In [1]:
from agents import Agent, OpenAIChatCompletionsModel, Runner, trace, WebSearchTool
from bs4 import BeautifulSoup
from datetime import datetime
from dotenv import load_dotenv
from workflow.common import extract_html
import gspread
from IPython.display import display, Markdown
import json
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, SummaryIndex
from llama_index.llms.openai import OpenAI
from llama_index.llms.openrouter import OpenRouter
from llama_index.core import Settings
from mailjet_rest import Client
from openai import OpenAI, AsyncOpenAI
import os
import requests
import pandas as pd
from pydantic import BaseModel, Field
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import tempfile
import time
from tqdm import tqdm
from webdriver_manager.chrome import ChromeDriverManager

load_dotenv(override=True)

C:\Users\User\anaconda3\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(

True

In [2]:
openai_api_key = os.getenv('OPENAI_API_KEY')
openai_base_url = os.getenv('BASE_URL')

client = AsyncOpenAI(
    base_url=openai_base_url,
    api_key=openai_api_key,
)

In [3]:
model = OpenAIChatCompletionsModel(model="openai/gpt-4o-mini", openai_client=client)
model_4o = OpenAIChatCompletionsModel(model="openai/gpt-4o:online", openai_client=client)
model_anthropic_online = OpenAIChatCompletionsModel(model="anthropic/claude-3.7-sonnet:online", openai_client=client)

In [4]:
llm = OpenRouter(
    api_key=openai_api_key,
    model="openai/gpt-4o-mini",        # Supports 128k context
    max_tokens=4000,                   # Allow long summaries
    context_window=128000,             # ← THIS IS THE KEY FIX
    temperature=0.1,
    timeout=600,                       # Prevent timeouts on large docs
    max_retries=3,
)

# llm = OpenRouter(
#     api_key=openai_api_key,
#     model="anthropic/claude-3-haiku",  # 200k context → solves everything
#     max_tokens=4000,
#     temperature=0.1,
#     timeout=900,
# )

Settings.llm = llm

Settings.context_window = 128000   # ← THIS FIXES THE NEGATIVE CONTEXT ERROR
Settings.chunk_size = 8192         # Larger chunks = fewer calls
Settings.chunk_overlap = 200

In [5]:
response = await client.chat.completions.create(
#     model="openai/gpt-4.1-nano",
    model = "qwen/qwen-2.5-72b-instruct",
    messages=[{"role": "user", "content": "Hi there."}],
)

print(response.choices[0].message.content.strip())

Hello! How can I assist you today?

In [4]:
spreadsheet_id = "1oHKGMuBynXOJkkQpDTAtjfsv-jrTXpzI2jj29VCCDaM"
sheet_gid = "0"
url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=csv&gid={sheet_gid}"
df = pd.read_csv(url)
df.head()

,Country,News,Website,Date,Headline,Link,Summary,Comment,Method
0,Afghanistan,Pajhwok Afghan News,https://www.pajhwok.com,9/12/2025,Doha Forum stresses Afghanistan’s role in regi...,https://pajhwok.com/2025/12/08/doha-forum-stre...,- The Doha Forum emphasized Afghanistan's pote...,NaN,NaN
1,Albania,Gazeta Panorama,https://www.panorama.com.al/,9/12/2025,"""We have not been divided!"" - The meetings of ...",https://www.panorama.com.al/skemi-qene-te-ndar...,- Salianji's meetings with Democratic Party me...,NaN,NaN
2,Algeria,El Khabar,https://www.elkhabar.com/fr,9/12/2025,The President of the Republic presides over a ...,https://www.elkhabar.com/fr/nation/le-presiden...,- The President of the Republic leads a meetin...,NaN,NaN
3,Andorra,Bondia.ad,https://www.bondia.ad/,9/12/2025,"Grandvalira closes the bridge with nearly 47,0...",https://www.bondia.ad/societat/grandvalira-tan...,- Grandvalira ski resort has successfully clos...,NaN,NaN
4,Angola,Jornal de Angola (state-owned),http://www.jornaldeangola.ao,9/12/2025,NaN,NaN,NaN,NaN,NaN

In [5]:
global_headlines_json = df.to_json(orient='records')

In [6]:
credentials_file = "global-headlines-474905-9494f258e0a5.json"
gc = gspread.service_account(filename=credentials_file)
spreadsheet = gc.open_by_key(spreadsheet_id)
worksheet = spreadsheet.worksheet("Sheet1")

In [5]:
def remove_html_tags(html_content):
    soup = BeautifulSoup(html_content, "html.parser")
    return soup.get_text()

In [6]:
website = "https://asia.nikkei.com/business/tech/semiconductors/tsmc-turns-japan-into-3rd-advanced-chip-base-as-ai-demand-soars/"

In [7]:
html_dict = extract_html.get_raw_html(website)
html_string = html_dict["html"]
clean_text = remove_html_tags(html_string)

if len(html_string) > 200000:
    html_string_input = clean_text
else:
    html_string_input = html_string

In [8]:
html_string_input

"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   TSMC turns Japan into 3rd advanced chip base as AI demand soars - Nikkei Asia\n  \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n        World\n       \n\n\n\n\n\n\n\n\n           China\n          \n\n\n\n\n\n\n\n           Japan\n          \n\n\n\n\n\n\n\n           India\n          \n\n\n\n\n\n\n\n           South Korea\n          \n\n\n\n\n\n\n\n           Indonesia\n          \n\n\n\n\n\n\n\n           Taiwan\n          \n\n\n\n\n\n\n\n           Thailand\n          \n\n\n\n\n\n\n\n           U.S.\n          \n\n\n\n\n\n\n\n\n\n           East Asia\n           \n\n\n\n\n\n\n\n\n              China\n             \n\n\n\n\n\n\n\n              Hong Kong\n             \n\n\n\n\n\n\n\n              Macao\n             \n\n\n\n\n\n\n\n              Taiwan\n             \n\n\n\n\n\n\n\n              Mongolia\n             \n\n\n\n\n\n\n\n              Japan\n             \n\n\n\n\n\n\n\n              South Korea\n             \n\n\n\n\n\n\n\n              North Korea\n             \n\n\n\n\n\n\n\n\n\n\n           Southeast Asia\n           \n\n\n\n\n\n\n\n\n              Indonesia\n             \n\n\n\n\n\n\n\n              Thailand\n             \n\n\n\n\n\n\n\n              Malaysia\n             \n\n\n\n\n\n\n\n              Singapore\n             \n\n\n\n\n\n\n\n              Philippines\n             \n\n\n\n\n\n\n\n              Vietnam\n             \n\n\n\n\n\n\n\n              Myanmar\n             \n\n\n\n\n\n\n\n              Cambodia\n             \n\n\n\n\n\n\n\n              Laos\n             \n\n\n\n\n\n\n\n              Brunei\n             \n\n\n\n\n\n\n\n              East Timor\n             \n\n\n\n\n\n\n\n\n\n\n           South Asia\n           \n\n\n\n\n\n\n\n\n              India\n             \n\n\n\n\n\n\n\n              Pakistan\n             \n\n\n\n\n\n\n\n              Afghanistan\n             \n\n\n\n\n\n\n\n              Bangladesh\n             \n\n\n\n\n\n\n\n              Sri Lanka\n             \n\n\n\n\n\n\n\n              Nepal\n             \n\n\n\n\n\n\n\n              Bhutan\n             \n\n\n\n\n\n\n\n              Maldives\n             \n\n\n\n\n\n\n\n\n\n\n           Central Asia\n           \n\n\n\n\n\n\n\n\n              Kazakhstan\n             \n\n\n\n\n\n\n\n              Uzbekistan\n             \n\n\n\n\n\n\n\n              Turkmenistan\n             \n\n\n\n\n\n\n\n              Tajikistan\n             \n\n\n\n\n\n\n\n              Kyrgyzstan\n             \n\n\n\n\n\n\n\n\n\n\n           Oceania\n           \n\n\n\n\n\n\n\n\n              Australia\n             \n\n\n\n\n\n\n\n              New Zealand\n             \n\n\n\n\n\n\n\n              Papua New Guinea\n             \n\n\n\n\n\n\n\n              Pacific Islands\n             \n\n\n\n\n\n\n\n\n\n\n           Rest of the World\n           \n\n\n\n\n\n\n\n\n              Middle East\n             \n\n\n\n\n\n\n\n              Russia & Caucasus\n             \n\n\n\n\n\n\n\n              North America\n             \n\n\n\n\n\n\n\n              Latin America\n             \n\n\n\n\n\n\n\n              Europe\n             \n\n\n\n\n\n\n\n              Africa\n             \n\n\n\n\n\n\n\n\n\n\n\n\n\n        Trending\n       \n\n\n\n\n\n\n\n\n           Japan election\n          \n\n\n\n\n\n\n\n           Trump administration\n          \n\n\n\n\n\n\n\n           Thai election\n          \n\n\n\n\n\n\n\n           Artificial intelligence\n          \n\n\n\n\n\n\n\n           Electric vehicles\n          \n\n\n\n\n\n\n\n           Supply Chain\n          \n\n\n\n\n\n\n\n           Taiwan tensions\n          \n\n\n\n\n\n\n\n           Bank of Japan\n          \n\n\n\n\n\n\n\n           Immigration\n          \n\n\n\n\n\n\n\n           ESG\n          \n\n\n\n\n\n\n\n           Explainer\n          \n\n\n\n\n\n\n\n\n\n\n        Business\n       \n\n\n\n\n\n\n\n\n           Business\n          \n\n\n\n\n\n\n\n           Semiconductors\n          \n\n\n\n\n\n\n\n           Automobiles\n          \n\n\n\n\n\n\n\n           Energy\n          \n\n\n\n\n\n\n\n           Transportation\n          \n\n\n\n\n\n\n\n           Retail\n          \n\n\n\n\n\n\n\n           Travel & Leisure\n          \n\n\n\n\n\n\n\n           Media & Entertainment\n          \n\n\n\n\n\n\n\n           Food & Beverage\n          \n\n\n\n\n\n\n\n           Finance\n          \n\n\n\n\n\n\n\n           Electronics\n          \n\n\n\n\n\n\n\n           Startups\n          \n\n\n\n\n\n\n\n           Business deals\n          \n\n\n\n\n\n\n\n\n\n\n        Markets\n       \n\n\n\n\n\n\n\n\n           Markets\n          \n\n\n\n\n\n\n\n           Equities\n          \n\n\n\n\n\n\n\n           Currencies\n          \n\n\n\n\n\n\n\n           Bonds\n          \n\n\n\n\n\n\n\n           Commodities\n          \n\n\n\n\n\n\n\n           Property\n          \n\n\n\n\n\n\n\n           IPO\n          \n\n\n\n\n\n\n\n           Wealth Management\n          \n\n\n\n\n\n\n\n\n\n\n        Tech\n       \n\n\n\n\n\n\n\n\n           Tech\n          \n\n\n\n\n\n\n\n           #techAsia\n          \n\n\n\n\n\n\n\n           China tech\n          \n\n\n\n\n\n\n\n           Startups\n          \n\n\n\n\n\n\n\n           Cryptocurrencies\n          \n\n\n\n\n\n\n\n           DealStreetAsia\n          \n\n\n\n\n\n\n\n\n\n\n        Politics\n       \n\n\n\n\n\n\n\n\n           Politics\n          \n\n\n\n\n\n\n\n           China\n          \n\n\n\n\n\n\n\n           Japan\n          \n\n\n\n\n\n\n\n           India\n          \n\n\n\n\n\n\n\n           South Korea\n          \n\n\n\n\n\n\n\n           Indonesia\n          \n\n\n\n\n\n\n\n           Taiwan\n          \n\n\n\n\n\n\n\n           Thailand\n          \n\n\n\n\n\n\n\n           U.S.\n          \n\n\n\n\n\n\n\n\n\n           East Asia\n           \n\n\n\n\n\n\n\n\n              China\n             \n\n\n\n\n\n\n\n              Hong Kong\n             \n\n\n\n\n\n\n\n              Macao\n             \n\n\n\n\n\n\n\n              Taiwan\n             \n\n\n\n\n\n\n\n              Mongolia\n             \n\n\n\n\n\n\n\n              Japan\n             \n\n\n\n\n\n\n\n              South Korea\n             \n\n\n\n\n\n\n\n              North Korea\n             \n\n\n\n\n\n\n\n\n\n\n           Southeast Asia\n           \n\n\n\n\n\n\n\n\n              Indonesia\n             \n\n\n\n\n\n\n\n              Thailand\n             \n\n\n\n\n\n\n\n              Malaysia\n             \n\n\n\n\n\n\n\n              Singapore\n             \n\n\n\n\n\n\n\n              Philippines\n             \n\n\n\n\n\n\n\n              Vietnam\n             \n\n\n\n\n\n\n\n              Myanmar\n             \n\n\n\n\n\n\n\n              Cambodia\n             \n\n\n\n\n\n\n\n              Laos\n             \n\n\n\n\n\n\n\n              Brunei\n             \n\n\n\n\n\n\n\n              East Timor\n             \n\n\n\n\n\n\n\n\n\n\n           South Asia\n           \n\n\n\n\n\n\n\n\n              India\n             \n\n\n\n\n\n\n\n              Pakistan\n             \n\n\n\n\n\n\n\n              Afghanistan\n             \n\n\n\n\n\n\n\n              Bangladesh\n             \n\n\n\n\n\n\n\n              Sri Lanka\n             \n\n\n\n\n\n\n\n              Nepal\n             \n\n\n\n\n\n\n\n              Bhutan\n             \n\n\n\n\n\n\n\n              Maldives\n             \n\n\n\n\n\n\n\n\n\n\n           Central Asia\n           \n\n\n\n\n\n\n\n\n              Kazakhstan\n             \n\n\n\n\n\n\n\n              Uzbekistan\n             \n\n\n\n\n\n\n\n              Turkmenistan\n             \n\n\n\n\n\n\n\n              Tajikistan\n             \n\n\n\n\n\n\n\n              Kyrgyzstan\n             \n\n\n\n\n\n\n\n\n\n\n           Oceania\n           \n\n\n\n\n\n\n\n\n              Australia\n             \n\n\n\n\n\n\n\n              New Zealand\n             \n\n\n\n\n\n\n\n              Papua New Guinea\n             \n\n\n\n\n\n\n\n              Pacific Islands\n             \n\n\n\n\n\n\n\n\n\n\n           Rest of the World\n           \n\n\n\n\n\n\n\n\n              Middle East\n             \n\n\n\n\n\n\n\n              Russia & Caucasus\n             \n\n\n\n\n\n\n\n              North America\n             \n\n\n\n\n\n\n\n              Latin America\n             \n\n\n\n\n\n\n\n              Europe\n             \n\n\n\n\n\n\n\n              Africa\n             \n\n\n\n\n\n\n\n\n\n\n\n\n\n        Economy\n       \n\n\n\n\n\n\n\n\n           Economy\n          \n\n\n\n\n\n\n\n           China\n          \n\n\n\n\n\n\n\n           Japan\n          \n\n\n\n\n\n\n\n           India\n          \n\n\n\n\n\n\n\n           South Korea\n          \n\n\n\n\n\n\n\n           Indonesia\n          \n\n\n\n\n\n\n\n           Taiwan\n          \n\n\n\n\n\n\n\n           Thailand\n          \n\n\n\n\n\n\n\n           U.S.\n          \n\n\n\n\n\n\n\n\n\n           East Asia\n           \n\n\n\n\n\n\n\n\n              China\n             \n\n\n\n\n\n\n\n              Hong Kong\n             \n\n\n\n\n\n\n\n              Macao\n             \n\n\n\n\n\n\n\n              Taiwan\n             \n\n\n\n\n\n\n\n              Mongolia\n             \n\n\n\n\n\n\n\n              Japan\n             \n\n\n\n\n\n\n\n              South Korea\n             \n\n\n\n\n\n\n\n              North Korea\n             \n\n\n\n\n\n\n\n\n\n\n           Southeast Asia\n           \n\n\n\n\n\n\n\n\n              Indonesia\n             \n\n\n\n\n\n\n\n              Thailand\n             \n\n\n\n\n\n\n\n              Malaysia\n             \n\n\n\n\n\n\n\n              Singapore\n             \n\n\n\n\n\n\n\n              Philippines\n             \n\n\n\n\n\n\n\n              Vietnam\n             \n\n\n\n\n\n\n\n              Myanmar\n             \n\n\n\n\n\n\n\n              Cambodia\n             \n\n\n\n\n\n\n\n              Laos\n             \n\n\n\n\n\n\n\n              Brunei\n             \n\n\n\n\n\n\n\n              East Timor\n             \n\n\n\n\n\n\n\n\n\n\n           South Asia\n           \n\n\n\n\n\n\n\n\n              India\n             \n\n\n\n\n\n\n\n              Pakistan\n             \n\n\n\n\n\n\n\n              Afghanistan\n             \n\n\n\n\n\n\n\n              Bangladesh\n             \n\n\n\n\n\n\n\n              Sri Lanka\n             \n\n\n\n\n\n\n\n              Nepal\n             \n\n\n\n\n\n\n\n              Bhutan\n             \n\n\n\n\n\n\n\n              Maldives\n             \n\n\n\n\n\n\n\n\n\n\n           Central Asia\n           \n\n\n\n\n\n\n\n\n              Kazakhstan\n             \n\n\n\n\n\n\n\n              Uzbekistan\n             \n\n\n\n\n\n\n\n              Turkmenistan\n             \n\n\n\n\n\n\n\n              Tajikistan\n             \n\n\n\n\n\n\n\n              Kyrgyzstan\n             \n\n\n\n\n\n\n\n\n\n\n           Oceania\n           \n\n\n\n\n\n\n\n\n              Australia\n             \n\n\n\n\n\n\n\n              New Zealand\n             \n\n\n\n\n\n\n\n              Papua New Guinea\n             \n\n\n\n\n\n\n\n              Pacific Islands\n             \n\n\n\n\n\n\n\n\n\n\n           Rest of the World\n           \n\n\n\n\n\n\n\n\n              Middle East\n             \n\n\n\n\n\n\n\n              Russia & Caucasus\n             \n\n\n\n\n\n\n\n              North America\n             \n\n\n\n\n\n\n\n              Latin America\n             \n\n\n\n\n\n\n\n              Europe\n             \n\n\n\n\n\n\n\n              Africa\n             \n\n\n\n\n\n\n\n\n\n\n\n\n\n        Features\n       \n\n\n\n\n\n\n\n\n           Trading Asia\n          \n\n\n\n\n\n\n\n           ASEAN Money\n          \n\n\n\n\n\n\n\n           Tech Asia\n          \n\n\n\n\n\n\n\n           China Up Close\n          \n\n\n\n\n\n\n\n           Policy Asia\n          \n\n\n\n\n\n\n\n           Big in Asia\n          \n\n\n\n\n\n\n\n           Datawatch\n          \n\n\n\n\n\n\n\n           Infographics\n          \n\n\n\n\n\n\n\n\n\n\n        Opinion\n       \n\n\n\n\n\n\n\n\n           Opinion\n          \n\n\n\n\n\n\n\n           Editor-in-Chief's Picks\n          \n\n\n\n\n\n\n\n           The Nikkei View\n          \n\n\n\n\n\n\n\n\n\n\n        Life & Arts\n       \n\n\n\n\n\n\n\n\n           Life & Arts\n          \n\n\n\n\n\n\n\n           Life\n          \n\n\n\n\n\n\n\n           Arts\n          \n\n\n\n\n\n\n\n           My Personal History\n          \n\n\n\n\n\n\n\n           Tea Leaves\n          \n\n\n\n\n\n\n\n           Eat & Drink\n          \n\n\n\n\n\n\n\n           Destinations\n          \n\n\n\n\n\n\n\n           Books\n          \n\n\n\n\n\n\n\n           Obituaries\n          \n\n\n\n\n\n\n\n\n\n\n        Watch & Listen\n       \n\n\n\n\n\n\n\n\n           Podcasts\n          \n\n\n\n\n\n\n\n           Video\n          \n\n\n\n\n\n\n\n           Photos\n          \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n        Semiconductors\n       \n\n\n       TSMC turns Japan into 3rd advanced chip base as AI demand soars\n      \n\n       Leading contract chipmaker unable to keep pace using Taiwan, US plants alone\n      \n\n\n\n\n\n\n       Cranes and pile drivers work on\xa0TSMC's planned second factory\xa0in Japan's Kumamoto prefecture in early February. (Photo by Toshiki Sasazu)\n      \n\n\n        HIDEAKI RYUGEN\n       \n\n\n\n          February 11, 2026 02:06 JST\n         \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n              TAIPEI -- Taiwan Semiconductor Manufacturing Co. has elevated Japan's role in its supply chain with plans to\xa0make more advanced chips there, a move that\xa0comes as demand for AI computing strains its existing production bases.\n             \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          Read Next\n         \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                 Semiconductors\n                \n\n\n\n                 TSMC to make advanced chips for AI at 2nd Japan plant\n                \n\n\n\n\n\n\n\n\n\n\n                Tech Asia\n               \n\n\n\n                Why are Taiwan's Nvidia suppliers investing billions in the US?\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Opinion\n               \n\n\n\n                TSMC's American expansion is not a surrender -- it's insurance for Taiwan\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Semiconductors\n               \n\n\n\n                TSMC plans record capex of up to $56bn for 2026 amid AI boom\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Semiconductors\n               \n\n\n\n                Japan chipmaker Rapidus tops $1bn in private investment as IBM aims to join\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Semiconductors\n               \n\n\n\n                Japan chipmaker Renesas sinks into red, missing out on AI boom\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Tech Asia\n               \n\n\n\n                What bubble? Big Tech's AI spending spree gathers pace in 2026\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Semiconductors\n               \n\n\n\n                How Arizona is cultivating talent for a US chip revival\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                Supply Chain\n               \n\n\n\n                HP, Dell, Acer and Asus mull using Chinese memory chips amid supply crunch\n               \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          Latest on\n          \n          Semiconductors\n         \n\n\n\n\n\n\n\n\n               Semiconductors\n              \n\n\n\n               Top China chipmaker SMIC says industry in 'crisis mode' over memory crunch\n              \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n               Semiconductors\n              \n\n\n\n               Japan chipmaker Renesas sinks into red, missing out on AI boom\n              \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n               Semiconductors\n              \n\n\n\n               TSMC to make advanced chips for AI at 2nd Japan plant\n              \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       Sponsored Content\n      \n\n\n\n\n\n\n\n\n\n\n\n\n\n       About Sponsored Content\n       \n        This content was commissioned by Nikkei's Global Business Bureau.\n       \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       Register for our newsletters\n      \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n        About Nikkei Asia\n       \n\n\n\n          About us\n         \n\n\n\n          Sitemap\n         \n\n\n\n          Announcements\n         \n\n\n\n          Advertise with Nikkei Asia\n         \n\n\n\n          About NIKKEI\n         \n\n\n\n\n\n        Support\n       \n\n\n\n          Help / Contact us\n         \n\n\n\n          View site tips\n         \n\n\n\n\n\n        Subscriptions\n       \n\n\n\n          Individual subscription\n         \n\n\n\n          Corporate subscription\n         \n\n\n\n          Gift subscription\n         \n\n\n\n\n\n        Legal & Privacy\n       \n\n\n\n          Terms of use\n         \n\n\n\n          Copyright\n         \n\n\n\n          Privacy & Cookie policy\n         \n\n\n\n          Information Transmission\n         \n\n\n\n\n\n        Event\n       \n\n\n\n          Nikkei Global Events\n         \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       No reproduction without permission.\n      \n\n\n\n\n\n\n\n\n\n\n\n\n\n"

In [39]:
prompt = f'''
You are good at reading html text, visualize the content, and identify the headline of the day.
Given this HTML text from a news website: {html_string_input}

CRITICAL REQUIREMENTS:
1. Identify the main headline of the day
2. ALWAYS translate to English if the headline is in any other language
3. Output ONLY the English headline text, nothing else
4. Do not include any non-English words or phrases
5. Ensure the headline is in proper English grammar and spelling
6. If the headline contains any non-English characters or words, translate them to English

IMPORTANT: The output must be 100% in English. If you cannot translate a headline to English, output "No headline found".
'''

response = await client.chat.completions.create(
#     model="anthropic/claude-3.7-sonnet",
    model="openai/gpt-4o-mini",
#     model="qwen/qwen2.5-vl-32b-instruct",
    messages=[{"role": "user", "content": prompt}],
)

headline = response.choices[0].message.content.strip()
print(headline)

"Quarter by quarter: What are the property prices in Sofia at the beginning of 2026?"

In [236]:
print(len(html_string))
print(len(clean_text))

134808
20743

In [237]:
# html_string

In [238]:
soup = BeautifulSoup(html_string, "html.parser")

# Extract all links
links = {a.get_text(): a for a in soup.find_all('a')}

# Get text without HTML tags
# text = soup.get_text()
links_on_page = ""

# Append links to the text
for link_text, url in links.items():
    links_on_page += f" [{link_text}]({url})"

In [239]:
links_on_page

' [\n     IMG\n    ](<a href="https://www.ibg.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="background-image: url(https://automedia.investor.bg/media/files/uploadedfiles/6e472c88bea7190ba9fda2ff6674e225-img-logo.png);     position: relative;  top: 3px;    width: 34px;     height: 13px;     overflow: hidden;     display: inline-block;     padding: 0;     text-indent: -9999px; background-repeat: no-repeat;     padding-right: 5px;" target="_blank">\n     IMG\n    </a>) [\n     Investor\n    ](<a href="https://www.investor.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Investor\n    </a>) [\n     Dnes\n    ](<a href="https://www.dnes.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Dnes\n    </a>) [\n     Bloombergtv\n    ](<a href="https://www.bloombergtv.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Bloombergtv\n    </a>) [\n     Bulgaria On Air\n    ](<a href="https://www.bgonair.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Bulgaria On Air\n    </a>) [\n     Gol\n    ](<a href="https://www.gol.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Gol\n    </a>) [\n     Tialoto\n    ](<a href="https://www.tialoto.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Tialoto\n    </a>) [\n     Az-jenata\n    ](<a href="https://www.az-jenata.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Az-jenata\n    </a>) [\n     Puls\n    ](<a href="https://www.puls.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Puls\n    </a>) [\n     Teenproblem\n    ](<a href="https://www.teenproblem.net/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Teenproblem\n    </a>) [\n     Automedia\n    ](<a href="https://www.automedia.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Automedia\n    </a>) [\n     Imoti.net\n    ](<a href="https://www.imoti.net/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Imoti.net\n    </a>) [\n     Rabota\n    ](<a href="https://www.rabota.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Rabota\n    </a>) [\n     Az-deteto\n    ](<a href="https://www.az-deteto.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Az-deteto\n    </a>) [\n     Blog\n    ](<a href="https://www.blog.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Blog\n    </a>) [\n     Start.bg\n    ](<a href="https://www.start.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Start.bg\n    </a>) [\n     Chernomore\n    ](<a href="https://www.chernomore.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Chernomore\n    </a>) [\n     Posoka\n    ](<a href="https://www.posoka.com/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Posoka\n    </a>) [\n     Boec\n    ](<a href="https://boec.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta" rel="noopener" style="" target="_blank">\n     Boec\n    </a>) [\n     Megavselena.bg\n    ](<a href="https://megavselena.bg/?utm_source=dnes&amp;utm_medium=link&amp;utm_campaign=lenta\t" rel="noopener" style="" target="_blank">\n     Megavselena.bg\n    </a>) [\n\n](<a href="https://dnes.bg">\n<img alt="DNES.BG" src="/media/img/svg/logo.svg" width="132"/>\n</a>) [\n\n       Новини Днес\n      \n      | 7\n     ](<a href="/last-articles">\n<h1>\n       Новини Днес\n      </h1>\n      | 7\n     </a>) [\n       България\n      ](<a href="/c/1-bulgaria" style="" target="_self">\n       България\n      </a>) [\n         Политика\n        ](<a href="//www.dnes.bg/c/57-politika" rel="noopener" style="" target="_self">\n         Политика\n        </a>) [\n         Общество\n        ](<a href="//www.dnes.bg/c/58-obshtestvo" rel="noopener" style="" target="_self">\n         Общество\n        </a>) [\n         Образование\n        ](<a href="//www.dnes.bg/c/59-obrazovanie" rel="noopener" style="" target="_self">\n         Образование\n        </a>) [\n         София\n        ](<a href="//www.dnes.bg/c/63-sofiya" rel="noopener" style="" target="_self">\n         София\n        </a>) [\n         Страната\n        ](<a href="//www.dnes.bg/c/64-stranata" rel="noopener" style="" target="_self">\n         Страната\n        </a>) [\n       Свободно време\n      ](<a href="/c/448-svobodno-vreme" style="" target="_self">\n       Свободно време\n      </a>) [\n         У-лицата\n        ](<a href="//www.dnes.bg/c/531-u-litsata" rel="noopener" style="" target="_self">\n         У-лицата\n        </a>) [\n         Без будилник\n        ](<a href="//www.dnes.bg/c/533-bez-budilnik\t" rel="noopener" style="" target="_self">\n         Без будилник\n        </a>) [\n         Звезди\n        ](<a href="//www.dnes.bg/c/30-zvezdi" rel="noopener" style="" target="_self">\n         Звезди\n        </a>) [\n         Музика\n        ](<a href="//www.dnes.bg/c/144-muzika" rel="noopener" style="" target="_self">\n         Музика\n        </a>) [\n         Миш-маш\n        ](<a href="//www.dnes.bg/c/7-mish-mash" rel="noopener" style="" target="_self">\n         Миш-маш\n        </a>) [\n         Артф@кти\n        ](<a href="//www.dnes.bg/c/142-artfkti" rel="noopener" style="" target="_self">\n         Артф@кти\n        </a>) [\n         Околосветско\n        ](<a href="//www.dnes.bg/c/557-okolosvetsko" rel="noopener" style="" target="_self">\n         Околосветско\n        </a>) [\n         Коли\n        ](<a href="//www.dnes.bg/c/8-koli" rel="noopener" style="" target="_self">\n         Коли\n        </a>) [\n       Последни новини\n      ](<a href="/last-articles" style="" target="_self">\n       Последни новини\n      </a>) [\n       Войната в украйна\n      ](<a href="//www.dnes.bg/c/581-voynata-v-ukrayna" rel="noopener" style="background-color: #85171e;" target="_self">\n       Войната в украйна\n      </a>) [\n       Крими\n      ](<a href="//www.dnes.bg/c/6-krimi" rel="noopener" style="" target="_self">\n       Крими\n      </a>) [\n       Свят\n      ](<a href="/c/2-svyat" style="" target="_self">\n       Свят\n      </a>) [\n       Фото\n      ](<a href="//www.dnes.bg/c/177-foto" rel="noopener" style="" target="_self">\n       Фото\n      </a>) [\n       Здраве\n      ](<a href="//www.dnes.bg/c/5-zdrave" rel="noopener" style="" target="_self">\n       Здраве\n      </a>) [\n       Бизнес\n      ](<a href="//www.dnes.bg/c/3-biznes" rel="noopener" style="" target="_self">\n       Бизнес\n      </a>) [\n       Технологии\n      ](<a href="//www.dnes.bg/c/4-tehnologii" rel="noopener" style="" target="_self">\n       Технологии\n      </a>) [\n       Спорт\n      ](<a href="/c/9-sport" style="" target="_self">\n       Спорт\n      </a>) [\n       Времето\n      ](<a href="//www.dnes.bg/c/558-vremeto" rel="noopener" style="" target="_self">\n       Времето\n      </a>) [\n       ТВ програма\n      ](<a href="//www.dnes.bg/tv" rel="noopener" style="" target="_self">\n       ТВ програма\n      </a>) [\n       Войната в Украйна\n      ](<a href="/c/581-voynata-v-ukrayna" style="" target="_self">\n       Войната в Украйна\n      </a>) [\n       ТВ Програма\n      ](<a href="/tv" style="" target="_self">\n       ТВ Програма\n      </a>) [\n       Лев и евро\n      ](<a href="/c/603-lev-i-evro">\n       Лев и евро\n      </a>) [\n         В кадър: Има задържани за погрома край централата на ДПС\n        ](<a href="https://www.dnes.bg/a/1-bulgaria/701984-v-kadar-ima-zadarzhani-za-pogroma-kray-tsentralata-na-dps">\n         В кадър: Има задържани за погрома край централата на ДПС\n        </a>) [\n           Пеевски: Румен Радев е истинският организатор на погромите, палежите и хаоса\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701982-peevski-rumen-radev-e-istinskiyat-organizator-na-pogromite-palezhite-i-haosa">\n           Пеевски: Румен Радев е истинският организатор на погромите, палежите и хаоса\n          </a>) [\n           Радев за протеста: Изходът е само един: оставка и предсрочни избори\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701979-radev-za-protesta-izhodat-e-samo-edin-ostavka-i-predsrochni-izbori">\n           Радев за протеста: Изходът е само един: оставка и предсрочни избори\n          </a>) [\n           В столичния район "Витоша" подменят 5400 осветителни тела\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701914-v-stolichniya-rayon-vitosha-podmenyat-5400-osvetitelni-tela">\n           В столичния район "Витоша" подменят 5400 осветителни тела\n          </a>) [\n           Пускат двупосочно движението по Дунав мост за празниците\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701919-puskat-dvuposochno-dvizhenieto-po-dunav-most-za-praznitsite">\n           Пускат двупосочно движението по Дунав мост за празниците\n          </a>) [\n           Дейвид Бекъм сподели какъв родител е\n          ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701899-deyvid-bekam-spodeli-kakav-roditel-e">\n           Дейвид Бекъм сподели какъв родител е\n          </a>) [\n           За 2,3 млн. евро: Продадоха картина на Рубенс, смятана за изгубена преди 400 г.\n          ](<a href="https://www.dnes.bg/a/2-svyat/701850-za-23-mln-evro-prodadoha-kartina-na-rubens-smyatana-za-izgubena-predi-400-g">\n           За 2,3 млн. евро: Продадоха картина на Рубенс, смятана за изгубена преди 400 г.\n          </a>) [\n           Израелският премиер Нетаняху поиска помилване по дело за корупция\n          ](<a href="https://www.dnes.bg/a/2-svyat/701873-izraelskiyat-premier-netanyahu-poiska-pomilvane-po-delo-za-koruptsiya">\n           Израелският премиер Нетаняху поиска помилване по дело за корупция\n          </a>) [\n           Терзиев: Най-големият протест бе опорочен от качулати хулигани\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701986-terziev-nay-golemiyat-protest-be-oporochen-ot-kachulati-huligani">\n           Терзиев: Най-големият протест бе опорочен от качулати хулигани\n          </a>) [\n           5 храни, които не са така здравословни, ако сте над 40\n          ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701734-5-hrani-koito-ne-sa-taka-zdravoslovni-ako-ste-nad-40">\n           5 храни, които не са така здравословни, ако сте над 40\n          </a>) [\n           Лазар Радков: Много е тежко положението в центъра!!!\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701985-lazar-radkov-mnogo-e-tezhko-polozhenieto-v-tsentara">\n           Лазар Радков: Много е тежко положението в центъра!!!\n          </a>) [\n           Кирил Петков: Протестът приключи, вандалите са маскирани ултраси\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701983-kiril-petkov-protestat-priklyuchi-vandalite-sa-maskirani-ultrasi">\n           Кирил Петков: Протестът приключи, вандалите са маскирани ултраси\n          </a>) [\n           Ивайло Мичрев: Трябваше да звъня на министър Даниел Митов, за да работи полицията\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701981-ivaylo-michrev-tryabvashe-da-zvanya-na-ministar-daniel-mitov-za-da-raboti-politsiyata">\n           Ивайло Мичрев: Трябваше да звъня на министър Даниел Митов, за да работи полицията\n          </a>) [\n         Виж всички новини\n        ](<a href="/last-articles">\n         Виж всички новини\n        </a>) [\n           Делян Добрев: Ако Борисов подаде оставка, ние няма да имаме бюджет\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701826-delyan-dobrev-ako-borisov-podade-ostavka-nie-nyama-da-imame-byudzhet">\n           Делян Добрев: Ако Борисов подаде оставка, ние няма да имаме бюджет\n          </a>) [\n           Залужний предлага Украйна да притежава ядрени оръжия като гаранция за сигурност\n          ](<a href="https://www.dnes.bg/a/581-voynata-v-ukrayna/701821-zaluzhniy-predlaga-ukrayna-da-pritezhava-yadreni-orazhiya-kato-garantsiya-za-sigurnost">\n           Залужний предлага Украйна да притежава ядрени оръжия като гаранция за сигурност\n          </a>) [\n           Заради срещата на Орбан с Путин: Навроцки отказа среща с унгарския премиер\n          ](<a href="https://www.dnes.bg/a/2-svyat/701813-zaradi-sreshtata-na-orban-s-putin-navrotski-otkaza-sreshta-s-ungarskiya-premier">\n           Заради срещата на Орбан с Путин: Навроцки отказа среща с унгарския премиер\n          </a>) [\n           Три непокорни монахини окупираха манастира си, не искали в старчески дом\n          ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701654-tri-nepokorni-monahini-okupiraha-manastira-si-ne-iskali-v-starcheski-dom">\n           Три непокорни монахини окупираха манастира си, не искали в старчески дом\n          </a>) [\n           Турските митничари на Капъкуле заловиха 23 кг скънк на влизане от България\n          ](<a href="https://www.dnes.bg/a/2-svyat/701857-turskite-mitnichari-na-kapakule-zaloviha-23-kg-skank-na-vlizane-ot-balgariya">\n           Турските митничари на Капъкуле заловиха 23 кг скънк на влизане от България\n          </a>) [\n           Калас: Ако се мисли за ограничаване на украинската армия, да се помисли и за руската\n          ](<a href="https://www.dnes.bg/a/2-svyat/701870-kalas-ako-se-misli-za-ogranichavane-na-ukrainskata-armiya-da-se-pomisli-i-za-ruskata">\n           Калас: Ако се мисли за ограничаване на украинската армия, да се помисли и за руската\n          </a>) [\n           Триъгълникът на властта почерня от хора, протестиращи срещу Бюджет 2026 ВИДЕО\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701965-triagalnikat-na-vlastta-pochernya-ot-hora-protestirashti-sreshtu-byudzhet-2026-video">\n           Триъгълникът на властта почерня от хора, протестиращи срещу Бюджет 2026 ВИДЕО\n          </a>) [\n           Зеленски от Париж: Войната трябва да приключи възможно най-скоро\n          ](<a href="https://www.dnes.bg/a/581-voynata-v-ukrayna/701945-zelenski-ot-parizh-voynata-tryabva-da-priklyuchi-vazmozhno-nay-skoro">\n           Зеленски от Париж: Войната трябва да приключи възможно най-скоро\n          </a>) [\n           Следващият ход на Русия: Кой Путин ще се появи на мирните преговори?\n          ](<a href="https://www.dnes.bg/a/2-svyat/701798-sledvashtiyat-hod-na-rusiya-koy-putin-shte-se-poyavi-na-mirnite-pregovori">\n           Следващият ход на Русия: Кой Путин ще се появи на мирните преговори?\n          </a>) [\n           Асен Василев с музикален дебют: Запя "Кой разпореди това безобразие" с пънк банда ВИДЕО\n          ](<a href="https://www.dnes.bg/a/1-bulgaria/701774-asen-vasilev-s-muzikalen-debyut-zapya-koy-razporedi-tova-bezobrazie-s-pank-banda-video">\n           Асен Василев с музикален дебют: Запя "Кой разпореди това безобразие" с пънк банда ВИДЕО\n          </a>) [\n         Радев за протеста: Изходът е само един: оставка и предсрочни избори\n        ](<a href="https://www.dnes.bg/a/1-bulgaria/701979-radev-za-protesta-izhodat-e-samo-edin-ostavka-i-predsrochni-izbori">\n         Радев за протеста: Изходът е само един: оставка и предсрочни избори\n        </a>) [\n         НА ЖИВО: Погром в центъра на София - горят кофи, унищожиха полицейска кола\n        ](<a href="https://www.dnes.bg/a/1-bulgaria/701975-na-zhivo-pogrom-v-tsentara-na-sofiya-goryat-kofi-unishtozhiha-politseyska-kola">\n         НА ЖИВО: Погром в центъра на София - горят кофи, унищожиха полицейска кола\n        </a>) [\n         В кадър: Хиляди крещяха "Оставка" в Триъгълника на властта\n        ](<a href="https://www.dnes.bg/a/1-bulgaria/701970-v-kadar-hilyadi-kreshtyaha-ostavka-v-triagalnika-na-vlastta">\n         В кадър: Хиляди крещяха "Оставка" в Триъгълника на властта\n        </a>) [\n         Сутрешни мъгли ни чакат във вторник, времето през деня – тихо и приятно\n        ](<a href="https://www.dnes.bg/a/558-vremeto/701891-sutreshni-magli-ni-chakat-vav-vtornik-vremeto-prez-denya-tiho-i-priyatno">\n         Сутрешни мъгли ни чакат във вторник, времето през деня – тихо и приятно\n        </a>) [\n         Времето днес: Валежите спират, остава студено\n        ](<a href="https://www.dnes.bg/a/558-vremeto/701831-vremeto-dnes-valezhite-spirat-ostava-studeno">\n         Времето днес: Валежите спират, остава студено\n        </a>) [\n         И утре ще е студено, но валежите спират\n        ](<a href="https://www.dnes.bg/a/558-vremeto/701789-i-utre-shte-e-studeno-no-valezhite-spirat">\n         И утре ще е студено, но валежите спират\n        </a>) [\n       Новият световен кикбокс шампион Вито Косар излиза на SENSHI 29\n      ](<a href="https://www.dnes.bg/a/9-sport/701951-noviyat-svetoven-kikboks-shampion-vito-kosar-izliza-na-senshi-29">\n       Новият световен кикбокс шампион Вито Косар излиза на SENSHI 29\n      </a>) [\n          Бракониер на риба от Монтана ще лежи година и половина в затвора\n         ](<a href="https://www.dnes.bg/a/1-bulgaria/701930-brakonier-na-riba-ot-montana-shte-lezhi-godina-i-polovina-v-zatvora">\n          Бракониер на риба от Монтана ще лежи година и половина в затвора\n         </a>) [\n          Жечо Станков за спрения ток: Има съмнения за умишлена намеса\n         ](<a href="https://www.dnes.bg/a/1-bulgaria/701980-zhecho-stankov-za-spreniya-tok-ima-samneniya-za-umishlena-namesa">\n          Жечо Станков за спрения ток: Има съмнения за умишлена намеса\n         </a>) [\n          8 начина да носите прическа "на етажи" - модерна многопластова визия\n         ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701871-8-nachina-da-nosite-pricheska-na-etazhi-moderna-mnogoplastova-viziya">\n          8 начина да носите прическа "на етажи" - модерна многопластова визия\n         </a>) [\n          Бен Афлек отпразнува Денят на благодарността с бившата си\n         ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701898-ben-aflek-otpraznuva-denyat-na-blagodarnostta-s-bivshata-si">\n          Бен Афлек отпразнува Денят на благодарността с бившата си\n         </a>) [\n          "Продължаваме промяната" поиска оставката на Даниел Митов\n         ](<a href="https://www.dnes.bg/a/1-bulgaria/701978-prodalzhavame-promyanata-poiska-ostavkata-na-daniel-mitov">\n          "Продължаваме промяната" поиска оставката на Даниел Митов\n         </a>) [\n          Спонсорирана публикация\n         ](<a href="/c/3-biznes">\n          Спонсорирана публикация\n         </a>) [\n          Там, където магията е реалност: Звездният декември в LunOr започва с Любо Киров\n         ](<a href="https://www.dnes.bg/a/448-svobodno-vreme/701651-tam-kadeto-magiyata-e-realnost-zvezdniyat-dekemvri-v-lunor-zapochva-s-lyubo-kirov">\n          Там, където магията е реалност: Звездният декември в LunOr започва с Любо Киров\n         </a>) [\n          От ЕРМ Запад обясниха защо е спрял токът в центъра на София\n         ](<a href="https://www.dnes.bg/a/1-bulgaria/701977-ot-erm-zapad-obyasniha-zashto-e-spryal-tokat-v-tsentara-na-sofiya">\n          От ЕРМ Запад обясниха защо е спрял токът в центъра на София\n         </a>) [\n          Ситуацията край централата на ГЕРБ е спокойна\n         ](<a href="https://www.dnes.bg/a/1-bulgaria/701976-situatsiyata-kray-tsentralata-na-gerb-e-spokoyna">\n          Ситуацията край централата на ГЕРБ е спокойна\n         </a>) [\n          MAX Movie – киното у дома е още по-завладяващо изживяване с новия филмов канал на А1

In [240]:
headline = response.choices[0].message.content.strip()
headline

'Arrests made for the rampage near the DPS headquarters'

In [241]:
prompt = f'''
Given this identified headline on a news website: "{headline}"
Note that the headline is being translated into English if the original text is non-English.
Please check if the link to that headline is in {links_on_page[:150000]}
If so, please output only the link. 
Note that sometime only the relative url is included. If so, you need to output the absolute url with the root website {website}.
If no link is founded, just output 'N/A'
Do not output anything else other than the link
Do not output any html tags e.g., '<a href=', '</a>'
'''

response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [242]:
link = response.choices[0].message.content
link

'https://www.dnes.bg/a/1-bulgaria/701984-v-kadar-ima-zadarzhani-za-pogroma-kray-tsentralata-na-dps'

In [30]:
link = "http://www.aastocks.com/sc/mobile/news.aspx?newsid=NOW.1496320&newstype=71&newssource=AAFN"

In [31]:
html_dict = extract_html.get_raw_html(link)

In [32]:
html_string = html_dict["html"]
clean_text = remove_html_tags(html_string)
clean_text

'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   《大行》里昂：携程短期利润率或受压  料中国反垄断行动更常态化财经新闻 Financial News\n  \n\n\n\n\n\n\n\n\n\n\n       桌面版\n      \n\n\n\n\n\n\n\n\n\n\n\n        最新搜看股票\n        \n\n\n\n\n\n\n\n\n\n       报价\n      \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       实时行情\n      \n\n\n\n\n\n\n\n       市场\n      \n\n\n\n\n\n\n\n       新闻\n      \n\n\n\n\n\n\n\n       指数\n      \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          返回\n         \n\n\n         放大\xa0+\n        \n\n         缩小\xa0-\n        \n\n         重点新闻\n        \n\n\n\n\n\n         《大行》里昂：携程短期利润率或受压  料中国反垄断行动更常态化\n        \n\n\n\n\n\n\n\n             推荐\n            \n\n             14\n            \n\n\n\n\n\n\n\n             利好\n            \n\n             16\n            \n\n\n\n\n\n\n\n             利淡\n            \n\n             21\n            \n\n\n\n\n\n\n          AASTOCKS新闻\n         \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n         里昂发表研究报告指，国家市场监管总局立案调查携程-S(09961.HK)垄断行为，目前公司持续正常营运，惟受此消息影响，携程(TCOM.US)美股ADR价格下跌17%。\n         \n\n         里昂估计中国的反垄断行动或会变得更常态化。该行认为，此次针对携程的调查可能集中於独家合作权和平台是否利用其优势向商家施压。该行相信，即使携程失去商家独家合作权，凭藉其庞大的交易量及与酒店的长期合作关系，料仍可保持强劲的竞争力。不过，携程或需向商家提供更多支援，短期内可能会压低利润率。\n         \n\n\n\n\n\n           相关内容\n          \n\n\n            《大行》大和：春季行情提前到来 料A股迈向「慢牛」\n           \n\n\n\n         该行预期，携程在2025至26年的经调整经营利润率约为29%，然而，商家支援措施或对利润率构成压力，但监於线上旅游市场竞争相对温和，相信公司可通过进一步改善营运效率来抵销部分影响。(sl/u)\n         \n\n         AASTOCKS新闻\n        \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          已将连结复制到剪贴簿\n          \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       备注\n      \n\n\n        (1) 所有香港指数为即时指数\n       \n\n\n\n\n\n\n\n      主页\n     \n     |\n     \n      实时行情\n     \n     |\n     \n      市场\n     \n     |\n     \n      新闻\n     \n     |\n     \n      指数\n     \n\n\n      意见箱\n     \n     |\n     \n      免责声明\n     \n\n\n\n      查看:\n      \n       手机\n      \n\n       |\n      \n\n       桌面\n      \n\n\n\n      语言:\n      \n       繁\n      \n\n       |\n      \n\n       简\n      \n\n       |\n      \n\n       EN\n      \n\n\n\n\n\n      回到页顶\n     \n\n\n     联络我们\n     \n     支援电邮:\n     \n      support@aastocks.com\n     \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'

In [33]:
# clean_text

In [35]:
prompt = f'''
You are a capable journalist. This is the content of a news: {clean_text}
Please extract the title of the news in its original language. Do not output anything else
'''

response = await client.chat.completions.create(
#     model="gpt-4o-mini",
    model="deepseek/deepseek-v3.2",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [36]:
summary = response.choices[0].message.content
print(summary)

《大行》里昂：携程短期利润率或受压  料中国反垄断行动更常态化

In [ ]:
prompt = f'''
You are a capable journalist. This is the headline of today: {clean_text}
Please summarize in 2-3 English bullets to capture the key informaiton. Each bullet should be very concise.
You may assume your readers know nothing about the country's news and politics
The source may not be in English. But make sure the summary is in English
If the text doesn't seem to be a legit news article, just output 'N/A'. Do not make things up.
IMPORTANT: When referring to Donald Trump, always refer to him as "President Donald Trump" or "US President Donald Trump". He is the CURRENT President of the United States as of 2025. Do NOT label him as "Former President" or "Ex-President" - this is incorrect.
'''

response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [ ]:
remove_html_tags_keep_links(html_string)

In [ ]:
country = "Algeria"
website = df[df['Country'] == country]['Website'].values[0]
print(f"Website: {website}")

In [ ]:
def find_row_number(df, country):
    row_number = df.index[df['Country'] == country].tolist()
    return row_number[0] + 2 if row_number else None

row_number = find_row_number(df, country)
today = datetime.now().strftime("%d/%m/%Y")

worksheet.update_cell(row_number, 4, today)
worksheet.update_cell(row_number, 5, headline_info["headline"])
worksheet.update_cell(row_number, 6, headline_info["link"])

print(f"Updated {country}")

In [ ]:
countries = list(df["Country"])

for country in tqdm(countries[:5]):
    try:
        website = df[df['Country'] == country]['Website'].values[0]
        if pd.isna(website) or website == "":
            continue
        
        html_dict = extract_html.get_raw_html(website)
        if not html_dict:
            continue
        
        html_string = html_dict["html"]
        clean_text = remove_html_tags(html_string)
        
        prompt = f'''
        Given this HTML text: {clean_text}
        Identify the headline and link.
        Output as JSON with "headline" and "link" keys.
        '''
        
        response = client.beta.chat.completions.parse(
            model="openai/gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format=Headline,
        )
        
        headline_info = json.loads(response.choices[0].message.content)
        
        row_number = find_row_number(df, country)
        today = datetime.now().strftime("%d/%m/%Y")
        
        worksheet.update_cell(row_number, 4, today)
        worksheet.update_cell(row_number, 5, headline_info["headline"])
        worksheet.update_cell(row_number, 6, headline_info["link"])
        
        print(f"✅ {country}: {headline_info['headline'][:50]}...")
        
    except Exception as e:
        print(f"❌ {country}: {str(e)}")

In [15]:
INSTRUCTIONS = (
f'''
You are a global news curator responsible for creating a comprehensive newsletter based on the latest headlines from every country. Your goal is to summarize the most significant news stories, focusing on global politics, major local developments, natural disasters, and other impactful events.

Gather Headlines: You will receive a list of headlines from various countries.

Prioritize Content: Identify and prioritize the most important news stories that have global relevance or significant local impact. You should also include news from lesser-known countries to give the readers a broader perspective.

Create an Outline:

Headlines around the globe - {datetime.now().strftime("%b %d, %Y")}
Daily news sourced directly from local newspapers

Regional Highlights:
Africa / Middle East: Key developments and notable events.
Americas: Focus on political changes and major local news.
Asia: Important updates on economic and political situations.
Europe: Significant political events and social movements.
Oceania: Relevant stories and developments.

Each news should be like:
- **[Israel-Hamas Ceasefire](https://www.haaretz.com/ty-tag/2023-israel-gaza-war-0000018b-1458-df09-a9db-5df99abd0000)**: A temporary ceasefire has been agreed between Israel and Hamas, aiming to facilitate humanitarian efforts and stabilize the region. (source of the news)\n

The first few words should accurately summarize what that news in about.
The classification of location should be based on where the event took place, not the location of the news source.

Draft the Newsletter: Write a detailed and engaging newsletter that:

Summarizes each headline clearly and concisely.
Provides context where necessary to enhance understanding. The country / newspaper publishing the news may be relevant.
Includes the sources in a link if available.
Maintains an organized flow for easy reading.
If needed, search the web for additional context / information. You may not assume the readers know the name of a political person or a city.
Do not invent your own facts. This is important.
Final Output: Ensure the newsletter is formatted in Markdown, aiming for 1500 words at least. The content should be well-structured and informative, catering to a global audience interested in current affairs.
'''
)

writer_agent = Agent(
    name="WriterAgent",
    instructions=INSTRUCTIONS,
    model=model_anthropic_online,
)

In [7]:
result = await Runner.run(writer_agent, global_headlines_json)

[non-fatal] Tracing client error 403: {"error":{"code":"unsupported_country_region_territory","message":"Country, region, or territory not supported","param":null,"type":"request_forbidden"}}
[non-fatal] Tracing client error 403: {"error":{"code":"unsupported_country_region_territory","message":"Country, region, or territory not supported","param":null,"type":"request_forbidden"}}

In [8]:
display(Markdown(result.final_output))

# Headlines around the globe - Nov 02, 2025
## Daily news sourced directly from local newspapers

### Regional Highlights

#### Africa / Middle East
- **[Trump Threatens Nigeria](https://www.krone.at/3945418)**: Former US President Donald Trump has issued threats of military action against Nigeria, citing concerns over alleged killings of Christians.
- **[M23 Offensive in DR Congo](https://en.wikipedia.org/wiki/2025_Bukavu_offensive)**: The M23 rebel group launched a campaign in South Kivu, Democratic Republic of Congo, in February 2025, continuing the regional instability.
- **[Palestinian Authority Operation in Tubas](https://en.wikipedia.org/wiki/2024_Palestinian_Authority_operation_in_Tubas)**: The Palestinian Authority conducted "Operation Protecting the Nation" in the West Bank's Tubas Governorate from October to November 2024.
- **[Safadi Urges Gaza Ceasefire Adherence](https://jordantimes.com/news/local/safadi-urges-full-adherence-to-gaza-ceasefire-action-on-humanitarian-crisis)**: Jordan's Foreign Minister calls for complete compliance with the Gaza ceasefire and immediate humanitarian action.

#### Americas
- **[US Strikes on Drug-Running Boats](https://apnews.com/article/drug-cartels-hegseth-pacific-8f9f65dd67c0bc55b6dd70b109df0216)**: The US launched three strikes on alleged drug-trafficking vessels off Colombia's coast, resulting in 14 fatalities.
- **[Blue Jays Lead in World Series](https://www.cbc.ca/news/livestory/blue-jays-lead-3-1-in-fiery-winner-take-all-world-series-game-7-9.6963371)**: The Toronto Blue Jays are leading 3-1 in the decisive Game 7 of the World Series.
- **[Hurricane Melissa Devastation](https://www.breakingbelizenews.com/2025/11/01/international-news-hurricane-melissa-death-toll-rises-above-50-as-caribbean-reels-from-apocalyptic-damage/)**: Hurricane Melissa has caused over 50 deaths across the Caribbean, with Jamaica reporting 28 casualties and widespread "apocalyptic" damage.
- **[Catatumbo Clashes in Colombia](https://en.wikipedia.org/wiki/2025_Catatumbo_clashes)**: The National Liberation Army has conducted attacks in Colombia's Catatumbo region, escalating existing conflicts.

#### Asia
- **[Xi Returns from APEC Meeting](https://english.news.cn/20251101/f7cc64f12d5b4dab8e3dc753a89a208a/c.html)**: Chinese President Xi Jinping has returned to Beijing after attending the APEC meeting and conducting a state visit to South Korea.
- **[Kim Jong Un Inspects Hospital](https://www.nknews.org/2025/10/kim-jong-un-inspects-new-hospital-at-center-of-plans-for-health-care-reform/)**: North Korean leader Kim Jong Un visited a new hospital, highlighting healthcare reform plans amid ongoing economic challenges.
- **[Uzbekistan Qualifies for World Cup](https://uzreport.news/football/o-zbekiston-ilk-bor-mundialga-chiqdi)**: Uzbekistan has qualified for the FIFA World Cup for the first time in its history, marking a significant milestone for the country's football program.
- **[Ukrainian Drones Strike Russian Oil Terminal](https://kyivindependent.com/ukraine-reportedly-strikes-oil-terminal-in-russias-krasnodar-krai/)**: Ukrainian forces launched drone strikes against an oil terminal in Russia's Krasnodar Krai, continuing their strategy of targeting Russian infrastructure.

#### Europe
- **[UK Train Stabbing](https://www.smh.com.au/world/europe/multiple-people-stabbed-on-uk-train-in-appalling-incident-20251102-p5n733.html)**: Nine people suffered life-threatening injuries following a mass stabbing on a train in Cambridgeshire, UK, with two suspects arrested.
- **[German Nationals Killed in Avalanche](https://www.spiegel.de/panorama/suedtirol-fuenf-deutsche-bei-lawinenunglueck-getoetet-a-2f454053-926f-4c2f-bbbc-f28cea8b1220)**: Five German citizens have died in an avalanche accident in South Tyrol, Italy.
- **[Russia-Ukraine War Continues](https://www.rp.pl/swiat/art43271141-wojna-rosji-z-ukraina-dzien-1347)**: The conflict between Russia and Ukraine has reached day 1,347, with continued intense fighting in eastern regions.
- **[Estonian PM Criticizes Latvia](https://news.err.ee/1609845303/estonian-pm-criticizes-latvia-s-plan-to-withdraw-from-istanbul-convention)**: Estonia's Prime Minister has expressed disapproval of Latvia's decision to withdraw from the Istanbul Convention, which aims to combat violence against women.

#### Oceania
- **[Bus Fire in Auckland](https://www.stuff.co.nz/nz-news/360873281/bus-hits-overpass-and-catches-fire-aucklands-north-shore)**: A bus caught fire after hitting an overpass on Auckland's North Shore in New Zealand, with no injuries reported.
- **[UAE Aid to Hurricane-Hit Caribbean](https://www.thenationalnews.com/news/uae/2025/10/31/uae-sends-crucial-aid-to-caribbean-communities-hit-by-deadly-hurricane-melissa/)**: The United Arab Emirates has sent essential aid to Caribbean communities devastated by Hurricane Melissa.
- **[Tonga XIII Rugby Preparations](https://matangitonga.to/2025/10/30/tonga-xiii-set-take-kiwis-after-losing-samoa)**: Tonga's rugby team is preparing to face the New Zealand Kiwis after suffering a recent loss to Samoa.

---

## Detailed News Reports

### Political Developments

#### **[Trump Threatens Military Action Against Nigeria](https://guardian.ng/news/trump-threatens-military-action-in-nigeria-over-killing-of-christians/)**
Former US President Donald Trump has threatened military intervention in Nigeria over alleged killings of Christians. As reported by Nigeria's The Guardian and Austria's Kronen Zeitung, the controversial statement has raised significant concerns about potential US foreign policy shifts and implications for US-Nigerian relations. The threat has sparked widespread reactions regarding international intervention and religious freedom issues.

#### **[Palestinian Authority-West Bank Conflict](https://en.wikipedia.org/wiki/2024_Palestinian_Authority_operation_in_Tubas)**
The Palestinian Authority conducted an operation in the Tubas Governorate of the West Bank from October to late November 2024. The operation, dubbed "Protecting the Nation," was part of the broader Palestinian Authority–West Bank militias conflict and the ongoing Middle Eastern crisis. This development illustrates the complex internal Palestinian dynamics amid regional tensions.

#### **[Russia Reaffirms Support for Venezuela](http://www.eluniversal.com/internacional/219338/rusia-reafirma-su-solido-apoyo-a-venezuela-y-aboga-por-la-preservacion-de-america-latina-como-zona)**
Russia has reiterated its strong support for Venezuela and advocated for maintaining Latin America as a zone of peace, according to Venezuela's El Universal. This declaration comes amid heightened regional tensions and underscores Russia's strategic interests in the Americas, opposing external interference in Venezuelan affairs.

#### **[Estonia Criticizes Latvia's Convention Withdrawal](https://news.err.ee/1609845303/estonian-pm-criticizes-latvia-s-plan-to-withdraw-from-istanbul-convention)**
Estonia's Prime Minister has publicly criticized Latvia's decision to withdraw from the Istanbul Convention, which aims to combat violence against women. This disagreement highlights growing divisions within Baltic states on social policy issues and demonstrates Estonia's commitment to international frameworks protecting women's rights.

---

### Armed Conflicts & Security

#### **[M23 Campaign in DR Congo](https://en.wikipedia.org/wiki/2025_Bukavu_offensive)**
The M23 rebel group conducted an offensive in South Kivu, Democratic Republic of Congo, from February 5-16, 2025. This campaign represents a continuation of the ongoing M23 insurgency that began in 2022, further destabilizing the eastern DRC and threatening civilian populations in the region.

#### **[Catatumbo Clashes in Colombia](https://en.wikipedia.org/wiki/2025_Catatumbo_clashes)**
The National Liberation Army (ELN) has carried out attacks in Colombia's Catatumbo region, according to reports. These clashes occur in Norte de Santander and represent ongoing insurgent activity in Colombia despite peace efforts with other armed groups in recent years.

#### **[Russia-Ukraine War Day 1347](https://www.rp.pl/swiat/art43271141-wojna-rosji-z-ukraina-dzien-1347)**
The war between Russia and Ukraine has reached its 1,347th day, with continued intense fighting in eastern Ukraine. Polish newspaper Rzeczpospolita reports that Russia has intensified military operations while Ukraine's forces claim significant Russian casualties amid their counteroffensive efforts. Diplomatic talks remain stalled as both sides prepare for potential further escalation.

#### **[Ukrainian Drone Strikes on Russian Oil Terminal](https://kyivindependent.com/ukraine-reportedly-strikes-oil-terminal-in-russias-krasnodar-krai/)**
Ukrainian forces have conducted drone strikes against an oil terminal in Russia's Krasnodar Krai, The Kyiv Independent reports. This attack represents a continuation of Ukraine's strategy to disrupt Russia's logistics and fuel supply infrastructure, impacting Russia's military capabilities.

---

### Natural Disasters & Humanitarian Crises

#### **[Hurricane Melissa Death Toll Rises](https://www.breakingbelizenews.com/2025/11/01/international-news-hurricane-melissa-death-toll-rises-above-50-as-caribbean-reels-from-apocalyptic-damage/)**
Hurricane Melissa has caused over 50 deaths across the Caribbean, with survivors describing the aftermath as "apocalyptic," according to Breaking Belize News. In Jamaica alone, the death toll has reached 28, as reported by The Gleaner. Relief efforts are underway, but challenges persist due to the extensive destruction and ongoing weather concerns.

#### **[UAE Sends Aid to Caribbean Communities](https://www.thenationalnews.com/news/uae/2025/10/31/uae-sends-crucial-aid-to-caribbean-communities-hit-by-deadly-hurricane-melissa/)**
The United Arab Emirates has dispatched critical aid to Caribbean communities devastated by Hurricane Melissa, The National reports. This assistance aims to support recovery efforts and provide essential supplies for rebuilding and humanitarian relief in the affected areas.

#### **[November Rainfall Drenches Bangladesh](https://www.thedailystar.net/environment/weather/news/november-rain-drenches-dhaka-parts-country-4024631)**
Dhaka and various regions of Bangladesh are experiencing heavy rainfall in November, The Daily Star reports. The unseasonal downpour has led to disruptions in daily activities and raised concerns about potential flooding. Authorities are monitoring the situation closely to implement necessary safety measures.

#### **[Avalanche Kills Five Germans in South Tyrol](https://www.spiegel.de/panorama/suedtirol-fuenf-deutsche-bei-lawinenunglueck-getoetet-a-2f454053-926f-4c2f-bbbc-f28cea8b1220)**
Five German nationals died in an avalanche in South Tyrol, Italy, according to Der Spiegel. The incident occurred in a popular skiing area, and despite rescue operations, all five victims were confirmed deceased at the scene. This tragedy highlights the ongoing dangers of winter sports in Alpine regions.

---

### Crime & Justice

#### **[Louvre Heist Update](https://www.lemonde.fr/en/france/article/2025/11/01/louvre-heist-suspects-brought-before-paris-magistrates_6746992_7.html)**
Two additional suspects have been charged in connection with the Louvre museum heist in Paris, while three previously detained individuals have been released, Le Monde reports. The investigation into this high-profile art theft continues as authorities search for more leads and attempt to recover the stolen items.

#### **[Mass Stabbing on UK Train](https://www.smh.com.au/world/europe/multiple-people-stabbed-on-uk-train-in-appalling-incident-20251102-p5n733.html)**
Nine people suffered life-threatening injuries following a knife attack on a train in Cambridgeshire, UK. The Sydney Morning Herald reports that authorities have described the incident as "appalling," and emergency services responded promptly to the scene. Two individuals have been arrested in connection with the attack, according to multiple European news outlets.

#### **[Prosecutor Investigates Costa Rican OIJ Director](https://www.nacion.com/sucesos/fiscalia-indago-a-director-del-oij-randall-zuniga/7I7NITHXABGBFEIJRH3HHGNEVQ/story/)**
The Director of Costa Rica's Judicial Investigation Organization (OIJ), Randall Zúñiga, is under investigation for alleged sexual offenses, La Nación reports. This case has raised significant concerns about leadership within one of the country's most important law enforcement institutions and may have broader implications for Costa Rica's judicial system.

#### **[University Student Killed at Halloween Party in Bogotá](https://www.eltiempo.com/bogota/universidad-de-los-andes-se-pronucia-sobre-la-muetre-de-jaime-esteban-moreno-tras-una-fiesta-de-halloween-en-bogota-3505304)**
A student from the University of Los Andes was fatally shot during a Halloween party in Bogotá, Colombia, El Tiempo reports. The incident has raised concerns about safety during social events in the city, and authorities are investigating the circumstances surrounding this tragic event.

---

### Sports & Entertainment

#### **[Blue Jays in World Series Game 7](https://www.cbc.ca/news/livestory/blue-jays-lead-3-1-in-fiery-winner-take-all-world-series-game-7-9.6963371)**
The Toronto Blue Jays are leading 3-1 in the decisive Game 7 of the World Series, CBC News reports. This winner-take-all matchup has created a tense atmosphere as the Blue Jays seek their first World Series title in decades.

#### **[Springboks Dominate Japan at Wembley](https://www.news24.com/sport/rugby/springboks/live-test-rugby-springboks-v-japan-20251101-0530)**
South Africa's Springboks secured a convincing victory against Japan at Wembley Stadium, scoring nine tries in a dominant performance, according to News24. This win emphasizes the Springboks' strong position as one of the world's top rugby teams.

#### **[Sinner Dominates Zverev in Paris](https://www.corriere.it/sport/tennis/diretta-live/25_novembre_01/sinner-zverev-semifinale-parigi-diretta-risultato.shtml)**
Jannik Sinner delivered a commanding performance against Alexander Zverev, winning 6-0, 6-1 to advance to the final of the Paris tournament, Corriere della Sera reports. This victory highlights Sinner's exceptional form leading into the final matchup.

#### **[Uzbekistan Makes World Cup History](https://uzreport.news/football/o-zbekiston-ilk-bor-mundialga-chiqdi)**
Uzbekistan has qualified for the FIFA World Cup for the first time in its history, UzReport announces. This achievement marks a significant milestone for Uzbek football and has generated considerable national pride and excitement.

---

### Health & Science

#### **[Kim Jong Un Inspects New Hospital](https://www.nknews.org/2025/10/kim-jong-un-inspects-new-hospital-at-center-of-plans-for-health-care-reform/)**
North Korean leader Kim Jong Un has conducted an inspection of a newly built hospital as part of the country's healthcare reform plans, NK News reports. The facility aims to enhance North Korea's medical infrastructure and improve public health services, reflecting an ongoing focus on healthcare improvements amid broader economic challenges.

#### **[First X-ray Service for TORBA in Vanuatu](https://www.dailypost.vu/news/first-x-ray-service-for-torba/article_2e500028-0de0-51ac-87ea-95244a3dc33d.html)**
TORBA province in Vanuatu has received its first X-ray service, the Vanuatu Daily Post reports. This development significantly improves local healthcare access, enhancing diagnostic capabilities for residents in the region and reflecting ongoing efforts to upgrade medical facilities and services in remote areas.

#### **[Temple Stampede in India](https://nationnews.com/2025/11/01/indian-temple-stampede-kills-nine/)**
A stampede at an Indian temple has resulted in nine fatalities, according to Barbados' The Nation Newspaper. The incident occurred during a religious event that drew a large crowd. Local authorities are investigating the circumstances that led to this tragedy.

#### **[Gadgets Breaking Backs in Tajikistan](https://asiaplustj.info/ru/news/tajikistan/society/20251101/kak-gadzheti-lomayut-vashu-spinu)**
A report from Tajikistan's Asia-Plus highlights how increasing use of electronic gadgets is causing back problems among users. Poor posture while using smartphones and laptops is identified as a significant contributing factor to musculoskeletal issues. Experts recommend ergonomic adjustments and regular breaks to mitigate these health risks.

---

### Business & Economy

#### **[Public-Private Partnership in Comoros](https://alwatwan.net/economie/partenariat-public-priv%C3%A9-i-signature-d%E2%80%99une-convention-entre-le-minist%C3%A8re-des-finances-et-les-op%C3%A9rateurs-%C3%A9conomiques.html)**
Comoros' Ministry of Finance has signed a Public-Private Partnership agreement with economic operators, Al Watwan reports. This collaboration aims to enhance infrastructure development and economic growth, outlining the roles and responsibilities of both public and private entities involved.

#### **[ECCEA Criticism in Mauritius](https://lexpress.mu/s/les-grands-titres-de-lexpress-de-ce-dimanche-2-novembre-2025-551063)**
Roshnee Gunness, the wife of a minister, is at the center of criticism regarding the Early Childhood Care and Education Authority (ECCEA) in Mauritius, L'Express reports. This controversy raises questions about governance and potential conflicts of interest in the educational sector.

#### **[Major Romanian Bank Claims Right to Withdraw Funds](https://adevarul.ro/economie/o-mare-banca-din-romania-isi-da-dreptul-sa-retraga-2483554.html)**
A major Romanian bank has claimed the right to withdraw money from customers' accounts without consent under specific conditions, Adevărul reports. This policy has raised concerns about consumer rights and banking practices in Romania, highlighting tensions between financial institutions and their customers.

#### **[China Might Lift Sanctions on Hanwha Ocean](https://www.yna.co.kr/view/AKR20251102004800071?section=international/all)**
China is reportedly considering lifting sanctions on South Korea's Hanwha Ocean as part of a US-China trade agreement, according to South Korea's Yonhap News Agency. This potential development could signal improved economic relations between China and South Korea, occurring within the context of broader US-China trade negotiations.

---

### Cultural & Social News

#### **[Grand Egyptian Museum Showcases Pharaonic Civilization](https://www.annahar.com/culture/254192/%D8%A7%D9%84%D9%85%D8%AA%D8%AD%D9%81-%D8%A7%D9%84%D9%85%D8%B5%D8%B1%D9%8A-%D8%A7%D9%84%D9%83%D8%A8%D9%8A%D8%B1-%D8%A5%D8%AD%D9%8A%D8%A7-%D8%AD%D8%B6%D8%A7%D8%B1%D8%A9-%D8%A7%D9%84%D9%81%D8%B1%D8%A7%D8%B9%D9%86%D8%A9-%D8%A8%D8%B5%D9%88%D8%B1%D8%A9-%D8%B9%D8%B5%D8%B1%D9%8A%D8%A9)**
The Grand Egyptian Museum presents a stunning display of Pharaonic civilization in a contemporary context, Lebanon's An-Nahar reports. The museum features innovative exhibitions that showcase Egypt's rich archaeological heritage through modern design and interactive experiences. Sayyid Theyazin attended the inauguration representing Oman's Sultan, according to Times of Oman.

#### **[Lord of Miracles Final Procession](https://elcomercio.pe/lima/sucesos/senor-de-los-milagros-en-vivo-procesion-hoy-sexto-y-ultimo-recorrido-del-cristo-moreno-este-sabado-1-de-noviembre-de-2025-rutas-desvios-ultimas-noticias-lbposting-noticia/)**
The final procession of the year honoring the Lord of Miracles has taken place in Peru, El Comercio reports. This significant religious event drew thousands of devotees who expressed their faith through prayers and traditional practices, reinforcing cultural heritage and community solidarity.

#### **[Urn Forest in Izegem, Belgium](https://www.vrt.be/vrtnws/en/2025/10/28/urn-forest-in-izegem-allows-mourners-to-bury-the-deceased-in-nat/)**

In [33]:
prompt = f'''
Please translate this English newsletter into traditional Chinese.
English newsletter: {newsletter_en}
For names and locations, include both Chinese and English, for example:
English version: Trump Threatens Nigeria: Former US President Donald Trump has issued threats of military action against Nigeria, citing concerns over alleged killings of Christians.
Chinese version: 特朗普威脅尼日利亞：前美國總統唐納德·特朗普(Donald Trump)對尼日利亞(Nigeria)發出軍事行動威脅，理由是對基督徒被謀殺的指控表示關切。
Output only the traditional Chinese newsletter
'''

response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [34]:
response.choices[0].message.content

"全球新聞快訊 - 2025年11月2日  \n每日新聞直接來源於當地報紙  \n區域重點  \n非洲 / 中東  \n特朗普威脅尼日利亞：前美國總統唐納德·特朗普（Donald Trump）對尼日利亞（Nigeria）發出軍事行動威脅，理由是對基督徒被謀殺的指控表示關切。  \nM23在剛果民主共和國發起攻勢：M23叛軍於2025年2月在剛果民主共和國南基伍（South Kivu）發起攻擊，持續加劇區域不穩定。  \n巴勒斯坦權力機構在圖巴斯的行動：巴勒斯坦權力機構在約旦河西岸的圖巴斯省（Tubas Governorate）從2024年10月到11月進行了“保護國家行動”。  \n薩法迪呼籲遵守對加薩的停火協定：約旦外長呼籲完全遵守對加薩的停火協議並立即採取人道行動。  \n美洲  \n美國對毒品走私船隻發動空襲：美國在哥倫比亞（Colombia）海岸對涉嫌毒品走私的船隻發動了三次空襲，造成14人死亡。  \n藍鳥隊在世界大賽領先：多倫多藍鳥隊（Toronto Blue Jays）在世界大賽第七場決勝局中以3-1領先。  \n颶風梅利莎造成的毀滅：颶風梅利莎在加勒比地區造成超過50人死亡，牙買加（Jamaica）報告有28人遇難，並造成廣泛的“世界末日”損壞。  \n哥倫比亞卡塔廷波的衝突：國家解放軍在哥倫比亞的卡塔廷波（Catatumbo）地區發起攻擊，加劇了現有衝突。  \n亞洲  \n習近平從亞太經合組織會議回國：中國國家主席習近平在參加亞太經合組織會議後已返回北京。  \n金正恩視察醫院：北韓領導人金正恩（Kim Jong Un）參觀了一所新建醫院，強調在持續的經濟挑戰中推進醫療改革計劃。  \n烏茲別克斯坦晉級世界杯：烏茲別克斯坦首次晉級國際足聯世界杯，這對該國的足球計劃來說是一個重要的里程碑。  \n烏克蘭無人機攻擊俄國油港：烏克蘭軍隊對俄羅斯克拉斯諾達爾邊疆區的一個油港發動無人機攻擊，持續其針對俄國基礎設施的策略。  \n歐洲  \n英國列車 stabbing 事件：在英國劍橋郡的列車上發生集體刺傷事件，造成九人重傷，兩名嫌疑人被逮捕。  \n德國國籍人士在阿爾卑斯山雪崩中喪生：五名德國公民在意大利南蒂羅爾（South Tyrol）的一起雪崩事故中喪生。  \n俄烏戰爭持續：俄烏衝突已進入第1,347天，東部地區持續激烈戰鬥。  \n愛沙尼亞總理批評拉脫維亞：愛沙尼亞總理對拉脫維亞決定退出旨在打擊針對婦女暴力的伊斯坦堡公約表示不滿。  \n大洋洲  \n奧克蘭巴士火災：新西蘭奧克蘭北岸的一輛巴士在撞上立交橋後起火，無人受傷。  \n阿聯酋向颶風重創的加勒比地區提供援助：阿聯酋已向受到梅利莎颶風（Hurricane Melissa）嚴重破壞的加勒比社區提供必需的援助。  \n湯加第十三屆橄欖球準備：湯加隊正在準備迎戰新西蘭基維隊，最近剛以失利告終。  \n詳細新聞報導  \n政治發展  \n特朗普威脅對尼日利亞進行軍事行動  \n前美國總統唐納德·特朗普（Donald Trump）對尼日利亞（Nigeria）的基督徒被謀殺提出了軍事干預威脅。根據尼日利亞《衛報》（The Guardian）和奧地利《克羅寧報》（Kronen Zeitung）的報導，這一具爭議性的聲明引發了對潛在的美國外交政策變化及美尼關係的重大關切。這一威脅引發了關於國際干預和宗教自由問題的廣泛反應。  \n\n巴勒斯坦權力機構 - 約旦河西岸衝突  \n巴勒斯坦權力機構在2024年10月至11月底間在約旦河西岸的圖巴斯省（Tubas Governorate）開展了一項名為“保護國家”的行動。該行動是巴勒斯坦權力機構與約旦河西岸民兵之間衝突的延續，並與持續的中東危機相關。這一發展顯示出在地區緊張局勢下巴勒斯坦內部的複雜動態。  \n\n俄羅斯重申對委內瑞拉的支持  \n根據委內瑞拉《今日報》（El Universal）的報導，俄羅斯重申對委內瑞拉（Venezuela）的強力支持，並呼籲保持拉丁美洲為和平區域。這一聲明是在地區緊張局勢加劇的背景下發出的，強調俄羅斯在美洲的戰略利益，反對外來對委內瑞拉事務的干預。  \n\n愛沙尼亞批評拉脫維亞退出公約  \n愛沙尼亞總理公開批評拉脫維亞決定退出旨在打擊針對婦女暴力的伊斯坦堡公約。這一分歧突顯出波羅的海國家在社會政策問題上的日益分歧，也展示了愛沙尼亞對保護婦女權利的國際框架的承諾。  \n\n武裝衝突與安全  \nM23在剛果民主共和國的攻擊  \nM23叛軍於2025年2月5日至16日在剛果民主共和國南基伍（South Kivu）發起攻勢。這次行動代表了自2022年以來M23叛亂活動的延續，進一步加劇了剛果東部的動盪並威脅到該地區的平民。  \n\n哥倫比亞卡塔廷波的衝突  \n根據報導，國家解放軍（ELN）在哥倫比亞的卡塔廷波地區展開了攻擊。這些衝突發生在北桑坦德（Norte de Santander）地區，儘管近年來對其他武裝團體的和平努力，這顯示出哥倫比亞持續的叛亂活動。  \n\n俄烏戰爭已進入第1347天  \n俄烏戰爭已進入第1,347天，東烏克蘭的激烈戰鬥仍在持續。波蘭報紙《共和國報》（Rzeczpospolita）報導，俄羅斯已加強軍事行動，而烏克蘭軍隊則聲稱在反攻中造成了重大俄國傷亡。兩邊的外交談判仍然停滯不前，雙方都在為進一步升級做準備。  \n\n烏克蘭無人機攻擊俄羅斯油港  \n烏克蘭軍隊對俄羅斯克拉斯諾達爾邊疆區的一個油港發動無人機攻擊，基輔獨立報（The Kyiv Independent）報導。這次襲擊代表了烏克蘭中斷俄羅斯物流和燃料供應基礎設施的策略，對俄國的軍事能力產生影響。  \n\n自然災害與人道危機  \n颶風梅利莎死亡人數上升  \n據《貝里斯新聞》（Breaking Belize News）報導，颶風梅利莎在加勒比海造成超過50人死亡，倖存者形容情況如同“世界末日”。僅在牙買加，死亡人數就達到28人，《格林納達報》（The Gleaner）報導。目前救助工作正在進行中，但由於廣泛的破壞和持續的天氣關切，挑戰依然存在。  \n\n阿聯酋向加勒比社區派發援助  \n阿聯酋已向受到梅利莎颶風打擊的加勒比社區發送重要援助，《國家報》（The National）報導。這一援助旨在支持重建工作並提供必要的補給，以緩解受災地區的人道需求。  \n\n孟加拉國11月份降雨成災  \n《每日之星》（The Daily Star）報導，達卡（Dhaka）和孟加拉國各地正經歷著11月份的強降雨。這場異常降雨導致日常活動受到干擾，人們擔心可能出現洪水。當局正在密切監控形勢，並實施必要的安全措施。  \n\n南蒂羅爾雪崩導致五名德國人遇難  \n根據《明鏡報》（Der Spiegel）的報導，五名德國國籍人士在意大利南蒂羅爾（South Tyrol）的一次雪崩中喪生。事件發生在一個受歡迎的滑雪地區，儘管進行了救援行動，但全部五名遇難者已被確認在現場死亡。這一悲劇突顯了阿爾卑斯地區冬季運動的持續危險。  \n\n犯罪與司法  \n羅浮宮盜竊案更新  \n根據《世界報》（Le Monde）的報導，與巴黎羅浮宮（Louvre）博物館盜竊案有關的兩名嫌疑人被控，而此前被拘留的三人已被釋放。對這起高調藝術盜竊案的調查仍在進行，當局正在尋找更多線索，並試圖追回被盜物品。  \n\n英國列車上發生集體刺傷事件  \n英國劍橋郡的列車上發生了刀具襲擊事件，造成九人重傷。《悉尼晨報》（Sydney Morning Herald）報導，當局對此次事件表示“令人震驚”，緊急服務迅速對現場作出反應。根據多家歐洲媒體，兩名嫌疑人已被逮捕。  \n\n檢察官調查哥斯達黎加OIJ主任  \n哥斯達黎加司法調查組（OIJ）主任蘭達·祖尼加（Randall Zúñiga）因涉嫌性侵犯而受到調查，《國家報》（La Nación）報導。此案引發了對該國重要執法機構領導層的重大關切，且可能對哥斯達黎加的司法系統產生更廣泛的影響。  \n\n波哥大萬聖節派對上學生被殺  \n在哥倫比亞波哥大的洛杉磯大學（University of Los Andes）舉行的萬聖節派對上，一名學生遭到槍擊身亡。《時間報》（El Tiempo）報導，該事件引發了人們對社交活動安全的擔憂，當局正調查這一悲劇事件的相關情況。  \n\n體育與娛樂  \n藍鳥隊在世界大賽第七場領先  \n據CBC新聞報導，多倫多藍鳥隊（Toronto Blue Jays）在世界大賽第七場決勝局中以3-1領先。這場勝者為王的比賽創造了緊張氛圍，藍鳥隊正尋求多年間的首個世界大賽冠軍。  \n\n南非春鹿隊在溫布利大勝日本  \n根據News24報導，南非春鹿隊（Springboks）在溫布利體育場以九次試得分的壓倒性表現戰勝了日本。這場勝利強調了春鹿隊作為世界頂級橄欖球隊之一的強大地位。  \n\n辛納在巴黎賽中壓倒澤維列夫  \nJannik Sinner對Alexander Zverev的比賽表現出色，以6-0, 6-1獲勝，將進入巴黎賽的決賽，根據《晚報》（Corriere della Sera）報導。該勝利突顯了辛納在決賽前出色的狀態。  \n\n烏茲別克斯坦創造世界杯歷史  \n烏茲別克斯坦首次晉級國際足聯世界杯，UzReport報導。這一成就對烏茲別克的足球運動來說是一個重要的里程碑，並引發了國民的自豪感與興奮。  \n\n健康與科學  \n金正恩視察新醫院  \n根據NK News報導，北韓領導人金正恩對一所新建醫院進行了視察，作為該國醫療改革計劃的一部分。該設施旨在提升北韓的醫療基礎設施和改善公共健康服務，反映了在更廣泛經濟挑戰下的醫療改善努力。  \n\n瓦努阿圖TORBA省首次提供X光服務  \n根據《瓦努阿圖每日郵報》（Vanuatu Daily Post）報導，TORBA省首次提供X光服務。這一發展顯著改善了當地的醫療保健，增強了該地區居民的診斷能力，反映出不斷提高偏遠地區醫療設施和服務的努力。  \n\n印度廟內踩踏事件  \n根據巴巴多斯《國家報》（The Nation Newspaper）的報導，印度一座廟宇發生踩踏事件，造成九人遇難。事故發生在一個吸引大量人群的宗教活動中。當地當局正在調查導致這場悲劇的情況。  \n\n吉爾吉斯斯坦電子產品造成脊背問題  \n根據塔吉克斯坦《亞洲通訊》（Asia-Plus）的報導，越來越多的電子設備使用引發了用戶的背部問題。專家指出，使用智能手機和筆記本電腦時的不良姿勢是造成肌肉骨骼問題的重要原因。專家建議進行符合人體工程學的調整及定期休息以減輕這些健康風險。  \n\n商業與經濟  \n科摩羅公共私營合作  \n根據《阿爾瓦坦報》（Al Watwan）的報導，科摩羅財政部與經濟運營商簽署了公共私營合作協議。此次合作旨在促進基礎設施發展和經濟增長，並明確參與公共和私營部門的角色和責任。  \n\n毛里求斯ECCEA的批評  \n根據《快報》（L'Express）的報導，總理之妻羅什妮·甘內斯（Roshnee Gunness）成為毛里求斯早期兒童護理與教育管理局（ECCEA）爭議的中心。此次爭議引發了對教育部門治理和潛在利益衝突的質疑。  \n\n主要羅馬尼亞銀行聲稱有權無需同意提取資金  \n根據《真實報》（Adevărul）的報導，羅馬尼亞一家主要銀行聲稱在特定條件下有權無需客戶同意提取資金。此政策引發了對消費者權益和銀行實踐的擔憂，突出了金融機構與客戶之間的緊張關係。  \n\n中國可能解除對漢華海洋的制裁  \n根據韓國聯合通訊社（Yonhap News Agency）的報導，中國可能會考慮解除對韓國漢華海洋（Hanwha Ocean）公司的制裁，作為美中貿易協議的一部分。這一潛在發展可能預示著中韓之間的經濟關係改善，正值更廣泛的美中貿易談判背景下。  \n\n文化與社會新聞  \n大埃及博物館展示法老文明  \n根據黎巴嫩《安哈爾報》（An-Nahar）的報導，大埃及博物館展示了法老文明的壯觀展示，融合了現代設計和互動體驗，展示了埃及豐富的考古遺產。阿曼蘇丹的代表賽義德·泰阿辛（Sayyid Theyazin）出席了啟動儀式，據《阿曼時報》（Times of Oman）報導。  \n\n奇蹟之主最終遊行  \n根據《商業報》（El Comercio）的報導，為榮耀奇蹟之主的年度最終遊行已在秘魯舉行。這一重要宗教事件吸引了數千名信徒，他們通過祈禱和傳統慶祝方式表達信仰，強化文化遺產和社區凝聚力。  \n\n比利時伊澤根姆樹葬森林  \n根據VRT NWS的報導，比利時伊澤根姆（Izegem）推出了一個“骨灰樹林”，允許哀悼者在自然環境中安葬親人的骨灰。這一舉措提供了傳統埋葬方式的生態替代方案，鼓勵在哀悼過程中與自然建立更深的聯結。  \n\n馬普托慶祝138周年  \n根據《新聞報》（Noticias）報導，拉薩克·曼吉克（Rasaque Manhique）正式啟動慶祝馬普托（Maputo）——莫桑比克首都——138周年的活動。慶祝活動旨在突顯該市豐富的歷史和文化遺產，並計劃在周年慶期間舉辦多項活動。  \n\n科技與創新  \n波塞冬號的跨海能力  \n根據保加利亞媒體dnes.bg的報導，“波塞冬”（Poseidon）號船隻據報導擁有無範圍限制的跨海航行能力。這一技術進步使其可以在無需加油或支持的情況下執行長時間的海上任務，標誌著海軍工程和操作效率的重大突破。  \n\nZ世代的就業革命  \n根據印尼《印尼日報》（Kompas）的報導，Z世代正在重新塑造就業環境，他們偏好靈活的工作安排和遠程機會。雇主正在迎合這些需求，提供多樣化的福利，包括心理健康支持和職業發展。科技和自動化對新職業領域產生影響，導致入門職位所需技能的轉變。  \n\n吉爾吉斯斯坦能源公司實施電力限制  \n根據24.kg的報導，吉爾吉斯斯坦一家能源公司實施限制電力容量，以防止變電站可能發生的過載。這一措施旨在確保能源供應的穩定性和可靠性，儘管客戶可能會因為這種預防策略而經歷電力使用上的限制。  \n\n泰國總理應對網絡犯罪  \n根據《曼谷郵報》（Bangkok Post）的報導，泰國總理強調政府對抗網絡犯罪的承諾，並指出其日益對國家安全構成威脅。新的舉措和更嚴格的法律正在被提議，以加強網絡安全措施和懲罰違法者，並呼籲政府機構、私營部門和國際夥伴之間加強合作。  \n\n隨著全球事件的不斷發展，本綜合摘要提供了對當今塑造我們世界的主要發展的深入了解。從政治緊張到科技進步，自然災害到文化慶祝，全球社會的相互聯繫在來自世界各地的多元新聞標題中依然顯而易見。"

In [ ]:
# websites = list(df[df["Link"].isna() & df["Headline"].notna()]["Website"])
# headlines = list(df[df["Link"].isna() & df["Headline"].notna()]["Headline"])
# combined = list(zip(websites, headlines))
# combined
websites = list(df[df["Headline"].isna()]["Website"])
websites

In [ ]:
# for website, headline in combined:
for website in websites:

    print(website)
    
    try:
        html_dict = extract_html.get_raw_html(website)
        html_string = html_dict["html"]
        clean_text = remove_html_tags(html_string)

        if len(html_string) > 200000:
            html_string_input = clean_text
        else:
            html_string_input = html_string

        prompt = f'''
        You are good at reading html text, visualize the content, and identify the headline of the day.
        Given this HTML text from a news website: {html_string_input}

        CRITICAL REQUIREMENTS:
        1. Identify the main headline of the day
        2. ALWAYS translate to English if the headline is in any other language
        3. Output ONLY the English headline text, nothing else
        4. Do not include any non-English words or phrases
        5. Ensure the headline is in proper English grammar and spelling
        6. If the headline contains any non-English characters or words, translate them to English

        IMPORTANT: The output must be 100% in English. If you cannot translate a headline to English, output "No headline found".
        '''

        response = await client.chat.completions.create(
#             model="anthropic/claude-haiku-4.5",
            model="openai/gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
        )

        headline = response.choices[0].message.content.strip()
        print(headline)

        soup = BeautifulSoup(html_string, "html.parser")

        # Extract all links
        links = {a.get_text(): a for a in soup.find_all('a')}

        # Get text without HTML tags
        # text = soup.get_text()
        links_on_page = ""

        # Append links to the text
        for link_text, url in links.items():
            links_on_page += f" [{link_text}]({url})"

        prompt = f'''
        Given this identified headline on a news website: "{headline}"
        Note that the headline is being translated into English if the original text is non-English.
        Please check if the link to that headline is in {links_on_page[:150000]}
        If so, please output only the link. 
        Note that sometime only the relative url is included. If so, you need to output the absolute url with the root website {website}.
        If no link is founded, just output 'N/A'
        Do not output anything else other than the link
        Do not output any html tags e.g., '<a href=', '</a>'
        '''

        response = await client.chat.completions.create(
            model="openai/gpt-4o-mini",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        link = response.choices[0].message.content
        print(link)

        html_dict = extract_html.get_raw_html(link)
        html_string = html_dict["html"]
        clean_text = remove_html_tags(html_string)

        prompt = f'''
        You are a capable journalist. This is the headline of today: {clean_text}
        Please summarize in 2-3 English bullets to capture the key informaiton. Each bullet should be very concise.
        You may assume your readers know nothing about the country's news and politics
        The source may not be in English. But make sure the summary is in English
        '''

        response = await client.chat.completions.create(
            model="openai\gpt-4o-mini",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        summary = response.choices[0].message.content
        print(summary)
        print("\n")
    
    except:
        continue

In [36]:
# Load a Markdown file
def load_markdown_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
    return content

# Example usage
markdown_content = load_markdown_file('newsletter_20251103_103157.md')

In [37]:
display(Markdown(markdown_content))

# Headlines around the globe - Nov 03, 2025
Daily news sourced directly from local newspapers

## Regional Highlights

### Africa / Middle East
- **[MACC to Call Up Whistleblower Over Corruption Video](https://thesun.my/malaysia-news/macc-to-call-up-whistleblower-over-corruption-video-JN13789437)**: The Malaysian Anti-Corruption Commission will interview a whistleblower regarding a video linking a Sabah leader to corruption allegations. (The Sun, Malaysia)
- **[10 JAMB Staff Face Prosecution Over Corruption](https://guardian.ng/news/nigeria/national/10-jamb-staff-face-prosecution-over-corruption-allegations/)**: More than 10 staff members of Nigeria's Joint Admissions and Matriculation Board are being prosecuted for corruption allegations. (The Guardian, Nigeria)
- **[Houthi Forces Block Vital Goods into Taiz](http://www.yemenpost.net/Detail123456789.aspx?ID=3&SubID=8397&MainCat=3)**: Human Rights Watch reports that Houthi forces are obstructing essential supplies from reaching Taiz, worsening the humanitarian crisis in Yemen. (Yemen Post)
- **[President Isaias Attends Inauguration of Egypt's Grand Museum](https://shabait.com/2025/11/02/president-isaias-attends-inauguration-of-egypts-grand-museum/)**: Eritrea's President Isaias participated in the opening ceremony of Egypt's Grand Museum, highlighting cultural cooperation in the region. (Shabait)
- **[Xi Extends Congratulations on Grand Egyptian Museum Opening](https://english.news.cn/20251102/120c706554da4e2483be0adc5df4e1a4/c.html)**: Chinese President Xi Jinping congratulated Egyptian President el-Sisi on the opening of the Grand Egyptian Museum near the Giza Pyramids. (Xinhua)

### Americas
- **[Early Voting Ends With Over 735,000 Ballots Cast in NYC Mayor's Race](https://www.nytimes.com/live/2025/11/02/nyregion/nyc-mayor-election-news)**: New York City's mayoral election has seen significant turnout during early voting, indicating high public interest. (The New York Times, USA)
- **[Trump to Host U.S.-Central Asia Summit](http://qazinform.com/news/foreign-media-on-kazakhstan-trump-to-host-us-central-asia-summit-on-november-6-kazakhstan-discusses-exporting-uranium-to-finnish-nuclear-plants-aa8a29)**: Former President Trump is set to host a summit with Central Asian leaders on November 6, focused on strengthening regional ties. (Kazinform, Kazakhstan)
- **[Masked Individuals Storm Government Palace in Mexico](https://www.eluniversal.com.mx/estados/en-marcha-por-carlos-manzo-grupo-de-embozados-irrumpe-en-palacio-de-gobierno-en-morelia-lanzan-muebles-por-las-ventanas/)**: A group of protesters stormed the Government Palace in Mexico, throwing furniture from windows during unrest related to the assassination of a seventh mayor in Michoacán. (El Universal, Mexico)
- **[Dodgers Win Back-to-Back Championship, Yamamoto Earns World Series MVP](https://news.web.nhk/newsweb/na/na-k10014965451000)**: The Los Angeles Dodgers have secured consecutive World Series championships with Japanese pitcher Yoshinobu Yamamoto named MVP. (NHK, Japan)
- **[Trump Selects Susie Wiles as Chief of Staff](https://almomento.net/trump-elige-a-susie-wiles-jefa-gabinete-primera-mujer-en-cargo/)**: Donald Trump has appointed Susie Wiles, who previously managed his 2016 Florida campaign, as White House Chief of Staff. (ALMOMENTO.NET, Dominican Republic)

### Asia
- **[Indian Women Lift Historic Maiden ODI World Title](https://www.thehindu.com/sport/cricket/womens-odi-world-cup-cricket-india-defeat-south-africa-lift-maiden-world-cup/article70233864.ece)**: India's women's cricket team has won their first-ever ODI World Cup by defeating South Africa in the final. (The Hindu, India)
- **[Uzbekistan Qualifies for World Cup for First Time](https://uzreport.news/football/o-zbekiston-ilk-bor-mundialga-chiqdi)**: Uzbekistan has made history by qualifying for the FIFA World Cup for the first time. (UzReport, Uzbekistan)
- **[Russian Oil Tanker on Fire After Ukrainian Drone Strike](https://kyivindependent.com/ukraine-war-latest-russian-oil-tanker-on-fire-after-strike-by-ukrainian-drones-in-krasnodar-krai-source-says/)**: A Russian oil tanker is reportedly ablaze following a strike by Ukrainian drones in Krasnodar Krai. (Kyiv Independent, Ukraine)
- **[Kim Jong Un Inspects New Hospital](https://www.nknews.org/2025/10/kim-jong-un-inspects-new-hospital-at-center-of-plans-for-health-care-reform/)**: North Korean leader Kim Jong Un has visited a newly built hospital that's central to the country's healthcare reform plans. (NK News)
- **[6.3 Magnitude Earthquake Strikes Afghanistan](https://www.nrk.no/nyheter/afghanistan_-jordskjelv-med-6_3-i-styrke-1.17636653)**: A powerful earthquake has hit Afghanistan, resulting in at least seven fatalities with rescue efforts underway. (NRK, Norway)

### Europe
- **[Protests Erupt Outside Serbia's Parliament](https://www.panorama.com.al/trazira-perpara-kuvendit-te-serbise-protestuesit-hedhin-flakadane-dhe-molotove-reagon-vucic-u-bej-thirrje-per-paqe/)**: Demonstrators threw torches and Molotov cocktails outside Serbia's parliament, with President Vučić calling for peace amid the unrest. (Gazeta Panorama, Albania)
- **[New Violence in Serbia – Vučić Promises New Elections](https://www.svt.se/nyheter/utrikes/nya-valdsamheter-i-serbien-vucic-lovar-nyval)**: President Aleksandar Vučić has announced plans for new elections in response to renewed violence across Serbia. (SVT, Sweden)
- **[37 People Arrested After Riot Near Serbian Assembly](https://www.blic.rs/vesti/politika/oglasio-se-mup-uhapseno-37-lica-nakon-nereda-kod-skupstine-srbije/689609c)**: The Serbian Interior Ministry announced that 37 individuals were arrested for disturbing public order during riots near the assembly. (Blic, Serbia)
- **[NATO Task Force Clears Historical Sea Mines in Gulf of Finland](https://yle.fi/a/74-20191775)**: NATO forces have successfully cleared historical sea mines in the Gulf of Finland, enhancing maritime safety in the region. (YLE, Finland)
- **[Arrest After Man Dies Following Dublin Assault](https://www.rte.ie/news/2025/1102/1541720-tyrellstown-dublin/)**: Irish authorities have made an arrest after a man in his 20s died following an assault in Dublin. (RTÉ News, Ireland)

### Oceania
- **[Ley's Leadership in Peril as Senior Liberals Move to Dump Net Zero](https://www.smh.com.au/politics/federal/ley-s-top-lieutenants-lean-towards-scrapping-net-zero-as-leadership-in-peril-20251103-p5n78b.html)**: Senior Liberal Party members are pushing to abandon the net zero emissions policy, threatening the leadership position of the party leader. (The Sydney Morning Herald, Australia)
- **[First X-ray Service for TORBA](https://www.dailypost.vu/news/first-x-ray-service-for-torba/article_2e500028-0de0-51ac-87ea-95244a3dc33d.html)**: The TORBA region in Vanuatu has launched its first-ever X-ray service, significantly improving local healthcare capabilities. (Vanuatu Daily Post)
- **[Floats Parade Brings Festivity to Nuku'alofa](https://matangitonga.to/2025/11/03/floats-parade-brings-festivity-nukualofa)**: A vibrant parade in Nuku'alofa, Tonga, showcased elaborate displays and brought together local communities in celebration. (Matangi Tonga)
- **[Deacon's Primary to Reopen After Upgrades](https://nationnews.com/2025/11/02/deacon-primary-to-reopen-monday-following-upgrade-works/)**: Deacon's Primary School in Barbados will reopen on Monday following the completion of facility improvements. (The Nation Newspaper)
- **[Halt the Parades for Now, Says Police](https://www.samoaobserver.ws/category/samoa/116728)**: Samoan police have announced a temporary suspension of parades due to safety concerns. (Samoa Observer)

## Detailed News Coverage

### Political Developments

**[Israel Receives Remains of Three Hostages from Gaza](https://www.lemonde.fr/en/international/article/2025/11/02/israel-receives-the-remains-of-three-hostages-from-gaza-as-fragile-ceasefire-holds_6747028_4.html)**: Israel has received the remains of three hostages from Gaza amid a fragile ceasefire. According to former President Trump, one of the bodies released is that of American-Israeli IDF soldier Omer Neutra. The transfer occurs as part of ongoing negotiations between the parties, with the ceasefire remaining tenuous. (Le Monde, France)

**[Trump: Putin Is a Strong Leader Whom One Cannot Play With](https://ria.ru)**: Former U.S. President Trump has characterized Russian President Putin as a strong leader who cannot be manipulated, signaling potential shifts in diplomatic approaches should Trump return to office. (RIA Novosti, Russia)

**[Paul Biya Re-elected in Cameroon Presidential Election](https://www.cameroon-tribune.cm/article.html/73520/fr.html/presidentielle-2025-paul-biya-reelu)**: Paul Biya has secured another term as President of Cameroon following the 2025 presidential election, extending his decades-long rule over the country. (Cameroon Tribune)

**[Nigerian Urges Trump Meeting After Military Action Threat](https://guardian.ng/news/nigeria/national/nigeria-urges-trump-meeting-after-military-action-threat/)**: Nigeria is seeking diplomatic engagement with former President Trump following his threat of military action regarding regional issues, highlighting tensions in U.S.-Nigeria relations. (The Guardian Nigeria)

**[Former MP Selmon Walters to Be Laid to Rest Today](https://www.searchlight.vc/breaking-news/2025/11/01/former-mp-selmon-walters-laid-rest-today/)**: The funeral for former Member of Parliament Selmon Walters is taking place today in Saint Vincent and the Grenadines, drawing political colleagues and community members. (Searchlight)

### Conflicts and Tensions

**[Palestinians Face Hunger, Cold and Loss Amid Ongoing Israeli Siege](https://www.aljazeera.com/news/2025/11/2/palestinians-face-hunger-cold-and-loss-amid-ongoing-israeli-siege-on-gaza)**: Gaza residents continue to experience severe shortages of food and essential supplies due to the ongoing Israeli siege, with winter conditions exacerbating the humanitarian crisis. (Al Jazeera, Qatar)

**[Gaza Children Back to School](https://kuwaittimes.com/article/35248/top-stories/gaza-children-back-to-school/)**: Children in Gaza are returning to classrooms after disruptions from recent conflicts, with schools implementing safety measures and mental health support to restore educational normalcy. (Kuwait Times)

**[Israeli Media: Israel Is Preparing to Open a New Front in Iraq](https://www.entekhab.ir/fa/news/893035/رسانه‌-عبری-اسرائیل-در-تدارک-گشودن-جبهه‌ای-جدید-در-عراق-است)**: Israeli media reports suggest that Israel is planning military operations in Iraq, potentially escalating regional tensions in the Middle East. (Entekhab, Iran)

**[Russian Forces Bombard Kherson Region, War in Ukraine Day 1348](https://www.zdg.md/stiri/live-text-fortele-ruse-bombardeaza-regiunea-herson-mai-multe-persoane-sunt-ranite-razboi-in-ucraina-ziua-1348/)**: Russian forces continue to target Ukraine's Kherson region, resulting in multiple injuries as the conflict enters its 1,348th day. (Ziarul de Gardă, Republic of Moldova)

**[Turkey's Foreign Minister: Ankara Expects PKK Activities in Iraq to Cease](https://www.dnes.bg/a/2-svyat/698439-turskiyat-vanshen-ministar-ankara-ochakva-deynostite-na-pkk-v-irak-da-badat-prekrateni)**: Turkey's Foreign Minister has stated that Ankara anticipates an end to PKK activities in Iraq as part of ongoing military and diplomatic efforts in the region. (dnes.bg, Bulgaria)

### Economic News

**[Credit Cards in Costa Rica: One Bank Controls Nearly Half of Business](https://www.nacion.com/economia/tarjetas-de-credito-en-costa-rica-un-banco/GRGYTDUJTBHN7DWOZGLFM6XHGU/story/)**: A single bank dominates Costa Rica's credit card market with nearly 50% market share, raising concerns about competition and consumer choice in the financial sector. (La Nación, Costa Rica)

**[Inflation Falls to 2% in October in Belgium](https://www.vrt.be/vrtnws/en/2025/10/30/inflation-falls-to-2-per-cent-in-october-what-became-cheaper-w/)**: Belgium's inflation rate decreased to 2% in October, with lower prices for food and energy offset by rising costs in housing and transportation, signaling a mixed economic outlook. (VRT NWS, Belgium)

**[GIPF Faces N$1 Billion Loss After Underperforming Investments](https://www.namibian.com.na/gipf-faces-n1-billion-loss-after-underperforming-offshore-investments-in-sa/)**: Namibia's Government Institutions Pension Fund is projecting losses of N$1 billion due to poor performance of its South African offshore investments. (The Namibian)

**[The Municipalities Submit 550 Licenses to Urban Planning](https://www.bondia.ad/societat/els-comuns-entren-550-llicencies-a-urbanisme-71-mes-que-el-2023)**: Andorra's municipalities have submitted 550 licenses to Urban Planning, representing an increase of 71 licenses compared to 2023 and indicating growth in urban development. (Bondia.ad)

**[Ethiopia's Economic Growth Creates Opportunities for Manufacturing](https://www.ena.et/web/eng/w/eng_7634853)**: Ethiopia's Ministry highlights strong economic growth that's opening significant opportunities in the manufacturing sector, aiming to enhance industrialization and attract investment. (Ethiopian News Agency)

### Sports News

**[Coquimbo Unido Becomes First Champion of Chilean Football](https://www.emol.com/noticias/Deportes/2025/11/02/1182103/coquimbo-unido-campeon-futbol-chileno.html)**: Coquimbo Unido has made history by becoming the first champion of Chilean football, marking a significant milestone for the club. (emol.com, Chile)

**[Sinner Beats Auger-Aliassime in Tennis Final](https://www.corriere.it/sport/tennis/diretta-live/25_novembre_02/sinner-auger-aliassime-finale-parigi-diretta.shtml)**: Jannik Sinner defeated Felix Auger-Aliassime in a thrilling tennis match, with his powerful backhand down the line proving decisive. (Corriere della Sera, Italy)

**[Football Ligue 1: Lupopo Defeats Mazembe, Vita Club Held by Maniema](https://radiookapi.net/2025/11/02/actualite/sport/football-ligue-1-lupopo-renverse-mazembe-vita-club-freine-par-maniema)**: In DR Congo's Ligue 1, Lupopo secured a comeback victory against Mazembe, while Vita Club was held to a draw by Maniema Union. (Radio Okapi, Democratic Republic of the Congo)

**[Oklahoma Remains NBA Benchmark, Hartenstein Shines](https://www.spiegel.de/sport/basketball/nba-oklahoma-city-bleibt-ungeschlagen-und-isaiah-hartenstein-brilliert-a-957ba71d-ff31-4dba-b3da-d62bec074000)**: The Oklahoma City Thunder continues its strong start to the NBA season, while German player Isaiah Hartenstein delivers impressive performances. (Der Spiegel, Germany)

**[Germany U-17 Reaches World Cup Final After Victory Over Qatar](https://www.gabonews.ga/sports/handball/39/lallemagne-u-17-en-finale-mondiale-apres-une-victoire-ecrasante-sur-le-qatar/)**: Germany's Under-17 team has secured a place in the World Cup final following a dominant win against Qatar. (Gabonews, Gabon)

### Health & Science

**[Justice Sector Commits to Digital Case Management in Bhutan](https://www.bbs.bt/235112/)**: Key institutions in Bhutan's justice sector are implementing new digital case management systems to enhance efficiency and accessibility within judicial processes. (Bhutan Broadcasting Service)

**[Unseasonal Rains Devastate Paddy Harvest Across Nepal](https://kathmandupost.com/national/2025/11/02/unseasonal-rains-devastate-paddy-harvest-across-nepal)**: Unexpected rainfall in Nepal has severely damaged paddy harvests, threatening food security as farmers report significant crop losses. (The Kathmandu Post)

**[Jamaica Braces for Food Shortages After Hurricane Melissa](https://www.breakingbelizenews.com/2025/11/02/jamaica-braces-for-egg-and-food-shortages-after-hurricane-melissa/)**: Jamaica is preparing for potential egg and food shortages following the impact of Hurricane Melissa, which has disrupted supply chains and agricultural production. (Breaking Belize News)

**[Menopause: A Silent and Transformative Journey](https://www.anacao.cv/noticia/2025/11/03/menopausa-uma-travessia-silenciosa-e-transformadora/)**: A feature in Cabo Verde's A Nação newspaper highlights the often-overlooked impacts of menopause on women's physical and emotional health, emphasizing the need for greater awareness and support. (A Nação)

**[Medics Suspend Strike at Central Hospital of Nampula](https://www.jornalnoticias.co.mz/2025/11/02/medicos-decidem-suspender-greve-no-hospital-central-de-nampula/)**: Medical staff at Mozambique's Central Hospital of Nampula have decided to suspend their strike action following negotiations addressing their concerns. (Noticias)

### Society & Culture

**[From Hardships to Hope: Daikundi Woman Leads Change](https://pajhwok.com/2025/11/02/from-hardships-to-hope-daikundi-woman-leads-change/)**: A determined woman from Afghanistan's Daikundi province is transforming her community despite significant challenges, leading initiatives to improve living conditions. (Pajhwok Afghan News)

**[That Luang Festival Kicks Off in Laos](https://vientianetimes.org.la/freefreenews/freecontent_212_That_y25.php)**: The That Luang festival has begun in Laos, celebrating cultural heritage and religious traditions while uniting participants from diverse backgrounds. (Vientiane Times)

**[Blood Feud in Vorizia: Scenes of Ancient Tragedy](https://www.kathimerini.gr/society/563899600/vorizia-skines-archaias-tragodias-meta-to-foniko-se-ypsisti-epifylaki-i-el-as/)**: A murder in Vorizia, Greece, has triggered a violent blood feud reminiscent of ancient tragedies, with police on high alert to prevent further violence. (Kathimerini, Greece)

**[A Man Earns More – a Norm. A Woman Earns More – a Problem?](https://www.delfi.lv/life/56017194/attiecibas/120093401/virietis-pelna-vairak-norma-sieviete-pelna-vairak-problema)**: A Latvian article examines societal double standards where men's higher earnings are accepted while women's financial success often faces scrutiny and criticism. (Delfi, Latvia)

**[Why an Italian City Named Streets After Luxembourg Cities](https://www.wort.lu/panorama/warum-eine-stadt-in-italien-strassen-nach-luxemburger-staedten-benannt-hat/101839410.html)**: A city in Italy has dedicated street names to Luxembourg cities to strengthen cultural ties and international friendship. (Luxemburger Wort, Luxembourg)

### Crime & Justice

**[MACC to Call Up Whistleblower Over Corruption Video](https://thesun.my/malaysia-news/macc-to-call-up-whistleblower-over-corruption-video-JN13789437)**: The Malaysian Anti-Corruption Commission (MACC) will interview a whistleblower regarding a video linking a Sabah leader to corruption allegations. Chief Commissioner Tan Sri Azam Baki stated the investigation would proceed based on evidence from the whistleblower's statement. (The Sun, Malaysia)

**[Vehicle Licence Bribery: MACC Detains Officers](https://thesun.my/malaysia-news/vehicle-licence-bribery-macc-detains-officers-ex-staff-of-govt-agency-GH13507221)**: Two staff members and a former employee of a Malaysian ministry's agency have been detained by the MACC for alleged involvement in corrupt practices related to vehicle licensing. (The Sun, Malaysia)

**[Bushiri Secures Victory Against Extradition](https://malawi24.com/2025/10/31/bushiri-secures-victory-against-extradition-high-court-declares-it-unlawful-and-unconstitutional/)**: Malawi's High Court has ruled that the extradition of Shepherd Bushiri is unlawful and unconstitutional, securing a legal victory for Bushiri who faces charges in South Africa. (Malawi24)

**[Police in Big Drug Bust at Foulis, Guyana](https://www.stabroeknews.com/2025/11/02/news/guyana/police-in-big-drug-bust-at-foulis/)**: Guyanese authorities have conducted a significant drug bust in Foulis, making multiple arrests as part of a broader crackdown on drug-related activities. (Stabroek News)


In [40]:
import markdown
html_content = markdown.markdown(markdown_content)

In [41]:
html_content

'<h1>Headlines around the globe - Nov 03, 2025</h1>\n<p>Daily news sourced directly from local newspapers</p>\n<h2>Regional Highlights</h2>\n<h3>Africa / Middle East</h3>\n<ul>\n<li><strong><a href="https://thesun.my/malaysia-news/macc-to-call-up-whistleblower-over-corruption-video-JN13789437">MACC to Call Up Whistleblower Over Corruption Video</a></strong>: The Malaysian Anti-Corruption Commission will interview a whistleblower regarding a video linking a Sabah leader to corruption allegations. (The Sun, Malaysia)</li>\n<li><strong><a href="https://guardian.ng/news/nigeria/national/10-jamb-staff-face-prosecution-over-corruption-allegations/">10 JAMB Staff Face Prosecution Over Corruption</a></strong>: More than 10 staff members of Nigeria\'s Joint Admissions and Matriculation Board are being prosecuted for corruption allegations. (The Guardian, Nigeria)</li>\n<li><strong><a href="http://www.yemenpost.net/Detail123456789.aspx?ID=3&amp;SubID=8397&amp;MainCat=3">Houthi Forces Block Vital Goods into Taiz</a></strong>: Human Rights Watch reports that Houthi forces are obstructing essential supplies from reaching Taiz, worsening the humanitarian crisis in Yemen. (Yemen Post)</li>\n<li><strong><a href="https://shabait.com/2025/11/02/president-isaias-attends-inauguration-of-egypts-grand-museum/">President Isaias Attends Inauguration of Egypt\'s Grand Museum</a></strong>: Eritrea\'s President Isaias participated in the opening ceremony of Egypt\'s Grand Museum, highlighting cultural cooperation in the region. (Shabait)</li>\n<li><strong><a href="https://english.news.cn/20251102/120c706554da4e2483be0adc5df4e1a4/c.html">Xi Extends Congratulations on Grand Egyptian Museum Opening</a></strong>: Chinese President Xi Jinping congratulated Egyptian President el-Sisi on the opening of the Grand Egyptian Museum near the Giza Pyramids. (Xinhua)</li>\n</ul>\n<h3>Americas</h3>\n<ul>\n<li><strong><a href="https://www.nytimes.com/live/2025/11/02/nyregion/nyc-mayor-election-news">Early Voting Ends With Over 735,000 Ballots Cast in NYC Mayor\'s Race</a></strong>: New York City\'s mayoral election has seen significant turnout during early voting, indicating high public interest. (The New York Times, USA)</li>\n<li><strong><a href="http://qazinform.com/news/foreign-media-on-kazakhstan-trump-to-host-us-central-asia-summit-on-november-6-kazakhstan-discusses-exporting-uranium-to-finnish-nuclear-plants-aa8a29">Trump to Host U.S.-Central Asia Summit</a></strong>: Former President Trump is set to host a summit with Central Asian leaders on November 6, focused on strengthening regional ties. (Kazinform, Kazakhstan)</li>\n<li><strong><a href="https://www.eluniversal.com.mx/estados/en-marcha-por-carlos-manzo-grupo-de-embozados-irrumpe-en-palacio-de-gobierno-en-morelia-lanzan-muebles-por-las-ventanas/">Masked Individuals Storm Government Palace in Mexico</a></strong>: A group of protesters stormed the Government Palace in Mexico, throwing furniture from windows during unrest related to the assassination of a seventh mayor in Michoacán. (El Universal, Mexico)</li>\n<li><strong><a href="https://news.web.nhk/newsweb/na/na-k10014965451000">Dodgers Win Back-to-Back Championship, Yamamoto Earns World Series MVP</a></strong>: The Los Angeles Dodgers have secured consecutive World Series championships with Japanese pitcher Yoshinobu Yamamoto named MVP. (NHK, Japan)</li>\n<li><strong><a href="https://almomento.net/trump-elige-a-susie-wiles-jefa-gabinete-primera-mujer-en-cargo/">Trump Selects Susie Wiles as Chief of Staff</a></strong>: Donald Trump has appointed Susie Wiles, who previously managed his 2016 Florida campaign, as White House Chief of Staff. (ALMOMENTO.NET, Dominican Republic)</li>\n</ul>\n<h3>Asia</h3>\n<ul>\n<li><strong><a href="https://www.thehindu.com/sport/cricket/womens-odi-world-cup-cricket-india-defeat-south-africa-lift-maiden-world-cup/article70233864.ece">Indian Women Lift Historic Maiden ODI World Title</a></strong>: India\'s women\'s cricket team has won their first-ever ODI World Cup by defeating South Africa in the final. (The Hindu, India)</li>\n<li><strong><a href="https://uzreport.news/football/o-zbekiston-ilk-bor-mundialga-chiqdi">Uzbekistan Qualifies for World Cup for First Time</a></strong>: Uzbekistan has made history by qualifying for the FIFA World Cup for the first time. (UzReport, Uzbekistan)</li>\n<li><strong><a href="https://kyivindependent.com/ukraine-war-latest-russian-oil-tanker-on-fire-after-strike-by-ukrainian-drones-in-krasnodar-krai-source-says/">Russian Oil Tanker on Fire After Ukrainian Drone Strike</a></strong>: A Russian oil tanker is reportedly ablaze following a strike by Ukrainian drones in Krasnodar Krai. (Kyiv Independent, Ukraine)</li>\n<li><strong><a href="https://www.nknews.org/2025/10/kim-jong-un-inspects-new-hospital-at-center-of-plans-for-health-care-reform/">Kim Jong Un Inspects New Hospital</a></strong>: North Korean leader Kim Jong Un has visited a newly built hospital that\'s central to the country\'s healthcare reform plans. (NK News)</li>\n<li><strong><a href="https://www.nrk.no/nyheter/afghanistan_-jordskjelv-med-6_3-i-styrke-1.17636653">6.3 Magnitude Earthquake Strikes Afghanistan</a></strong>: A powerful earthquake has hit Afghanistan, resulting in at least seven fatalities with rescue efforts underway. (NRK, Norway)</li>\n</ul>\n<h3>Europe</h3>\n<ul>\n<li><strong><a href="https://www.panorama.com.al/trazira-perpara-kuvendit-te-serbise-protestuesit-hedhin-flakadane-dhe-molotove-reagon-vucic-u-bej-thirrje-per-paqe/">Protests Erupt Outside Serbia\'s Parliament</a></strong>: Demonstrators threw torches and Molotov cocktails outside Serbia\'s parliament, with President Vučić calling for peace amid the unrest. (Gazeta Panorama, Albania)</li>\n<li><strong><a href="https://www.svt.se/nyheter/utrikes/nya-valdsamheter-i-serbien-vucic-lovar-nyval">New Violence in Serbia – Vučić Promises New Elections</a></strong>: President Aleksandar Vučić has announced plans for new elections in response to renewed violence across Serbia. (SVT, Sweden)</li>\n<li><strong><a href="https://www.blic.rs/vesti/politika/oglasio-se-mup-uhapseno-37-lica-nakon-nereda-kod-skupstine-srbije/689609c">37 People Arrested After Riot Near Serbian Assembly</a></strong>: The Serbian Interior Ministry announced that 37 individuals were arrested for disturbing public order during riots near the assembly. (Blic, Serbia)</li>\n<li><strong><a href="https://yle.fi/a/74-20191775">NATO Task Force Clears Historical Sea Mines in Gulf of Finland</a></strong>: NATO forces have successfully cleared historical sea mines in the Gulf of Finland, enhancing maritime safety in the region. (YLE, Finland)</li>\n<li><strong><a href="https://www.rte.ie/news/2025/1102/1541720-tyrellstown-dublin/">Arrest After Man Dies Following Dublin Assault</a></strong>: Irish authorities have made an arrest after a man in his 20s died following an assault in Dublin. (RTÉ News, Ireland)</li>\n</ul>\n<h3>Oceania</h3>\n<ul>\n<li><strong><a href="https://www.smh.com.au/politics/federal/ley-s-top-lieutenants-lean-towards-scrapping-net-zero-as-leadership-in-peril-20251103-p5n78b.html">Ley\'s Leadership in Peril as Senior Liberals Move to Dump Net Zero</a></strong>: Senior Liberal Party members are pushing to abandon the net zero emissions policy, threatening the leadership position of the party leader. (The Sydney Morning Herald, Australia)</li>\n<li><strong><a href="https://www.dailypost.vu/news/first-x-ray-service-for-torba/article_2e500028-0de0-51ac-87ea-95244a3dc33d.html">First X-ray Service for TORBA</a></strong>: The TORBA region in Vanuatu has launched its first-ever X-ray service, significantly improving local healthcare capabilities. (Vanuatu Daily Post)</li>\n<li><strong><a href="https://matangitonga.to/2025/11/03/floats-parade-brings-festivity-nukualofa">Floats Parade Brings Festivity to Nuku\'alofa</a></strong>: A vibrant parade in Nuku\'alofa, Tonga, showcased elaborate displays and brought together local communities in celebration. (Matangi Tonga)</li>\n<li><strong><a href="https://nationnews.com/2025/11/02/deacon-primary-to-reopen-monday-following-upgrade-works/">Deacon\'s Primary to Reopen After Upgrades</a></strong>: Deacon\'s Primary School in Barbados will reopen on Monday following the completion of facility improvements. (The Nation Newspaper)</li>\n<li><strong><a href="https://www.samoaobserver.ws/category/samoa/116728">Halt the Parades for Now, Says Police</a></strong>: Samoan police have announced a temporary suspension of parades due to safety concerns. (Samoa Observer)</li>\n</ul>\n<h2>Detailed News Coverage</h2>\n<h3>Political Developments</h3>\n<p><strong><a href="https://www.lemonde.fr/en/international/article/2025/11/02/israel-receives-the-remains-of-three-hostages-from-gaza-as-fragile-ceasefire-holds_6747028_4.html">Israel Receives Remains of Three Hostages from Gaza</a></strong>: Israel has received the remains of three hostages from Gaza amid a fragile ceasefire. According to former President Trump, one of the bodies released is that of American-Israeli IDF soldier Omer Neutra. The transfer occurs as part of ongoing negotiations between the parties, with the ceasefire remaining tenuous. (Le Monde, France)</p>\n<p><strong><a href="https://ria.ru">Trump: Putin Is a Strong Leader Whom One Cannot Play With</a></strong>: Former U.S. President Trump has characterized Russian President Putin as a strong leader who cannot be manipulated, signaling potential shifts in diplomatic approaches should Trump return to office. (RIA Novosti, Russia)</p>\n<p><strong><a href="https://www.cameroon-tribune.cm/article.html/73520/fr.html/presidentielle-2025-paul-biya-reelu">Paul Biya Re-elected in Cameroon Presidential Election</a></strong>: Paul Biya has secured another term as President of Cameroon following the 2025 presidential election, extending his decades-long rule over the country. (Cameroon Tribune)</p>\n<p><strong><a href="https://guardian.ng/news/nigeria/national/nigeria-urges-trump-meeting-after-military-action-threat/">Nigerian Urges Trump Meeting After Military Action Threat</a></strong>: Nigeria is seeking diplomatic engagement with former President Trump following his threat of military action regarding regional issues, highlighting tensions in U.S.-Nigeria relations. (The Guardian Nigeria)</p>\n<p><strong><a href="https://www.searchlight.vc/breaking-news/2025/11/01/former-mp-selmon-walters-laid-rest-today/">Former MP Selmon Walters to Be Laid to Rest Today</a></strong>: The funeral for former Member of Parliament Selmon Walters is taking place today in Saint Vincent and the Grenadines, drawing political colleagues and community members. (Searchlight)</p>\n<h3>Conflicts and Tensions</h3>\n<p><strong><a href="https://www.aljazeera.com/news/2025/11/2/palestinians-face-hunger-cold-and-loss-amid-ongoing-israeli-siege-on-gaza">Palestinians Face Hunger, Cold and Loss Amid Ongoing Israeli Siege</a></strong>: Gaza residents continue to experience severe shortages of food and essential supplies due to the ongoing Israeli siege, with winter conditions exacerbating the humanitarian crisis. (Al Jazeera, Qatar)</p>\n<p><strong><a href="https://kuwaittimes.com/article/35248/top-stories/gaza-children-back-to-school/">Gaza Children Back to School</a></strong>: Children in Gaza are returning to classrooms after disruptions from recent conflicts, with schools implementing safety measures and mental health support to restore educational normalcy. (Kuwait Times)</p>\n<p><strong><a href="https://www.entekhab.ir/fa/news/893035/رسانه\u200c-عبری-اسرائیل-در-تدارک-گشودن-جبهه\u200cای-جدید-در-عراق-است">Israeli Media: Israel Is Preparing to Open a New Front in Iraq</a></strong>: Israeli media reports suggest that Israel is planning military operations in Iraq, potentially escalating regional tensions in the Middle East. (Entekhab, Iran)</p>\n<p><strong><a href="https://www.zdg.md/stiri/live-text-fortele-ruse-bombardeaza-regiunea-herson-mai-multe-persoane-sunt-ranite-razboi-in-ucraina-ziua-1348/">Russian Forces Bombard Kherson Region, War in Ukraine Day 1348</a></strong>: Russian forces continue to target Ukraine\'s Kherson region, resulting in multiple injuries as the conflict enters its 1,348th day. (Ziarul de Gardă, Republic of Moldova)</p>\n<p><strong><a href="https://www.dnes.bg/a/2-svyat/698439-turskiyat-vanshen-ministar-ankara-ochakva-deynostite-na-pkk-v-irak-da-badat-prekrateni">Turkey\'s Foreign Minister: Ankara Expects PKK Activities in Iraq to Cease</a></strong>: Turkey\'s Foreign Minister has stated that Ankara anticipates an end to PKK activities in Iraq as part of ongoing military and diplomatic efforts in the region. (dnes.bg, Bulgaria)</p>\n<h3>Economic News</h3>\n<p><strong><a href="https://www.nacion.com/economia/tarjetas-de-credito-en-costa-rica-un-banco/GRGYTDUJTBHN7DWOZGLFM6XHGU/story/">Credit Cards in Costa Rica: One Bank Controls Nearly Half of Business</a></strong>: A single bank dominates Costa Rica\'s credit card market with nearly 50% market share, raising concerns about competition and consumer choice in the financial sector. (La Nación, Costa Rica)</p>\n<p><strong><a href="https://www.vrt.be/vrtnws/en/2025/10/30/inflation-falls-to-2-per-cent-in-october-what-became-cheaper-w/">Inflation Falls to 2% in October in Belgium</a></strong>: Belgium\'s inflation rate decreased to 2% in October, with lower prices for food and energy offset by rising costs in housing and transportation, signaling a mixed economic outlook. (VRT NWS, Belgium)</p>\n<p><strong><a href="https://www.namibian.com.na/gipf-faces-n1-billion-loss-after-underperforming-offshore-investments-in-sa/">GIPF Faces N$1 Billion Loss After Underperforming Investments</a></strong>: Namibia\'s Government Institutions Pension Fund is projecting losses of N$1 billion due to poor performance of its South African offshore investments. (The Namibian)</p>\n<p><strong><a href="https://www.bondia.ad/societat/els-comuns-entren-550-llicencies-a-urbanisme-71-mes-que-el-2023">The Municipalities Submit 550 Licenses to Urban Planning</a></strong>: Andorra\'s municipalities have submitted 550 licenses to Urban Planning, representing an increase of 71 licenses compared to 2023 and indicating growth in urban development. (Bondia.ad)</p>\n<p><strong><a href="https://www.ena.et/web/eng/w/eng_7634853">Ethiopia\'s Economic Growth Creates Opportunities for Manufacturing</a></strong>: Ethiopia\'s Ministry highlights strong economic growth that\'s opening significant opportunities in the manufacturing sector, aiming to enhance industrialization and attract investment. (Ethiopian News Agency)</p>\n<h3>Sports News</h3>\n<p><strong><a href="https://www.emol.com/noticias/Deportes/2025/11/02/1182103/coquimbo-unido-campeon-futbol-chileno.html">Coquimbo Unido Becomes First Champion of Chilean Football</a></strong>: Coquimbo Unido has made history by becoming the first champion of Chilean football, marking a significant milestone for the club. (emol.com, Chile)</p>\n<p><strong><a href="https://www.corriere.it/sport/tennis/diretta-live/25_novembre_02/sinner-auger-aliassime-finale-parigi-diretta.shtml">Sinner Beats Auger-Aliassime in Tennis Final</a></strong>: Jannik Sinner defeated Felix Auger-Aliassime in a thrilling tennis match, with his powerful backhand down the line proving decisive. (Corriere della Sera, Italy)</p>\n<p><strong><a href="https://radiookapi.net/2025/11/02/actualite/sport/football-ligue-1-lupopo-renverse-mazembe-vita-club-freine-par-maniema">Football Ligue 1: Lupopo Defeats Mazembe, Vita Club Held by Maniema</a></strong>: In DR Congo\'s Ligue 1, Lupopo secured a comeback victory against Mazembe, while Vita Club was held to a draw by Maniema Union. (Radio Okapi, Democratic Republic of the Congo)</p>\n<p><strong><a href="https://www.spiegel.de/sport/basketball/nba-oklahoma-city-bleibt-ungeschlagen-und-isaiah-hartenstein-brilliert-a-957ba71d-ff31-4dba-b3da-d62bec074000">Oklahoma Remains NBA Benchmark, Hartenstein Shines</a></strong>: The Oklahoma City Thunder continues its strong start to the NBA season, while German player Isaiah Hartenstein delivers impressive performances. (Der Spiegel, Germany)</p>\n<p><strong><a href="https://www.gabonews.ga/sports/handball/39/lallemagne-u-17-en-finale-mondiale-apres-une-victoire-ecrasante-sur-le-qatar/">Germany U-17 Reaches World Cup Final After Victory Over Qatar</a></strong>: Germany\'s Under-17 team has secured a place in the World Cup final following a dominant win against Qatar. (Gabonews, Gabon)</p>\n<h3>Health &amp; Science</h3>\n<p><strong><a href="https://www.bbs.bt/235112/">Justice Sector Commits to Digital Case Management in Bhutan</a></strong>: Key institutions in Bhutan\'s justice sector are implementing new digital case management systems to enhance efficiency and accessibility within judicial processes. (Bhutan Broadcasting Service)</p>\n<p><strong><a href="https://kathmandupost.com/national/2025/11/02/unseasonal-rains-devastate-paddy-harvest-across-nepal">Unseasonal Rains Devastate Paddy Harvest Across Nepal</a></strong>: Unexpected rainfall in Nepal has severely damaged paddy harvests, threatening food security as farmers report significant crop losses. (The Kathmandu Post)</p>\n<p><strong><a href="https://www.breakingbelizenews.com/2025/11/02/jamaica-braces-for-egg-and-food-shortages-after-hurricane-melissa/">Jamaica Braces for Food Shortages After Hurricane Melissa</a></strong>: Jamaica is preparing for potential egg and food shortages following the impact of Hurricane Melissa, which has disrupted supply chains and agricultural production. (Breaking Belize News)</p>\n<p><strong><a href="https://www.anacao.cv/noticia/2025/11/03/menopausa-uma-travessia-silenciosa-e-transformadora/">Menopause: A Silent and Transformative Journey</a></strong>: A feature in Cabo Verde\'s A Nação newspaper highlights the often-overlooked impacts of menopause on women\'s physical and emotional health, emphasizing the need for greater awareness and support. (A Nação)</p>\n<p><strong><a href="https://www.jornalnoticias.co.mz/2025/11/02/medicos-decidem-suspender-greve-no-hospital-central-de-nampula/">Medics Suspend Strike at Central Hospital of Nampula</a></strong>: Medical staff at Mozambique\'s Central Hospital of Nampula have decided to suspend their strike action following negotiations addressing their concerns. (Noticias)</p>\n<h3>Society &amp; Culture</h3>\n<p><strong><a href="https://pajhwok.com/2025/11/02/from-hardships-to-hope-daikundi-woman-leads-change/">From Hardships to Hope: Daikundi Woman Leads Change</a></strong>: A determined woman from Afghanistan\'s Daikundi province is transforming her community despite significant challenges, leading initiatives to improve living conditions. (Pajhwok Afghan News)</p>\n<p><strong><a href="https://vientianetimes.org.la/freefreenews/freecontent_212_That_y25.php">That Luang Festival Kicks Off in Laos</a></strong>: The That Luang festival has begun in Laos, celebrating cultural heritage and religious traditions while uniting participants from diverse backgrounds. (Vientiane Times)</p>\n<p><strong><a href="https://www.kathimerini.gr/society/563899600/vorizia-skines-archaias-tragodias-meta-to-foniko-se-ypsisti-epifylaki-i-el-as/">Blood Feud in Vorizia: Scenes of Ancient Tragedy</a></strong>: A murder in Vorizia, Greece, has triggered a violent blood feud reminiscent of ancient tragedies, with police on high alert to prevent further violence. (Kathimerini, Greece)</p>\n<p><strong><a href="https://www.delfi.lv/life/56017194/attiecibas/120093401/virietis-pelna-vairak-norma-sieviete-pelna-vairak-problema">A Man Earns More – a Norm. A Woman Earns More – a Problem?</a></strong>: A Latvian article examines societal double standards where men\'s higher earnings are accepted while women\'s financial success often faces scrutiny and criticism. (Delfi, Latvia)</p>\n<p><strong><a href="https://www.wort.lu/panorama/warum-eine-stadt-in-italien-strasse

In [6]:
website = "https://asia.nikkei.com/business/tech/semiconductors"

In [8]:
html_dict = extract_html.get_raw_html(website)
html_string = html_dict["html"]
clean_text = remove_html_tags(html_string)

if len(html_string) > 200000:
    html_string_input = clean_text
else:
    html_string_input = html_string

In [9]:
html_string

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <link href="/images/frontend/favicons/default.png" rel="icon" type="image/png"/>\n  <link href="/images/frontend/favicons/144x144.png" rel="icon" sizes="144x144" type="image/png"/>\n  <link href="/images/frontend/favicons/288x288.png" rel="icon" sizes="288x288" type="image/png"/>\n  <link href="/images/frontend/favicons/144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144"/>\n  <link href="/images/frontend/favicons/288x288.png" rel="apple-touch-icon-precomposed" sizes="288x288"/>\n  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>\n  <meta content="yes" name="mobile-web-app-capable"/>\n  <meta content="yes" name="apple-mobile-web-app-capable"/>\n  <meta content="Nikkei Asia" name="application-name"/>\n  <meta content="Nikkei Asia" name="apple-mobile-web-app-title"/>\n  <meta content="#0076bf" name="theme-color"/>\n  <meta content="#0076bf" name="msapplication-navbutton-color"/>\n  <meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/>\n  <meta content="/" name="msapplication-starturl"/>\n  <meta content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport"/>\n  <meta content="nikkei, asian, review, publication, insight, business, asia, Asia300, asian business, asia insights, asian finance, asian economy, asian political news, asian analysis, asia focused, for asia, by asia, asian news in english, Nikkei Asian Review, Nikkei Asia, asia.nikkei.com, NAR" name="keywords"/>\n  <meta content="Japan, China, India and Southeast Asia news and expert analysis published by Nikkei, an award-winning independent provider of quality journalism." name="description"/>\n  <title>\n   Semiconductors: News &amp; Insights - Nikkei Asia\n  </title>\n  <meta content="summary" name="twitter:card"/>\n  <meta content="@NAR" name="twitter:site"/>\n  <meta content="Semiconductors" name="twitter:title" property="og:title"/>\n  <meta content="Japan, China, India and Southeast Asia news and expert analysis published by Nikkei, an award-winning independent provider of quality journalism." name="twitter:description" property="og:description"/>\n  <meta content="https://images.ft.com/v3/image/raw/https%3A%2F%2Fasia.nikkei.com%2Fimages%2Ffrontend%2Ffavicons%2F630x630.png?width=630&amp;fit=cover&amp;gravity=faces&amp;dpr=2&amp;quality=medium&amp;source=nar-cms&amp;format=auto&amp;height=630" name="twitter:image" property="og:image"/>\n  <meta content="https://asia.nikkei.com/business/tech/semiconductors" name="og:url" property="og:url"/>\n  <meta content="website" name="og:type" property="og:type"/>\n  <meta content="Nikkei Asia" name="og:site_name" property="og:site_name"/>\n  <meta content="en_GB" name="og:locale" property="og:locale"/>\n  <meta content="https://images.ft.com/v3/image/raw/https%3A%2F%2Fasia.nikkei.com%2Fimages%2Ffrontend%2Ffavicons%2F630x630.png?width=630&amp;fit=cover&amp;gravity=faces&amp;dpr=2&amp;quality=medium&amp;source=nar-cms&amp;format=auto&amp;height=630" name="og:image" property="og:image"/>\n  <meta content="630" name="og:image:width" property="og:image:width"/>\n  <meta content="630" name="og:image:height" property="og:image:height"/>\n  <meta content="Japan, China, India and Southeast Asia news and expert analysis published by Nikkei, an award-winning independent provider of quality journalism." name="og:description" property="og:description"/>\n  <link href="/business/tech/semiconductors?page=2" rel="next"/>\n  <link href="https://asia.nikkei.com/business/tech/semiconductors" rel="canonical"/>\n  <meta content="34" name="next-head-count"/>\n  <script client-env=\'{"NEXT_PUBLIC_DISABLE_NEXT_ROUTER":true,"NEXT_PUBLIC_HOTJAR_ID":629942,"NEXT_PUBLIC_HOTJAR_VERSION":6,"NEXT_PUBLIC_PIANO_DEBUG":false,"NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID":"GTM-PGQQD4B","NEXT_PUBLIC_GOOGLE_ANALYTICS_ID":"UA-44606671-1","NEXT_PUBLIC_GOOGLE_ANALYTICS_SITE":"asia.nikkei.com","NEXT_PUBLIC_FRONTEND_CLOUDFRONT_STATIC_URL":"https://d2p3vtsww1sn4i.cloudfront.net","NEXT_PUBLIC_SHOW_AD_BLOCK":false,"NEXT_PUBLIC_OUTBRAIN_ADVERTISING_ID":"00280e9c9208103b82992e13a5e43683ac","NEXT_PUBLIC_FACEBOOK_PIXEL_ID":"1076130949081971","NEXT_PUBLIC_CHARTBEAT_ID":"54438","NEXT_PUBLIC_MY_NEWS_EXPANSION_ENABLED":false,"NEXT_PUBLIC_AI_FEATURES_ENABLED":false,"NEXT_PUBLIC_DEFAULT_PAGINATION_LIMIT":40,"NEXT_PUBLIC_SEARCH_PAGINATION_LIMIT":200,"NEXT_PUBLIC_PRODUCT_MATRIX_ENABLED":false}\' shared-frontend-env=\'{"NEXT_PUBLIC_NODE_ENV":"production","NEXT_PUBLIC_BASE_URL":"https://asia.nikkei.com","NEXT_PUBLIC_APOLLO_TIMEOUT_MS":30000,"NEXT_PUBLIC_APPLY_CYPRESS_PROPERTIES":false,"NEXT_PUBLIC_APOLLO_SERVER_URL":"https://asia.nikkei.com/api/__service/next_api/v1/graphql","NEXT_PUBLIC_PIANO_ID":"3keAb0xYpj","NEXT_PUBLIC_PIANO_ENV":"prod","NEXT_PUBLIC_PIANO_URL":"https://experience-ap.piano.io","NEXT_PUBLIC_ATLAS_SDK_API_KEY":"885cfd611594f1cb21ecd50b741a9f55a68fc4d8","NEXT_PUBLIC_ATLAS_ENDPOINT":"https://astat.nikkei.com","NEXT_PUBLIC_SENTRY_ENABLED":true,"NEXT_PUBLIC_ORIGAMI_URL":"https://www.ft.com/__origami/service/image/v2/images/raw"}\'>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){const e=JSON.parse(document.currentScript.getAttribute("client-env")),n=JSON.parse(document.currentScript.getAttribute("shared-frontend-env"));window.clientEnv=e,window.sharedFrontendEnv=n,Object.freeze(window.clientEnv),Object.freeze(window.sharedFrontendEnv)}\n  </script>\n  <script>\n   "undefined"!=typeof window&&"undefined"!=typeof window&&(window.addEventListener("dependencies.service.tracking.ready",(()=>{window.loggedIn=!(!window.paywallState||!window.paywallState.authority||-1!==["A1","A3I","A1S","-",""].indexOf(window.paywallState.authority))})),window.isCount=!1,window.oneClickFree=!1);\n  </script>\n  <script>\n   "undefined"!=typeof window&&"undefined"!=typeof window&&(tp=window.tp||[],tp.push(["init",function(){window.location.pathname.includes("/member")&&tp.pianoId.init({stage:"product-matrix"});const e=new CustomEvent("dependencies.service.piano.init",{detail:{piano:tp}});window.dispatchEvent(e)}]),window.addEventListener("dependencies.service.piano.push",(e=>{tp.push(e.detail.args)})),window.addEventListener("message",(e=>{if(e.data.type&&"get-piano-id"===e.data.type){const e=window.tp.aid;window.postMessage({type:"get-piano-id:response",pianoId:e},"*")}else e.data.type&&"set-access-token"===e.data.type?(window.tp.pianoId.loginByToken(e.data.accessToken),window.postMessage({type:"set-access-token:response"},"*")):e.data.type&&"piano-logout"===e.data.type&&window.tp.pianoId.logout().then((()=>{window.postMessage({type:"piano-logout:response"},"*")}))})),tp.push(["addHandler","showTemplate",function(e){"#paywall-offer"===e.containerSelector&&window.dispatchEvent(new CustomEvent("paywall-shown"))}]));\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){if(!["/account/newsletter-preferences"].find((t=>window.location.pathname.includes(t)))){var _sf_startpt=(new Date).getTime();!function(){var t=window._sf_async_config=window._sf_async_config||{};t.uid=window.clientEnv.NEXT_PUBLIC_CHARTBEAT_ID,t.domain="asia.nikkei.com",t.useCanonical=!0,t.useCanonicalDomain=!0,t.flickerControl=!1}(),function(){var t=document.createElement("script");t.setAttribute("async","true"),t.setAttribute("type","text/javascript"),t.setAttribute("src","//static.chartbeat.com/js/chartbeat_mab.js"),document.head.appendChild(t)}()}}\n  </script>\n  <script id="google-tag-manager">\n   if("undefined"!=typeof window&&"undefined"!=typeof window){const e=()=>{window.removeEventListener("dependencies.service.tracking.ready",e);((e,n,t,a,d)=>{e[a]=e[a]||[],e[a].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});const i=n.getElementsByTagName(t)[0],o=n.createElement(t),r="dataLayer"!==a?"&l="+a:"";o.async=!0,o.src="https://www.googletagmanager.com/gtm.js?id="+d+r,o.addEventListener("load",(()=>{window.googletag.pubads().setTargeting("path",location.pathname)})),i.parentNode.insertBefore(o,i)})(window,document,"script","dataLayer",window.clientEnv.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID)};["/account/newsletter-preferences"].find((e=>window.location.pathname.includes(e)))||window.addEventListener("dependencies.service.tracking.ready",e)}\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){const e=()=>{var n,i,o,s,d,t;window.removeEventListener("dependencies.service.session.ready",e),n=window,i=document,o="script",s="ga",n.GoogleAnalyticsObject=s,n[s]=n[s]||function(){(n[s].q=n[s].q||[]).push(arguments)},n[s].l=1*new Date,d=i.createElement(o),t=i.getElementsByTagName(o)[0],d.async=1,d.src="//www.google-analytics.com/analytics.js",t.parentNode.insertBefore(d,t),ga("create",window.clientEnv.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID,window.clientEnv.NEXT_PUBLIC_GOOGLE_ANALYTICS_SITE),ga("set","dimension1","-"!==window.session.memberId?"true":"false"),window.session&&""!==window.session.authority&&ga("set","dimension2",window.session.authority),window.session&&"-"!==window.session.memberId&&ga("set","dimension3",window.session.memberId);const w=window.sharedFrontendEnv.NEXT_PUBLIC_PIANO_ID;ga("set","dimension4",w),"undefined"!=typeof viewMode&&""!==viewMode&&ga("set","dimension5",viewMode),"undefined"!=typeof contractId&&""!==contractId&&ga("set","dimension6",contractId),"undefined"!=typeof c_code&&""!==c_code&&ga("set","dimension7",c_code),ga("send","pageview"),window.oneClickFree&&ga("send","event","OneClickFree","view","OneClickFree-view",{nonInteraction:!0})};[].find((e=>window.location.pathname.includes(e)))||window.addEventListener("dependencies.service.session.ready",e)}\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){const e=()=>{window.removeEventListener("dependencies.service.session.ready",e);var n="na";if(window.session?.authority){n="sub_1";var o=window.session.authority;-1!==["A2h","A2","A2P"].indexOf(o)?n="ex":-1!==["A1","A1S","A2N"].indexOf(o)&&(n="no")}window.googletag=window.googletag||{},googletag.cmd=googletag.cmd||[],googletag.cmd.push((function(){googletag.pubads().setTargeting("swgt",n),googletag.pubads().setTargeting("path",location.pathname)}))};["/account/newsletter-preferences","/member/register"].find((e=>window.location.pathname.includes(e)))||window.addEventListener("dependencies.service.session.ready",e)}\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){["/account/newsletter-preferences"].find((e=>window.location.pathname.includes(e)))||(!function(e,n,t,o,i,c,f){e.fbq||(i=e.fbq=function(){i.callMethod?i.callMethod.apply(i,arguments):i.queue.push(arguments)},e._fbq||(e._fbq=i),i.push=i,i.loaded=!0,i.version="2.0",i.queue=[],(c=n.createElement(t)).async=!0,c.src="https://connect.facebook.net/en_US/fbevents.js",(f=n.getElementsByTagName(t)[0]).parentNode.insertBefore(c,f))}(window,document,"script"),fbq("init",window.clientEnv.NEXT_PUBLIC_FACEBOOK_PIXEL_ID),fbq("track","PageView"))}\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){["/account/newsletter-preferences"].find((t=>window.location.pathname.includes(t)))||window.addEventListener("dependencies.service.tracking.ready",(()=>{if(-1==window.location.host.indexOf("staging")&&"article"==window.paywallState?.contentTypeIdentifier){var t=document,e=t.getElementsByTagName("head")[0],r=t.createElement("meta");r.setAttribute("property","product:availability");var n=new Date(tracking_data.publish_date),a=(new Date).getTime()-n.getTime(),i=Math.floor(a/864e5);i>90?r.setAttribute("content","out of stock"):r.setAttribute("content","in stock"),e.appendChild(r);var o=t.createElement("meta");o.setAttribute("property","product:custom_label_0"),o.setAttribute("content",i),e.appendChild(o);var d=t.createElement("meta");d.setAttribute("property","product:custom_label_1"),d.setAttribute("content",window.tracking_data.source),e.appendChild(d);var c=t.createElement("meta");c.setAttribute("property","product:brand"),c.setAttribute("content",window.tracking_data.section),e.appendChild(c);var p=t.createElement("meta");p.setAttribute("property","product:category"),p.setAttribute("content",window.tracking_data.topic),e.appendChild(p);var u=t.createElement("meta");u.setAttribute("property","product:retailer_item_id"),u.setAttribute("content",window.tracking_data.article_id),e.appendChild(u);var l=t.createElement("meta");l.setAttribute("property","product:condition"),l.setAttribute("content","new"),e.appendChild(l);var s=t.createElement("meta");s.setAttribute("property","product:price:amount"),s.setAttribute("content","1"),e.appendChild(s);var m=t.createElement("meta");m.setAttribute("property","product:price:currency"),m.setAttribute("content","USD"),e.appendChild(m)}}))}\n  </script>\n  <script async="" src="//platform.twitter.com/oct.js" type="text/javascript">\n  </script>\n  <script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js">\n  </script>\n  <script>\n   if("undefined"!=typeof window&&"undefined"!=typeof window){["/account/newsletter-preferences"].some((e=>window.location.pathname.includes(e)))||window.dispatchEvent(new CustomEvent("dependencies.service.piano.push",{detail:{args:["init",function(){try{const t=document.createElement("script");t.setAttribute("id","outbrain-script"),t.setAttribute("type","text/javascript"),t.setAttribute("async","async"),t.src="//widgets.outbrain.com/outbrain.js",document.head.appendChild(t),t.addEventListener("load",e)}catch(e){}}]}}));const e=()=>{!function(e,t){var n=window.clientEnv.NEXT_PUBLIC_OUTBRAIN_ADVERTISING_ID;if(e.obApi){var i=function(e){return"[object Array]"===Object.prototype.toString.call(e)?e:[e]};e.obApi.marketerId=i(e.obApi.marketerId).concat(i(n))}else{var a=e.obApi=function(){a.dispatch?a.dispatch.apply(a,arguments):a.queue.push(arguments)};a.version="1.1",a.loaded=!0,a.marketerId=n,a.queue=[];var r=t.createElement("script");r.async=!0,r.src="//amplify.outbrain.com/cp/obtp.js",r.type="text/javascript";var o=t.getElementsByTagName("script")[0];o.parentNode.insertBefore(r,o)}}(window,document),obApi("track","PAGE_VIEW"),window.dispatchEvent(new CustomEvent("dependencies.service.outbrain.ready"))}}\n  </script>\n  <link href="/public-assets/manifest.json" rel="manifest"/>\n  <link href="https://fonts.googleapis.com" rel="preconnect"/>\n  <link href="https://fonts.gstatic.com" rel="preconnect"/>\n  <style>\n  </style>\n  <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;500;600;700&amp;display=swap" media="print" onload="this.media = \'all\';" rel="stylesheet"/>\n  <style>\n  </style>\n  <script async="" crossorigin="anonymous" defer="" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v16.0">\n  </script>\n  <noscript>\n   <img height="1" src="https://www.facebook.com/tr?id=1076130949081971&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>\n  </noscript>\n  <script data-nscript="beforeInteractive" id="replaceArticleBody">\n   "undefined"!=typeof window&&"undefined"!=typeof window&&(window.replaceArticleBody=function(){const e=new Event("articleAccessCalled");document.dispatchEvent(e)});\n  </script>\n  <script data-nscript="beforeInteractive" id="setupExpiredSubscription">\n   if("undefined"!=typeof window&&"undefined"!=typeof window){const e="PreviousSubs",t=window.localStorage,n=JSON.parse(t.getItem(e))||{};window.dispatchEvent(new CustomEvent("dependencies.service.piano.updated",{detail:{args:["addHandler","experienceExecute",o=>{if(!o||!o.user||!o.user.uid||"anon"===o.user.uid)return;const i=o.user.uid;o.accessList.length>=1&&(n[i]=!0),n.hasOwnProperty(i)&&0===o.accessList.length&&(delete n[i],document.cookie="__tac=; Max-Age=0; path=/; domain="+location.host,document.cookie="__tac=; Max-Age=0; path=/; domain="+location.hostname,document.cookie="__tac=; Max-Age=0; path=/; domain=.nikkei.com"),t.setItem(e,JSON.stringify(n))}]}}))}\n  </script>\n  <script async="" data-nscript="beforeInteractive" id="schema-org" type="application/ld+json">\n   {"@context":"https://schema.org","@type":"Thing","mainEntityOfPage":"https://asia.nikkei.com/business/tech/semiconductors","name":"Semiconductors"}\n  </script>\n  <link as="style" href="/_next/static/css/d55e5253fb13b991.css" rel="preload"/>\n  <link data-n-g="" href="/_next/static/css/d55e5253fb13b991.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/4f27eb6722ddbfe5.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/4f27eb6722ddbfe5.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/6ce224c75b0ce022.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/6ce224c75b0ce022.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/df7110f730630b19.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/df7110f730630b19.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/02918951e00490ee.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/02918951e00490ee.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/0934266b7fc9508d.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/0934266b7fc9508d.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/314a8b7317bf827a.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/314a8b7317bf827a.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/ffbe025e356edc76.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/ffbe025e356edc76.css" rel="stylesheet"/>\n  <link as="style" href="/_next/static/css/f8bc5f1eca545837.css" rel="preload"/>\n  <link data-n-p="" href="/_next/static/css/f8bc5f1eca545837.css" rel="stylesheet"/>\n  <noscript data-n-css="">\n  </noscript>\n  <script defer="" nomodule="" src="/_next/static/chunks/polyfills-42372ed130431b0a.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/webpack-4b4b4826b301d994.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/framework-a32fdada02556615.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/main-a66c75b9611067ce.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/pages/_app-b6bc0a26690875ac.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/a5a946bf-c9db86cde31e93cb.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/9097-797492b16d6167aa.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/3374-ba0b1b5fe8990296.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/2117-02df4f145bb4093e.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/6741-e0f6ec9163416b4a.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/7159-2d5dd1999f774d71.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/982-8d5ea2f18a636e26.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/4783-6200d7da9e6931c8.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/9501-4e01e1ae85598b73.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/2596-6edfaec74234eac2.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/8321-38a949c3b67ff9ea.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/7111-9a5e040c88c84196.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/2171-38853b7d10a01616.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/8308-53f62f58c2b1869f.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/1373-401b3e894e229b8f.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/6718-124437b375898336.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/2459-c6deb70d7d48325d.js">\n  </script>\n  <script defer="" src="/_next/static/chunks/pages/%5B...alias%5D-8f70d7619c987e28.js">\n  </script>\n  <script defer="" src="/_next/static/MBN7XKHbBL_6QvTB8Xn0T/_buildManifest.js">\n  </script>\n  <script defer="" src="/_next/static/MBN7XKHbBL_6QvTB8Xn0T/_ssgMa

In [10]:
from pydantic import BaseModel, Field
from pydantic import ValidationError
from typing import List

In [11]:
class Headlines(BaseModel):
    headlines: List[str]

In [12]:
prompt = f"""
You are a web scraper that extracts news headlines from a news site's homepage HTML.

Here is the full HTML of the news site:

```{html_string_input}```

Extract the top 10 most prominent headlines of the day. 
Focus on the main stories shown at the top of the page (usually the hero story and the next 9 featured stories). 
Ignore navigation links, video titles, weather, sport sub-sections, and advertisements.

Return ONLY a JSON object that matches this exact schema:
{{
  "headlines": [
    "headline 1",
    "headline 2",
    ...
  ]
}}
Do not include any explanations, markdown, or extra text. 
If there are fewer than 10 prominent headlines, return all of them.
"""

In [13]:
response = await client.chat.completions.create(
    model="openai/gpt-4o-mini",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.2,        # low temperature for reliable extraction
#     max_tokens=1500,
)

In [14]:
raw_content = response.choices[0].message.content.strip()

In [15]:
raw_content

'{\n  "headlines": [\n    "TSMC to make advanced chips for AI at 2nd Japan plant",\n    "Chip titan will switch to 3-nm node, helping Japan secure stable supply of powerful products",\n    "HP, Dell, Acer and Asus mull using Chinese memory chips amid supply crunch",\n    "Japan chipmaker Rapidus tops $1bn in private investment as IBM aims to join",\n    "AMD rakes in $390m from AI chip sales to China but warns of uncertainty",\n    "AI effect starts to flip \'Korea discount\' on stocks into a premium",\n    "Apple supplier Nittobo to roll out improved glass cloth crucial to AI chips",\n    "What bubble? Big Tech\'s AI spending spree gathers pace in 2026",\n    "Japan\'s Renesas to sell timing solution segment to US-based SiTime for $3bn",\n    "TSMC\'s American expansion is not a surrender -- it\'s insurance for Taiwan"\n  ]\n}'

In [16]:
try:
    # Parse the JSON output directly into your Pydantic model
    data = json.loads(raw_content)
    top_headlines = Headlines(**data)
    
    # Now you have a clean list of strings
    print("Top 10 Headlines:")
    for i, headline in enumerate(top_headlines.headlines, 1):
        print(f"{i}. {headline}")
        
except json.JSONDecodeError as e:
    print("LLM did not return valid JSON:", e)
    print("Raw output:", raw_content)
except ValidationError as e:
    print("Validation error:", e)
    print("Raw output:", raw_content)

Top 10 Headlines:
1. TSMC to make advanced chips for AI at 2nd Japan plant
2. Chip titan will switch to 3-nm node, helping Japan secure stable supply of powerful products
3. HP, Dell, Acer and Asus mull using Chinese memory chips amid supply crunch
4. Japan chipmaker Rapidus tops $1bn in private investment as IBM aims to join
5. AMD rakes in $390m from AI chip sales to China but warns of uncertainty
6. AI effect starts to flip 'Korea discount' on stocks into a premium
7. Apple supplier Nittobo to roll out improved glass cloth crucial to AI chips
8. What bubble? Big Tech's AI spending spree gathers pace in 2026
9. Japan's Renesas to sell timing solution segment to US-based SiTime for $3bn
10. TSMC's American expansion is not a surrender -- it's insurance for Taiwan

In [17]:
for headline in top_headlines.headlines:
    print(headline)

TSMC to make advanced chips for AI at 2nd Japan plant
Chip titan will switch to 3-nm node, helping Japan secure stable supply of powerful products
HP, Dell, Acer and Asus mull using Chinese memory chips amid supply crunch
Japan chipmaker Rapidus tops $1bn in private investment as IBM aims to join
AMD rakes in $390m from AI chip sales to China but warns of uncertainty
AI effect starts to flip 'Korea discount' on stocks into a premium
Apple supplier Nittobo to roll out improved glass cloth crucial to AI chips
What bubble? Big Tech's AI spending spree gathers pace in 2026
Japan's Renesas to sell timing solution segment to US-based SiTime for $3bn
TSMC's American expansion is not a surrender -- it's insurance for Taiwan

In [18]:
soup = BeautifulSoup(html_string, "html.parser")

# Extract all links
links = {a.get_text(): a for a in soup.find_all('a')}

# Get text without HTML tags
# text = soup.get_text()
links_on_page = ""

# Append links to the text
for link_text, url in links.items():
    links_on_page += f" [{link_text}]({url})"

In [19]:
len(links_on_page)

71307

In [20]:
headline = top_headlines.headlines[0]
headline

'TSMC to make advanced chips for AI at 2nd Japan plant'

In [21]:
prompt = f'''
Given this identified headline on a news website: "{headline}"
Note that the headline is being translated into English if the original text is non-English.
Please check if the link to that headline is in {links_on_page[:150000]}
If so, please output only the link. 
Note that sometime only the relative url is included. If so, you need to output the absolute url with the root website {website}.
If no link is founded, just output 'N/A'
Do not output anything else other than the link
Do not output any html tags e.g., '<a href=', '</a>'
'''

response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

In [22]:
response.choices[0].message.content.strip()

'https://asia.nikkei.com/business/tech/semiconductors/tsmc-to-make-advanced-chips-for-ai-at-2nd-japan-plant'

In [5]:
def scrape_data(url):
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    # These two lines help avoid detection and reduce cookie banner issues
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_experimental_option("excludeSwitches", ["enable-automation"])

    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    wait = WebDriverWait(driver, 20)

    try:
        driver.get(url)

        # === STEP 1: Kill the cookie banner first ===
        cookie_accepted = False
        for _ in range(3):  # retry a few times
            try:
                # Most common OneTrust "Accept All" buttons (try several variants)
                accept_button = None
                accept_selectors = [
                    "#onetrust-accept-btn-handler",           # Most common
                    ".onetrust-close-btn-handler",            # Sometimes there's a close X
                    "#onetrust-button-group #accept-recommended-btn-handler",
                    "button[aria-label*='Accept' i]",         # Case-insensitive "Accept"
                    "button:contains('Accept')",              # fallback (rare)
                    "#onetrust-pc-btn-handler",               # "Reject All" or "Manage" sometimes works too
                ]

                for selector in accept_selectors:
                    try:
                        accept_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, selector)))
                        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", accept_button)
                        driver.execute_script("arguments[0].click();", accept_button)  # JS click = more reliable
                        print("Cookie banner accepted")
                        cookie_accepted = True
                        time.sleep(2)
                        break
                    except:
                        continue
                
                if cookie_accepted:
                    break
            except:
                pass
            time.sleep(1)

        # === STEP 2: Now safely click "7 DAYS" ===
        try:
            seven_days = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "label[for='Daterange2']")))
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", seven_days)
            driver.execute_script("arguments[0].click();", seven_days)
            print("'7 DAYS' clicked successfully")
            time.sleep(2)  # let the table reload
        except Exception as e:
            print("Could not click 7 DAYS:", e)

        # === STEP 3: Wait for table content to actually change/load ===
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "table tr td")))
        time.sleep(3)  # small buffer – you can make this smarter later

        # === Your original scraping logic here ===
        extracted_data = []
        table_rows = driver.find_elements(By.CSS_SELECTOR, 'table tr')
        
        for row in table_rows:
            cells = row.find_elements(By.TAG_NAME, 'td')
            if cells and len(cells) >= 4:
                date_time_text = cells[0].text.strip()
                code_text = cells[1].text.strip()
                company_text = cells[2].text.strip()
                headline_text = cells[3].text.strip()
                
                # Find PDF link
                link = ""
                all_links = cells[3].find_elements(By.TAG_NAME, 'a')
                for link_element in all_links:
                    href = link_element.get_attribute('href')
                    if href and '.pdf' in href.lower():
                        link = href
                        break
                
                # Parse date/time
                date_str = date_time_text
                time_str = ""
                if ' ' in date_time_text:
                    date_str, time_str = date_time_text.split(' ', 1)
                
                # Handle multi-company rows
                if '\n' in code_text and '\n' in company_text:
                    codes = [c.strip() for c in code_text.split('\n')]
                    companies = [c.strip() for c in company_text.split('\n')]
                    
                    for code, company in zip(codes, companies):
                        row_data = process_row_data(date_str, time_str, code, company, headline_text, link)
                        extracted_data.append(row_data)
                else:
                    row_data = process_row_data(date_str, time_str, code_text, company_text, headline_text, link)
                    extracted_data.append(row_data)
                    
        return extracted_data
    
    except Exception as e:
        print(f"Error during scraping: {e}")
        return []

    finally:
        driver.quit()


# Helper function to avoid code duplication
def process_row_data(date_str, time_str, code, company, headline_text, link):
    row_data = {
        "date": date_str,
        "time": time_str,
        "code": code,
        "company": company,
        "category": "",
        "title": "",
        "link": link,
        "summary": ""
    }
    
    if '\n' in headline_text:
        parts = headline_text.split('\n', 1)
        if len(parts) == 2:
            category, title = parts
            row_data["category"] = category.strip()
            title = title.split('...More')[0].strip()
            row_data["title"] = title
    else:
        row_data["title"] = headline_text.strip()
    
    return row_data

In [6]:
def prescreen(title):
    if 'Next Day Disclosure Return' in title:
        return False
    else:
        return True

In [7]:
async def is_relevant(title):
    prompt = f"""
    You are a research analyst who is good at screening out minor and irrelevant news of a company by reading the title of an announcement.
    In general, regular returns (e.g., Next Day Disclosure Returns), proxy statement, amendments to articles are not relevant.
    Given the title of the announcement: {title}, please output only 'relevant' or 'irrelevant'
    """
    
    response = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    if response.choices[0].message.content.strip() == "irrelevant":
        return "irrelevant"
    else:
        return "relevant"

In [8]:
def generate_summary(url):
    with tempfile.TemporaryDirectory() as temp_dir:
        pdf_path = os.path.join(os.getcwd(), "document.pdf")
        response = requests.get(url, stream=True, timeout=60)
        response.raise_for_status()
        with open(pdf_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)

    documents = SimpleDirectoryReader(
        input_files=[pdf_path],
    ).load_data()                
            
    summary_index = SummaryIndex(documents)
    
    summary_query_engine = summary_index.as_query_engine(
        response_mode="tree_summarize",
        use_async=True,
    )    

    prompt='''
    Please summarize the document in 4-8 bullets in a concise manner. Avoid legal jargon.
    '''
    
    response = summary_query_engine.query(prompt)
    
    return response.response

In [9]:
data = scrape_data("https://www1.hkexnews.hk/listedco/listconews/index/lci.html?lang=en")

Cookie banner accepted
'7 DAYS' clicked successfully

In [10]:
len(data)

1023

In [11]:
stock_list = [
    "09988", #Alibaba
    "00700", #Tencent
    "09888", #Baidu
    "09618", #JD
    "09999", #Netease
    "01024", #Kuaishou
    "03690", #Meituan
    "01810", #Xiaomi
    "01211", #BYD
    "09866", #NIO
    "09868", #Xpeng
    "02015", #Li Auto
    "09863", #Leap Motor
    "00020", #Sensetime
    "09660", #Horizon Robotics
    "02525", #Hesai
    "02665", #Seyond
    "02498", #Robosense
    "02590", #Geekplus
    "02432", #Dobot
    "09880", #Ubtech
    "02026", #pony
    "00800", #weride
]

In [12]:
len(data)

1023

In [13]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Find the previous weekday
if today.weekday() == 0:  # Monday
    previous_weekday = today - timedelta(days=3)  # Go back to Friday
else:
    previous_weekday = today - timedelta(days=1)  # Go back one day

# Format the dates
formatted_today = today.strftime('%d/%m/%Y')
formatted_previous_weekday = previous_weekday.strftime('%d/%m/%Y')

# Output the result
data_range = [formatted_previous_weekday, formatted_today]
print(data_range)

['16/12/2025', '17/12/2025']

In [14]:
relevant_target_data_ytd = [row for row in data if 
                   row['date'] in data_range and 
                   row['code'] in stock_list and
                    prescreen(row['title']) and
                  await is_relevant(row["title"]) == "relevant"]
len(relevant_target_data_ytd)

0

In [15]:
relevant_target_data_ytd

[]

In [16]:
for row in relevant_target_data_ytd:
    row["summary"] = generate_summary(row["link"])

In [69]:
prompt = f"""
You are a financial news journalist tasked with creating a concise news-style summary of regulatory announcements from listed companies.

I have collected the following regulatory announcements:

{json.dumps(relevant_target_data_ytd, indent=2)}

Please create a concise news-style summary that:
1. Rewrites announcement titles into engaging, journalistic headlines (not just copying the legal titles)
2. Highlights the most significant and noteworthy announcements
3. Groups related announcements when appropriate
4. Includes the source (company name or link) for each item
5. Focuses on information that would be relevant to investors and stakeholders
6. Uses a news writing style - clear, engaging, and accessible

Format your response as:

## Regulatory Announcements Summary

- **News-style headline**: Brief summary of the key points. (Source: [company name or link])
- **News-style headline**: Brief summary of the key points. (Source: [company name or link])
...

Requirements:
- Transform legal/formal announcement titles into news-style headlines that are more readable and engaging
- Be concise (aim for 200-400 words total)
- Prioritize the most significant announcements (major corporate actions, financial results, regulatory changes, etc.)
- Each bullet point should include the source information
- If multiple announcements are from the same company, you may group them together
- Focus on actionable information and material developments
- Write headlines in a journalistic style - active voice, clear, and informative
- Example: Instead of "Company ABC - Annual Results Announcement", write something like "ABC Reports Strong Annual Earnings" or "ABC Posts Record Revenue for Fiscal Year"

Output only the summary, no additional commentary.
"""

In [70]:
response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

listed_co_news = response.choices[0].message.content.strip()

In [132]:
def send_regulatory_summary_email(title, summary_text, recipient_email="davidlau512@gmail.com"):
    # Sender information
    sender_email = "david@xplorehk.com"
    sender_name = "Global Headlines"
    
    # Convert markdown to HTML
    import markdown
    html_content = markdown.markdown(summary_text)
    
    # Email subject
    from datetime import datetime
    subject = f"{title} - {datetime.now().strftime('%B %d, %Y')}"
    
    # Create Mailjet client and send email
    try:
        api_key = os.environ.get('MJ_APIKEY_PUBLIC')
        api_secret = os.environ.get('MJ_APIKEY_PRIVATE')
        
        if not api_key or not api_secret:
            print("❌ Mailjet API keys not found in environment variables")
            return False
        
        mailjet = Client(auth=(api_key, api_secret), version='v3.1')
        
        data = {
            'Messages': [
                {
                    "From": {
                        "Email": sender_email,
                        "Name": sender_name
                    },
                    "To": [{"Email": recipient_email, "Name": "Recipient"}],
                    "Subject": subject,
                    "TextPart": summary_text,
                    "HTMLPart": html_content
                }
            ]
        }
        
        result = mailjet.send.create(data=data)
        
        if result.status_code == 200:
            print(f"✅ Corporate announcement summary sent successfully to {recipient_email}!")
            return True
        else:
            print(f"❌ Failed to send email. Status code: {result.status_code}")
            print(f"Response: {result.json()}")
            return False
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False

In [72]:
# Send the email
send_regulatory_summary_email("Corporate Announcement Summary", listed_co_news)

✅ Corporate announcement summary sent successfully to davidlau512@gmail.com!

True

In [73]:
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
# These two lines help avoid detection and reduce cookie banner issues
options.add_argument('--disable-blink-features=AutomationControlled')
options.add_experimental_option("excludeSwitches", ["enable-automation"])

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
wait = WebDriverWait(driver, 20)
driver.get("http://www.aastocks.com/en/stocks/market/ipo/iponews.aspx")

In [74]:
driver.page_source

'<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#"><head id="Head1"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="google-site-verification" content="PSvX40cckR7V_q8QVaRk5jnTEIeinakRTyMqcjv9WPI"> <script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-38RQTHE076&amp;l=_gtagL&amp;cx=c&amp;gtm=4e5ca1"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-FL2WFCGS0Y&amp;l=_gtagL"></script><script type="text/javascript" async="" src="https://ssl.google-analytics.com/ga.js"></script><script type="text/javascript">\nvar _gaq = _gaq || [];\n_gaq.push([\'_setAccount\', \'UA-20790503-3\']);\n_gaq.push([\'_setDomainName\', \'www.aastocks.com\']);\n_gaq.push([\'_setSampleRate\', \'5\']);\n_gaq.push([\'_trackPageview\']);\n_gaq.push([\'_trackPageLoadTime\']);\n_gaq.push([\'a3._setAccount\', \'UA-130882905-1\']);\n_gaq.push([\'a3._setDomainName\', \'www.aastocks.com\']);\n_gaq.push([\'a3._trackPageview\']);\n_gaq.push([\'a3._trackPageLoadTime\']);\n_gaq.push([\'vt._setAccount\', \'UA-131025525-1\']);\n_gaq.push([\'vt._setDomainName\', \'www.aastocks.com\']);\nfunction OA_show(name) {}\n</script> <meta name="aa-update" content="2025-12-16 12:46:40"> <link href="/en/resources/style/stock_std_eng?v=3NK1XSc9hEdwkNouadfgZpUYw4yDGlMHhIlP-TPF5Vk1" rel="stylesheet"> <!--[if IE]> <link type="text/css" href=\'/en/resources/style/ie.css\' rel="stylesheet" /> <![endif]--> <!--[if IE 6]> <link type="text/css" href=\'/en/resources/style/ie6.css\' rel="stylesheet" /> <![endif]--> <!--[if IE 8]> <style type="text/css">\n#topPanel .menu_item > a > span { letter-spacing:0px; }\n</style> <![endif]--> <!--[if IE 9]> <link type="text/css" href=\'/en/resources/style/ie9.css\' rel="stylesheet" /> <![endif]--> <script src="/en/resources/script/js_std?v=ZbU0IfQBlBrv2n0JyVIVI8PSbxbbcjK5H7U6di_uKtI1"></script> <script type="text/javascript">\nvar APP_LANG = \'eng\';\nvar fullCookiesDomain = \'www.aastocks.com\';\nvar subCookiesDomain = \'.aastocks.com\';\nvar WDataDomain = "https://wdata.aastocks.com";\nvar hostUrl = \'/en/\';\nvar is980Mode = false;\nvar curWidth980Mode = is980Mode;\nvar Error1 = \'Please try again later.\';\nvar Error2 = \'No related information.\';\nvar OA_AAParam = [\'0\'];\nfunction refreshPage() {\nwindow.location.reload();\n}\nif (AAUtility.IsMobileBrowser()) {\ndocument.write("<style>body{-webkit-text-size-adjust:100%;}</style>");\n}\nvar ServerDate = new Date(\'2025-12-16T12:46:40\');\nvar AA_LABEL = {\nLogout: {\nConfirmLogout: \'Confirm logout?\'\n, Logout: \'Logout\'\n, Cancel: \'Cancel\'\n}\n};\nvar TimeDiff_LABEL = {\ndateDiff: {\nJ: \'Just\',\nD: \' day\',\nW: \' week\',\nM: \' month\',\nY: \' year\',\nH: \' hour\',\nMin: \' minute\'\n}\n};\nvar NewsSource_LABEL = {\nfull: {\naa: \'AASTOCKS\'\n, anue: \'ANUE\'\n, glh: \'GLH\'\n, infocast: \'IN\'\n, youlian: \'You Lian Cloud\'\n, zt: \'Zhi Tong\'\n}, short: {\naa: \'AA\'\n, anue: \'ANUE\'\n, glh: \'GLH\'\n, infocast: \'IN\'\n, youlian: \'YLC\'\n, zt: \'ZT\'\n}\n};\nvar AACONFIG = {\nShowMsg: false\n};\nvar AAMessage;\n$(function () {\nAAMessage = $("body").AAMessage({ domain: WDataDomain });\n});\n</script> <script type="text/javascript">_gaq.push([\'a2._setAccount\', \'UA-129665018-1\']); _gaq.push([\'a2._trackPageview\']);</script><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="facebook-domain-verification" content="qks66kbnwjl4vjtrplbyj74zne2aco"><meta name="keywords" content="IPO, Initial Public Offering, Listed IPO, Planned IPO, IPO News, Sponsor, IPO information, IPO calendar, Profit loss, Cash flow, Balance sheet, Offer price, IPO  calculator, IPO grey market"><meta name="description" content="Provide IPO information, including related IPO’s company information, industry comparison , financial comparison, IPO news, IPO calendar, sponsor performance, IPO grey market today, Upcoming IPO grey market."><script>OA_zones = {\'Super_Banner\':55,\'LREC\':58,\'Crazy_iPad_popup\':331};\n</script><script>if (typeof (OA_zones) != \'undefined\') {\nvar OA_zoneids = \'\';\nfor (var zonename in OA_zones) OA_zoneids += escape(zonename + \'=\' + OA_zones[zonename] + "|");\nOA_zoneids += \'&amp;nz=1\';\n} else {\nvar OA_zoneids = escape(\'\');\n}\nif (typeof (OA_source) == \'undefined\') { OA_source = \'\'; }\nvar OA_p = \'//hkg8.aastocks.com/ad/delivery/spc.php\';\nvar OA_r = Math.floor(Math.random() * 99999999);\nOA_output = new Array();\nvar OA_spc = "<" + "script type=\'text/javascript\' ";\nOA_spc += "src=\'" + OA_p + "?zones=" + OA_zoneids;\nOA_spc += "&amp;source=" + escape(OA_source) + "&amp;r=" + OA_r;\nOA_spc += "&amp;block=1&amp;blockcampaign=1&amp;custom_zone=1";\nOA_spc += (document.charset ? \'&amp;charset=\' + document.charset : (document.characterSet ? \'&amp;charset=\' + document.characterSet : \'\'));\nif (window.location) OA_spc += "&amp;loc=" + escape(window.location);\nif (document.referrer) OA_spc += "&amp;referer=" + escape(document.referrer);\nif (typeof OA_AAParam != "undefined") OA_spc += "&amp;aaparam=" + escape(OA_AAParam.join(\';\'));\nOA_spc += "\'><" + "/script>";\ndocument.write(OA_spc);\nfunction OA_show(name) {\nif (typeof (OA_output[name]) == \'undefined\') {\nreturn;\n} else {\ndocument.write(OA_output[name]);\n}\n}\nfunction OA_show_Browser_Width(o) {\nvar a = $.extend(true, { \'div\': \'\', \'width\': 0, \'height\': 0, \'url\': \'\', \'imp\': \'\', \'tarWidth\': 1200, scrolToLog: false }, o), b = document.getElementById(a.div)\n, c = function () { return window.top && window.top.innerWidth ? window.top.innerWidth : window.innerWidth ? window.innerWidth : 0; }\n, d = window.top && window.top !== window;\nif (b == null || b.innerHTML != \'\') { \nreturn; \n}\nvar _tarPos = function () {\nvar _b = $(b).offset().top, _c = $(window).scrollTop(), _h= $(window).height();\nreturn _c + _h > _b && _c < _b;\n}\nvar _fn = function () {\nif (c() < a.tarWidth) {\nreturn;\n} else if (a.scrolToLog) {\nif (!_tarPos())\nreturn;\t\n}\nvar s = [];\ns.push(\'<iframe hspace="0" vspace="0" frameborder="0" scrolling="no" style="width:\' + a.width + \'px;height:\' + a.height + \'px;border:none;margin:0;padding:0;border-color:#000" src="\' + a.url + \'"></iframe>\');\ns.push(\'<img src="\' + a.imp + \'" alt="" style="width: 0px; height: 0px;" />\');\nb.style.width = a.width;\nb.style.height = a.height;\nb.innerHTML = s.join(\'\');\n$(window).unbind(\'resize scroll\', _fn);\nif (d) {\nwindow.parent.SetFrameHeight($(document).height());\n}\n}\nif (a.scrolToLog) {\nif (_tarPos() && c() >= a.tarWidth) {\n_fn();\n}\nelse {\n$(window).bind(\'resize scroll\', _fn);\n}\n} else if (c() >= a.tarWidth) {\n_fn();\n} else {\n$(window).bind(\'resize\', _fn);\n}\n}\nfunction OA_ChkValid(a, b, c) {\ntry {\nvar _a = OA_output[a];\nif (!(_a != null && _a != undefined && _a != \'\')) {\ntypeof b == \'function\' ? b.apply(this, [{ ID: a }]) : \'\';\n} else if (_a && $.trim(_a.replace(/\\<\\!\\-\\-[^\\n]*\\-\\-\\>/g, \'\')).length == 0) {\ntypeof b == \'function\' ? b.apply(this, [{ ID: a }]) : \'\';\n} else {\ntypeof c == \'function\' ? c.apply(this, [{ ID: a }]) : \'\';\n}\n} catch (e) { }\n}\nfunction OA_ScrollToShow(id, name) {\nvar _tarPos = function () {\nvar _b = $(id).offset().top, _c = $(window).scrollTop(), _h = $(window).height();\nreturn _c + _h > _b && _c < _b;\n}\nvar _fn = function () {\ntry{\nif (!_tarPos())\nreturn;\n$(id).append(OA_output[name]);\n$(window).unbind(\'scroll\', _fn);\n} catch(e) {$(window).unbind(\'scroll\', _fn);}\n}\nif ($(id).length == 0 || typeof (OA_output[name]) == \'undefined\' || OA_output[name] == \'\') { return; } else { setTimeout(function () { $(window).bind(\'scroll\', _fn); }, 0); }\n}</script><script type="text/javascript" src="//hkg8.aastocks.com/ad/delivery/spc.php?zones=Super_Banner%3D55%7CLREC%3D58%7CCrazy_iPad_popup%3D331%7C&amp;nz=1&amp;source=&amp;r=52533860&amp;block=1&amp;blockcampaign=1&amp;custom_zone=1&amp;charset=UTF-8&amp;loc=https%3A//www.aastocks.com/en/stocks/market/ipo/iponews.aspx&amp;aaparam=0"></script><link href="/en/favicon.ico?v=1.2.15" rel="icon"><link href="/en/favicon.ico?v=1.2.15" rel="shortcut icon" type="image/x-icon"><title>\nIPO Plus - IPO News\n</title></head> <body id="stock" class="eng resizeable"><div id="aamessage" style="position:relative; background-color:#d6dbe0; display:none;"><div id="aamessage_box" style="position:relative; margin:0px auto; padding-top:10px; width:980px; color:#4a535b; font-size:13px; line-height:14px; text-align:center;"></div><div style="position:absolute; top:calc(50% - 15px); left:0px; width:100%; height:30px; z-index:1;"><div style="position:relative; margin:0px auto; width:980px;"><div id="aamessage_close" style="float:right; padding:0px 10px; min-width:48px; text-align:center; font-size:15px; line-height:28px; color:#4a535b; border:1px solid #4a535b; border-radius:4px; cursor:pointer; z-index:1;">Close</div><div style="clear:both;"></div></div></div></div> <div id="divFSMask" style="position:absolute; filter:alpha(opacity=80); zoom:1; opacity:0.8; top:0px; left:0px; width:100%; background:black; height:100%; z-index:100; display:none"></div> <div id="CrazyiPadPopup"><script type="text/javascript">OA_show(\'Crazy_iPad_popup\');</script></div> <div class="div980"></div> <script type="text/javascript">\nis980Mode = $(".div980").is(":visible");\ncurWidth980Mode = is980Mode;\n$(window).resize(function () {\nis980Mode = $(".div980").is(":visible");\n});\n</script> <form method="post" action="iponews.aspx" id="mainForm"> <div class="aspNetHidden"> <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="nYZZ/RhUXkE8shqTmO/mK9DGyx8PAfCCEi1Z73JcRyi/11l0DuVULvPHXKayNGrk7Vc3cdx4XYZ9lSlPCEqJ7a0RPT59T7xs2yZLXP4O2Ha9J3f/cOw2InhS2c9+hHwa6GGy3w=="> </div> <div class="container"> </div> <div class="container" style="position:relative; z-index:3;" id="divMasterHead"> <div id="topPanel"> <div class="blue-line"> <div class="container"> <div class="float_l AASTOCKSHome" style="position:relative; top:10px; "> <div style="height: 20px; line-height: 20px; padding-left:0px;" class="float_l icon_marginright" onclick="setHomepage()"><a href="#" onclick="return false;" class="curpointer" title="Set Homepage"><div class="header_icon_map2 icon_sethome jshoverwithclass" hover="hoveron"></div></a></div> <div style="height: 20px; line-height: 20px; padding-left:0px;" class="float_l icon_marginright"><a href="/en/memberinfo/feedback.aspx" class="curpointer" title="Feedback"><div class="header_icon_map2 icon_contact jshoverwithclass" hover="hoveron"></div></a></div> <div style="width:1px; height: 20px; line-height: 20px; background-color:#006e97;" class="float_l icon_marginright"></div> <div style="height: 20px; line-height: 20px;" class="float_l icon_marginright lang-btn"><a id="bLang1" class="jshoverwithclass tc" hover="hoveron" href="javascript:toLang(\'tc\')">繁</a></div> <div style="height: 20px; line-height: 20px;" class="float_l icon_marginright lang-btn"><a id="bLang2" class="jshoverwithclass sc" hover="hoveron" href="javascript:toLang(\'sc\')">简</a></div> <div style="width:1px; height: 20px; line-height: 20px; background-color:#006e97;" class="float_l icon_marginright"></div> <div style="height: 20px; line-height: 20px; padding-left:0px;" class="float_l icon_marginright"><a href="https://www.facebook.com/AAStocks.com.Limited/" class="curpointer" title="FACEBOOK FAN PAGE" target="_blank"><div class="header_icon_map2 icon_facebook jshoverwithclass" hover="hoveron"></div></a></div> <div style="width:1px; height: 20px; line-height: 20px; background-color:#006e97;" class="float_l icon_marginright"></div> <div style="height: 20px; line-height: 20px;" class="float_l icon_marginright"> <a href="https://itunes.apple.com/hk/app/id368726182?mt=8" target="_blank" class="curpointer"> <div class="topslidebox"> <div style="position:absolute; width:100%; height:100%; z-index:1;"></div> <table><tbody><tr><td><div class="header_icon_map2 icon_topiphone"></div></td><td style="padding-left:9px;"><span style="white-space:nowrap;">Market+ (iPhone)</span></td></tr></tbody></table> </div> </a> </div> <div style="height: 20px; line-height: 20px;" class="float_l icon_marginright"> <a href="https://play.google.com/store/apps/details?id=com.aastocks.dzh&amp;hl=en" target="_blank" class="curpointer"> <div class="topslidebox"> <div style="position:absolute; width:100%; height:100%; z-index:1;"></div> <table><tbody><tr><td><div class="header_icon_map2 icon_topandroid"></div></td><td style="padding-left:9px;"><span style="white-space:nowrap;">Market+ (Android)</span></td></tr></tbody></table> </div> </a> </div> <div style="height: 20px; line-height: 20px;" class="float_l"> <a href="/en/mobile/default.aspx" class="curpointer"> <div class="topslidebox"> <div style="position:absolute; width:100%; height:100%; z-index:1;"></div> <table><tbody><tr><td><div class="header_icon_map2 icon_topmobile"></div></td><td style="padding-left:13px;"><span style="white-space:nowrap;">Mobile Site</span></td></tr></tbody></table> </div> </a> </div> </div> <div class="tp-box float_r jshoverwithclass" hover="hoveron" onclick="window.location.href=\'/en/usq/default.aspx\'"> <div class="header_icon_map_streaming tpbox_realtime"></div> <div class="tpbox_realtime_text bold" hover="hoveron">US STOCKS</div> </div> <div class="tp-box float_r " onclick="window.location.href=\'/en/funds/default.aspx\'"> <div class="bold jshoverwithclass" hover="hoveron">FUNDS</div> </div> <div class="tp-box float_r " onclick="window.location.href=\'/en/forex/default.aspx\'"> <div class="bold jshoverwithclass" hover="hoveron">FX &amp; CRYPTO</div> </div> <div class="tp-box float_r " onclick="window.location.href=\'/en/cnhk/default.aspx\'"> <div class="bold jshoverwithclass" hover="hoveron">SH/SZ-HK</div> </div> <div class="tp-box float_r sel" onclick="window.location.href=\'/en/\'"> <div class="bold " hover="hoveron">HK STOCKS</div> </div> <div class="clear"></div> </div> </div> <style type="text/css">\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-1 { width:30px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-2 { width:55px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-3 { width:20px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-4 { width:30px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-5 { width:50px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-6 { width:55px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-1 { width:40px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-2 { width:55px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-3 { width:20px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-4 { width:30px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-5 { width:50px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-6 { width:45px; }\n@media screen and (min-width: 1100px) {\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-1 { width:35px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-2 { width:62px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-3 { width:25px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-4 { width:35px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-5 { width:58px; }\n#topPanel .tp-index .tp-index-td2 .tp-index-td2-6 { width:65px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-1 { width:52px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-2 { width:55px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-3 { width:25px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-4 { width:35px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-5 { width:57px; }\nbody.eng #topPanel .tp-index .tp-index-td2 .tp-index-td2-6 { width:50px; }\n}\n</style> <script type="text/javascript">\n/* Forex Function */\nfunction forexquote() {\nvar symbol = \'EURUSD\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nfxquote(symbol);\n}\nfunction forexchartquote() {\nvar symbol = \'EURUSD\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nfxchart(symbol);\n}\nfunction quote(value) {\nfxquote(value);\n}\nfunction fxquote(value) {\nif (value == "UDI") {\nwindow.location.href = "/en/forex/quote/dollarindex.aspx";\n} else {\nwindow.location.href = "/en/forex/quote/quote.aspx?symbol=" + encodeURIComponent(value);\n}\n}\nfunction fxchart(value) {\nwindow.location.href = "/en/forex/quote/chart.aspx?symbol=" + encodeURIComponent(value);\n}\nfunction ctquote(value) {\nwindow.location.href = "/en/forex/crypto/quote.aspx?symbol=" + encodeURIComponent(value);\n}\nfunction ctchart(value) {\nwindow.location.href = "/en/forex/crypto/quote.aspx?symbol=" + encodeURIComponent(value);\n}\n/* End of Forex Function */\n/* US Function */\nfunction uschart(value) {\nwindow.location.href = "/en/usq/quote/chart.aspx?symbol=" + encodeURIComponent(value);\n}\nfunction usquotewvalue() {\nvar symbol = \'AAPL\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nusquote(symbol);\n}\nfunction usquotewvalue2() {\nvar symbol = \'AAPL\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nusquote(symbol);\n}\nfunction uschartwvalue() {\nvar symbol = \'AAPL\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nuschart(symbol);\n}\nfunction uschartwvalue2() {\nvar symbol = \'AAPL\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nuschart(symbol);\n}\nfunction usquote(value) {\nwindow.location.href = "/en/usq/quote/quote.aspx?symbol=" + encodeURIComponent(value);\n}\nfunction usnews(value) {\nwindow.location.href = "/en/usq/quote/stock-news.aspx?symbol=" + encodeURIComponent(value);\n}\n// End of US Function\n// Stock Function\nfunction hkquotewvalue() {\nvar symbol = \'00001\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nhkquote(symbol);\n}\nfunction hkchartwvalue() {\nvar symbol = \'00001\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nhkchart(symbol);\n}\nfunction hkquote(value, target) {\nif (typeof target != "undefined") {\nwindow.open("/en/stocks/quote/quick-quote.aspx?symbol=" + encodeURIComponent(value), target);\n} else {\nwindow.location.href = "/en/stocks/quote/quick-quote.aspx?symbol=" + encodeURIComponent(value);\n}\n}\nfunction hkchart(value, target) {\nif (typeof target != "undefined") {\nwindow.open(\'/en/stocks/quote/detailchart.aspx?symbol=\' + encodeURIComponent(value), target);\n} else {\nwindow.location.href = \'/en/stocks/quote/detailchart.aspx?symbol=\' + encodeURIComponent(value);\n}\n}\nfunction hknewswvalue(value) {\nvar symbol = \'00001\';\nsymbol = value != null ? (value || symbol) : symbol;\nwindow.location.href = \'/en/stocks/analysis/stock-aafn/{0}/{1}/{2}/{3}\'.replace("{0}", symbol).replace("{1}", "0").replace("{2}", "hk-stock-news").replace("{3}", "1");\n}\nfunction hknews() {\nvar symbol = \'00001\';\nsymbol = inputControl_txtSymbol != null ? (inputControl_txtSymbol.GetSymbol() || symbol) : symbol;\nwindow.location.href = \'/en/stocks/analysis/stock-aafn/{0}/{1}/{2}/{3}\'.replace("{0}", symbol).replace("{1}", "0").replace("{2}", "hk-stock-news").replace("{3}", "1");\n}\nfunction hknews2(value, target) {\nif (typeof target != "undefined") {\nwindow.open(\'/en/stocks/analysis/stock-aafn/{0}/{1}/{2}/{3}\'.replace("{0}", value).replace("{1}", "0").replace("{2}", "hk-stock-news").replace("{3}", "1"), target);\n} else {\nwindow.location.href = \'/en/stocks/analysis/stock-aafn/{0}/{1}/{2}/{3}\'.replace("{0}", value).replace("{1}", "0").replace("{2}", "hk-stock-news").replace("{3}", "1");\n}\n}\nfunction hkipo(t

In [120]:
import html  # This is the key import!

def extract_news_list(driver, timeout=20):
    news_items = []
    
    wait = WebDriverWait(driver, timeout)
    wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "div[ref^='NOW.']")))
    
    news_blocks = driver.find_elements(By.CSS_SELECTOR, "div[ref^='NOW.']")
    
    for block in news_blocks:
        item = {"title": "", "date": "", "content": "", "link": "", "image_url": None}
#         print(block.get_attribute("outerHTML"))
        
        try:
            # === TITLE: Get from title attribute AND unescape HTML entities ===
            title_link = block.find_element(By.CSS_SELECTOR, "a[id*='lnkNews_']:not([id*='lnkNewsImage'])")
            raw_title = title_link.get_attribute("title") or title_link.text.strip()
            if raw_title:
                # This converts &amp;lt; → <, &amp;gt; → >, &amp;#39; → ', etc.
                clean_title = html.unescape(raw_title)
                # Optional: remove the <IPO> tag if you don't want it
                clean_title = clean_title.replace("<IPO>", "").strip()
                item["title"] = clean_title
            else:
                item["title"] = "[No title]"
        except Exception as e:
            item["title"] = "[Title error]"
        
        try:
            item["link"] = title_link.get_attribute("href")
            if item["link"] and not item["link"].startswith("http"):
                item["link"] = "https://www.aastocks.com" + item["link"]
        except:
            pass
        
        # === DATE ===
        try:
            time_text = block.find_element(By.CSS_SELECTOR, ".newstime4 .inline_block").text.strip()
            # Extract YYYY/MM/DD part
            import re
            match = re.search(r'(\d{4}/\d{1,2}/\d{1,2})', time_text)
            if match:
                y, m, d = match.group(1).split("/")
                item["date"] = f"{int(d):02d}/{int(m):02d}/{y}"
            else:
                item["date"] = "[Unknown]"
        except:
            item["date"] = "[Unknown]"
        
        # === CONTENT ===
        try:
            content = block.find_element(By.CSS_SELECTOR, ".newscontent4")
            text = content.text.strip()
            footer = "~AAStocks Financial NewsWeb Site: www.aastocks.com"
            if text.endswith(footer):
                text = text[:-len(footer)].strip()
            item["content"] = text or "[No content]"
        except:
            item["content"] = "[No content]"
        
        # === IMAGE (optional) ===
        try:
            img = block.find_element(By.CSS_SELECTOR, ".newsImage4a img")
            item["image_url"] = img.get_attribute("src")
        except:
            pass
        
#         print(item)
        
        if item["title"] and item["title"] not in {"[No title]", "[Title error]"}:
            news_items.append(item)
    
    return news_items

In [121]:
news_list = extract_news_list(driver)

In [125]:
current_ipo_news = [news for news in news_list if news["date"] in data_range]
current_ipo_news

[{'title': 'GUOXIA TECH Closes Up 128.4% to $45.9 at Midday',
  'date': '16/12/2025',
  'content': 'On debut today, GUOXIA TECH(02655.HK) opened at $38, up 89.1% from the listing price of $20.1. Peaking/ bottoming at $46.8/37.84, the stock closed midday at $45.9, up 128.4% from the listing price of $20.1, on volume of 6.86 million shares and turnover of $268.28 million.',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490647/ipo-news/AAFN',
  'image_url': 'https://plib.aastocks.com/aafnnews/image/medialib/20191017105312335_s.jpg'},
 {'title': "Nearly Half of 15 Firms Invested in by C Capital's Fund Plan to Go Public Next Yr",
  'date': '16/12/2025',
  'content': 'C Capital, co-founded by former NEW WORLD DEV (00017.HK) CEO Adrian Cheng, has invested in around 15 companies through its blind pool fund.C Capital CEO Ben Cheng told Hong Kong media that seven of the abovementioned 15 companies are planning to go public next year in Hong Kong, Mainland China, or the US, including GPU company B...',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490592/ipo-news/AAFN',
  'image_url': 'https://plib.aastocks.com/aafnnews/image/medialib/20191017105308849_s.jpg'},
 {'title': 'GUOXIA TECH Opens Up 89.1% to $38 on Debut',
  'date': '16/12/2025',
  'content': 'GUOXIA TECH(02655.HK) opened at $38 on debut today, up 89.1% from the listing price of $20.1, 3.98 million shares traded at market open.',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490586/ipo-news/AAFN',
  'image_url': 'https://plib.aastocks.com/aafnnews/image/medialib/20180115141815344_s.jpg'},
 {'title': 'Tibet Miner ZHIHUI MINING Records Margin Oversubscription ~3,355x',
  'date': '16/12/2025',
  'content': 'ZHIHUI MINING (02546.HK), a Tibet mining company, will conclude its IPO period today (16th) at noon.According to market data, as of around 9 am today, ZHIHUI MINING received a margin of more than HKD184.58 billion from brokers, making it a highly sought-after new stock recently.Based on the public offering portion raising around...',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490589/ipo-news/AAFN',
  'image_url': 'https://plib.aastocks.com/aafnnews/image/medialib/20251211084227609_s.png'},
 {'title': 'Guoxia Technology Closes Up 88.1% to $37.8 on Gray Mkt',
  'date': '15/12/2025',
  'content': 'Guoxia Technology(02655.HK), which will be listed tomorrow, opened up 20.2% to $24.16 on gray market. Peaking/ bottoming at $40/24.16, it closed at $37.8, up 88.1% or $17.70 from the listing price, on volume of 1.88 million shares and turnover of $67.4 million, according to PhillipMart data. Excluding handling fee, the book gain...',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490478/ipo-news/AAFN',
  'image_url': 'https://plib.aastocks.com/aafnnews/image/medialib/20180126163240922_s.jpg'},
 {'title': 'Guoxia Technology Opens Up 19.4% to $24 on Gray Mkt',
  'date': '15/12/2025',
  'content': '[No content]',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490424/ipo-news/AAFN',
  'image_url': None},
 {'title': 'HashKey  Priced at $6.68/ Shr, Raising $1.6B: Wire',
  'date': '15/12/2025',
  'content': '[No content]',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490375/ipo-news/AAFN',
  'image_url': None},
 {'title': 'QINGSONG HEALTH IPO Starts Tdy w/ Entry Fee HKD4,581.75',
  'date': '15/12/2025',
  'content': '[No content]',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490301/ipo-news/AAFN',
  'image_url': None},
 {'title': 'HANXBIO-B IPO Begins w/ Entry Fee HKD3,232.27, Attracting 7 Cornerstone Investors',
  'date': '15/12/2025',
  'content': '[No content]',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490292/ipo-news/AAFN',
  'image_url': None},
 {'title': 'NUOBIKAN IPO Begins Tdy w/ Entry Fee HKD5,353.45 for Board Lot of 50 Shrs',
  'date': '15/12/2025',
  'content': '[No content]',
  'link': 'https://www.aastocks.com/en/stocks/news/aafn-con/NOW.1490285/ipo-news/AAFN',
  'image_url': None}]

In [129]:
prompt = f"""
You are an expert financial news summarizer specializing in Hong Kong IPO and stock market updates.

Your task is to read the following list of raw news items (each with title, date, and content) and produce a concise daily bulletin in English.

Instructions:
- Cover EVERY news item in the list — do not skip any, even if it seems less significant.
- Identify the main company/stock (e.g., from stock code like (02655.HK) or name in title/content) for each item.
- If multiple items are about the SAME company/stock, group them under ONE bullet point and combine into a coherent summary (merge details chronologically or logically; do not list titles separately).
- If an item is about a unique company/stock (or general/non-company-specific), give it its own bullet point.
- For each bullet, start with the company/stock name/code prominently, then summarize in 1–2 sentences.
- Prioritize recent details within groups (use dates if relevant).
- Skip items with "[No content]" only if the title adds no value; otherwise, summarize the title alone.
- Sort the final bullets by recency (newest items/companies first).
- Do not include links, image URLs, or source mentions.

Output format: A list of bullet points only. No introduction, no conclusion.

Here is today's raw news data:

{json.dumps(current_ipo_news, indent=2)}

Now generate the summary bulletin.

"""

In [130]:
response = await client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

ipo_news = response.choices[0].message.content.strip()

In [131]:
ipo_news

"- **GUOXIA TECH (02655.HK)**: On its debut on December 16, 2025, GUOXIA TECH opened at $38, up 89.1% from its listing price of $20.1, and peaked at $46.8 before closing midday at $45.9, marking a 128.4% increase. Prior to its official listing, the stock closed at $37.8 in the gray market on December 15, 2025, up 88.1% from the listing price.\n\n- **ZHIHUI MINING (02546.HK)**: The IPO of ZHIHUI MINING, a Tibet mining company, garnered significant interest as it recorded a margin oversubscription of approximately 3,355 times on December 16, 2025, with about HKD 184.58 billion received by brokers.\n\n- **C Capital**: As of December 16, 2025, nearly half of the 15 firms invested in by C Capital's fund plan to go public next year, including various companies with intentions to list in Hong Kong, Mainland China, or the US. C Capital was co-founded by Adrian Cheng, former CEO of NEW WORLD DEV (00017.HK)."

In [133]:
send_regulatory_summary_email("HK IPO news", ipo_news)

✅ Corporate announcement summary sent successfully to davidlau512@gmail.com!

True

In [78]:
news_blocks = driver.find_elements(By.CSS_SELECTOR, "div[ref^='NOW.']")

In [84]:
for block in news_blocks:
    item = {"title": "", "date": "", "content": ""}

    try:
        # 1. Title - inside <a> with id containing "lnkNews"
        title_elem = block.find_element(By.CSS_SELECTOR, "a[id*='lnkNews']")
        item["title"] = title_elem.text.strip()
        # Fallback if text is empty (sometimes title is in attribute)
        if not item["title"]:
            item["title"] = title_elem.get_attribute("title") or ""
        item["title"] = item["title"].replace("<IPO>", "").strip()  # clean tags if needed
    except:
        item["title"] = "[No title found]"

    try:
        # 2. Date - inside script with ConvertToLocalTime or visible text like "2025/12/16 12:15"
        time_divs = block.find_elements(By.CSS_SELECTOR, ".newstime4")
        date_text = ""
        for div in time_divs:
            text = div.text.strip()
            if not text:
                # Check inner script
                scripts = div.find_elements(By.TAG_NAME, "script")
                for s in scripts:
                    script_text = s.get_attribute("innerHTML")
                    match = date_pattern.search(script_text)
                    if match:
                        date_text = match.group(1)
                        break
            else:
                match = date_pattern.search(text)
                if match:
                    date_text = match.group(1)
                    break
            if date_text:
                break

        if date_text:
            # Convert "2025/12/16" → "16/12/2025"
            y, m, d = date_text.split("/")
            item["date"] = f"{int(d):02d}/{int(m):02d}/{y}"
        else:
            item["date"] = "[Unknown date]"
    except:
        item["date"] = "[Unknown date]"

    try:
        # 3. Content - in div with class "newscontent4"
        content_elem = block.find_element(By.CSS_SELECTOR, ".newscontent4")
        item["content"] = content_elem.text.strip()
        # Remove trailing "~AAStocks Financial News..." if present
        if item["content"].endswith("~AAStocks Financial NewsWeb Site: www.aastocks.com"):
            item["content"] = item["content"][:-len("~AAStocks Financial NewsWeb Site: www.aastocks.com")].strip()
    except:
        item["content"] = "[No content]"

    # Only add if we got at least a title
    if item["title"] and item["title"] != "[No title found]":
        news_items.append(item)

test
<selenium.webdriver.remote.webelement.WebElement (session="927e3d9fdcf20f05a4567c40cae1b4ea", element="f.3AA6C2CF3E2F3FE490D6AB2642E8C7FD.d.B8825C1235F4D835B911767AD91874AC.e.67")>

In [40]:
pdf_path = os.path.join(os.getcwd(), "2025121500019.pdf")

documents = SimpleDirectoryReader(
    input_files=[pdf_path],
).load_data()                

summary_index = SummaryIndex(documents)

summary_query_engine = summary_index.as_query_engine(
    response_mode="tree_summarize",
    use_async=True,
)

In [41]:
prompt='''
You are an expert financial analyst specializing in IPO prospectuses. Summarize the provided document in a detailed, structured manner, focusing on the company's business, financials, offering details, and key parties. Use clear sections with bullet points for readability. Avoid legal jargon; explain concepts simply. If information is missing or unclear, note it explicitly.

Structure your summary as follows:

1. **Company Overview**: Describe the company's main business, industry, products/services, history, and competitive position. Include any key risks or growth strategies mentioned.

2. **Key Financials**: Summarize recent financial performance, including revenue, profit/loss, EBITDA (if applicable), balance sheet highlights (e.g., assets, liabilities, cash position), and any trends or projections. Cover the last 2-3 years if available.

3. **Offering Structure**: Detail the IPO mechanics, including:
   - Total number of shares offered (public offer vs. international placement).
   - Price range or final offer price.
   - Net proceeds and intended use (e.g., expansion, debt repayment).
   - Cornerstone investors (names, amounts committed, lock-up periods).

4. **Parties Involved**: List key external parties, including:
    - Sponsor, Overall Coordinator, Global Coordinator, Joint Bookrunner and Joint Lead Manager

Base your summary solely on the document content. If a section lacks data, state "Not specified in the prospectus." Keep the total response under 1,000 words, prioritizing accuracy and neutrality.
'''

response = summary_query_engine.query(prompt)
print(response)

BadRequestError: Error code: 400 - {'error': {'message': 'This endpoint\'s maximum context length is 128000 tokens. However, you requested about 150997 tokens (146997 of text input, 4000 in the output). Please reduce the length of either one, or use the "middle-out" transform to compress your prompt automatically.', 'code': 400, 'metadata': {'provider_name': None}}}

In [32]:
llm

OpenRouter(callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x000001FF59A43D50>, system_prompt=None, messages_to_prompt=<function messages_to_prompt at 0x000001FF45F2CF40>, completion_to_prompt=<function default_completion_to_prompt at 0x000001FF46118220>, output_parser=None, pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>, query_wrapper_prompt=None, model='anthropic/claude-3-haiku', temperature=0.1, max_tokens=4000, logprobs=None, top_logprobs=0, additional_kwargs={}, max_retries=5, timeout=900.0, default_headers=None, reuse_client=True, api_key='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', api_base='https://openrouter.ai/api/v1', api_version='', strict=False, reasoning_effort=None, modalities=None, audio_config=None, context_window=3900, is_chat_model=True, is_function_calling_model=False, tokenizer=None)

In [2]:
import yfinance as yf

def get_price_stats(ticker: str) -> dict:
    """
    Returns:
      - current_price
      - last_close (last trading day's close)
      - ytd_close (last trading close of previous calendar year)
      - pct_change_ytd (from ytd_close to current)
    """
    t = yf.Ticker(ticker)

    # Current price (fallbacks included)
    info = getattr(t, "fast_info", {}) or {}
    current = info.get("last_price") or info.get("regularMarketPrice")
    if current is None:
        current = t.history(period="1d")["Close"].iloc[-1]

    # Last trading day's close
    last_close = info.get("previous_close") or info.get("regularMarketPreviousClose")
    if last_close is None:
        last_close = t.history(period="5d")["Close"].dropna().iloc[-1]

    # YTD close = last trading close of previous calendar year
    hist = t.history(period="max")
    if hist.empty:
        raise ValueError(f"No price history for {ticker}")

    current_year = hist.index[-1].year
    prev_year = hist[hist.index.year < current_year]
    if prev_year.empty:
        raise ValueError(f"Not enough history to compute ytd_close for {ticker}")

    ytd_close = prev_year["Close"].iloc[-1]
    pct_change_ytd = (current / ytd_close - 1.0) * 100.0

    return {
        "ticker": ticker,
        "current_price": float(current),
        "last_close": float(last_close),
        "ytd_close": float(ytd_close),
        "pct_change_ytd": float(pct_change_ytd),
    }

In [3]:
def _safe_float(x):
    try:
        if x is None:
            return None
        return float(x)
    except Exception:
        return None

def _latest_close(ticker):
    try:
        s = ticker.history(period="5d")["Close"].dropna()
        if s.empty:
            return None
        return float(s.iloc[-1])
    except Exception:
        return None


def _previous_close(ticker):
    info = getattr(ticker, "fast_info", {}) or {}
    val = info.get("previous_close") or info.get("regularMarketPreviousClose")
    v = _safe_float(val)
    if v is not None:
        return v
    # Fallback: last available close (can be same as "current" if market is closed)
    return _latest_close(ticker)

In [4]:
ticker = yf.Ticker("^HSI")
# _previous_close(ticker)

In [5]:
info = getattr(ticker, "fast_info", {})
info

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

In [6]:
ticker.history(period="2d")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-21 00:00:00+08:00,26397.039062,26692.779297,26397.039062,26585.060547,2998700000,0.0,0.0
2026-01-22 00:00:00+08:00,26750.509766,26779.220703,26499.140625,26541.720703,0,0.0,0.0

In [31]:
async def fetch_article_html(url):
    """Fetch the HTML content of an article page"""
    try:
        html_dict = extract_html.get_raw_html(url)
        if html_dict and html_dict.get("html"):
            return html_dict["html"]
        return None
    except Exception as e:
        print(f"    WARNING: Error fetching article HTML: {e}")
        return None

In [32]:
html_content = await fetch_article_html("https://news.futunn.com/en/post/66803841/ipo-news-minimax-a-globally-leading-ai-large-model-company?level=1&data_ticket=1767075888981595")

In [36]:
clean_text = remove_html_tags(html_content)
if len(clean_text) > 200000:
    clean_text = clean_text[:200000] + "..."

In [41]:
clean_text.replace("\n", "").replace("  ", " ")

'  IPO News | MiniMax, a globally leading AI large model company, has launched its initial public offering with cornerstone investors including Alibaba and Abu Dhabi. The minimum subscription amount is HKD 3,333.28.        Investing                 Stocks                    HK Stocks                     US Stocks                     JP Stocks                     A-Shares                     Margin Trading                     IPO                     Invest Regularly                    Derivatives & Cryptos                    ETF                     Options                     Futures                     Crypto                     Futu Money Plus                    Cash Plus                     Funds                     US Treasuries                     Structured Products                    Futu PWM                    Private Wealth Management                     Trust Services                  Go FUTU Securities check more                >               Markets                 Quotes                    Stocks                     Options                     Futures                     Forex                     ETF                    Trading Tools                    Paper Trade                     Stock Screener                     Heat Map                     Earnings Calendar                     Institutional Tracker                     Investment Themes                   App Store                  Download >                  Google Play                  Download >                  Mac                  Download >                  Windows                  Download >                News & Community                 News                    Headlines                     24/7 News                     Economic Calendar                     Topics                     Live                    Learn                    Library                     Courses                     Lectures                    Community                    Feeds                     Hot Topics                 Pricing              Promotions               Check more promotion                 >                  Welcome Rewards                    Join Futubull Membership Program                    Referral Program                    Transfer Bonus                 Blog              About Us                 About us >                    About Futu                     Futu Highlights                     Milestones                     Corporate Social Responsibility                     Contact us                     Join Us                     Futu I&E                     Futu Store                    Futu Experience Stores                    FUTU Flagship Store                    Shop A,B,C on Gound floor and shop A on 1st Floor, Soundwill Plaza , NO. 38 Russell Street, Causeway Bay, Hong Kong                    FUTU Store (Tsim Sha Tsui)                    G/F, 96 Nathan Road, Tsim Sha Tsui, Kowloon                    FUTU Store (Causeway Bay)                    G/F, Lai Yuen Apartments , 29-33 Lee Garden Road, Causeway Bay, Hong Kong                    FUTU Store（Mong Kok)                    G/F, 67-69 Argyle Street, Mongkok, Kowloon                    FUTU Head Office (Admiralty)                    34/F, United Centre, 95 Queensway, Admiralty, HK                    FUTU Store（Tsuen Wan)                    G/F, No. 280 Sha Tsui Road, Tsuen Wan, New Territories                    FUTU Store（Sha Tin)                    G09A, G/F, Kings Wing Plaza 1, No. 3 On Kwan Street, Sha Tin, New Territories                    FUTU Store (Tseung Kwan O)                    Shop UG16-17, UG/F, MCP Central, Tseung Kwan O, New Territories                  Check more                >               Support              More                 About Us                    About us                    Support                  English                繁體中文                简体中文             Sign up/Log in            Download            English           Back           Investing             Stocks                HK Stocks                 US Stocks                 JP Stocks                 A-Shares                 Margin Trading                 IPO                 Invest Regularly                Derivatives & Cryptos                ETF                 Options                 Futures                 Crypto                Futu Money Plus                Cash Plus                 Funds                 US Treasuries                 Structured Products                Futu PWM                Private Wealth Management                 Trust Services              Markets             Quotes                Stocks                 Options                 Futures                 Forex                 ETF                Trading Tools                Paper Trade                 Heat Map                 Earnings Calendar                 Institutional Tracker                 Investment Themes              News & Community             News                Headlines                 24/7 News                 Economic Calendar                 Topics                 Live                Learn                Library                 Courses                 Lectures                Community                Feeds                 Hot Topics              Pricing           Promotions              Welcome Rewards                Join Futubull Membership Program                Referral Program                Transfer Bonus             Blog           About Us              About us>                 About Futu                 Futu Highlights                 Milestones                 Corporate Social Responsibility                 Contact us                 Join Us                 Futu I&E                 Futu Store              Support           English           繁體中文           简体中文           Dark           Light          Open Account         Headlines        IPO News | MiniMax, a globally leading AI large model company, has launched its initial public offering with cornerstone investors including Alibaba and Abu Dhabi. The minimum subscription amount is HKD 3,333.28.         Stocks IPO           Topic             3078 news             51988 Subscribers            Subscribe          IPO News | MiniMax, a globally leading AI large model company, has launched its initial public offering with cornerstone investors including Alibaba and Abu Dhabi. The minimum subscription amount is HKD 3,333.28.           Futu News            ·            08:24            MINIMAX-WP             0.00%            Futu News reported on December 31st that            $MINIMAX-WP (00100.HK)$           An announcement was made regarding the offering from December 31 to January 6. The company plans to conduct a global offering of approximately 25,389,200 shares and is expected to be listed on January 9, 2026.           Company Overview           MiniMax is a globally leading general artificial intelligence technology company. The company has independently developed a series of multimodal large models, including MiniMax M2, Hailuo 2.3, Speech 2.6, and Music 2.0, which possess code and Agent capabilities as well as long-context processing abilities, enabling understanding, generation, and integration of various modalities such as text, audio, images, video, and music. Based on these self-developed models, the company has launched a series of AI-native products globally, including MiniMax Agent, Conch AI, MiniMax Audio, Xingye, and an open platform for enterprises and developers.           MiniMax\'s AI-native product portfolio has attracted a large user base, with average monthly active users (MAU) increasing more than sixfold from 3.1 million in 2023 to 19.1 million in 2024, and further rising to 27.6 million during the nine months ended September 30, 2025. As of September 30, 2025, MiniMax had over 212 million individual users across more than 200 countries and regions, as well as over 130,000 enterprise customers in more than 100 countries.           Financial Overview           In terms of financial performance, MiniMax’s revenue increased by 174.7% from $19.454 million during the nine months ended September 30, 2024, to $53.437 million (approximately RMB 376 million) during the same period in 2025. Revenue in 2023 was $3.46 million, and in 2024 it reached $30.523 million.           Industry Overview           The main tracks for large model applications currently include productivity, entertainment, visual generation, audio generation, and general B2B services, such as social media content recommendation systems, chatbots, intelligent personal assistants, autonomous driving systems, intelligent risk control models, and AI-assisted diagnostics.           Upon release, MiniMax\'s models achieved leading performance in text, video, and audio modalities, ranking highly on Artificial Analysis’s evaluation list and securing the top position among all open-source models. According to灼识谘询(CIC), in terms of global model-based revenue in 2024, MiniMax is the tenth-largest large model technology company globally and the fourth-largest pure-play large model technology company.           According to CIC, the global large model market is still in the early stages of commercial implementation. In terms of model-based revenue, the global large model market is expected to grow rapidly from $10.7 billion in 2024 to $206.5 billion in 2029, with a compound annual growth rate (CAGR) of 80.7%. The large model application market size is projected to increase from $7.1 billion in 2024 to $151.5 billion in 2029, with a CAGR of 84.3%. Meanwhile, the large model MaaS (Model-as-a-Service) market size is expected to grow from $3.6 billion in 2024 to $55 billion in 2029, with a CAGR of 72.7%.           IDC forecasts that by 2030, artificial intelligence will contribute a cumulative $19.9 trillion to the global economy and drive a 3.5% increase in global GDP by 2030.           Cornerstone Investors           Cornerstone investors have agreed to subscribe for a certain number of offer shares amounting to approximately $350 million at the offer price, subject to certain conditions. Assuming the offer price is HKD 158.0 (the median of the offer price range), the total number of offer shares to be subscribed by cornerstone investors will be 17,235,120 shares. Cornerstone investors include:           Abu Dhabi Investment Authority ("ADIA"), Alisoft China Holding Limited ("Alisoft China", an indirect wholly-owned subsidiary of Alibaba Group), Aspex Master Fund ("AMF"), Boyu, Huitianfu Hong Kong, Eastspring Investments (Singapore) Limited ("Eastspring"), E Fund Management Co., Ltd., IDG Breyer Capital Fund L.P. ("IDG Breyer Fund"), Janchor Funds, Martis Fund, L.P., Mirae Asset Securities, MPC VII, Perseverance Asset Management, and Taikang Life Insurance.           Use of Proceeds           In terms of the use of proceeds, MiniMax expects net proceeds from the global offering to amount to approximately HKD 3.8183 billion (assuming no exercise of the over-allotment option and based on a mid-range offer price of HKD 158). According to the prospectus, MiniMax intends to allocate the proceeds raised from the global offering for the following purposes:           Approximately 90% will be used for the company’s research and development over the next five years, including the development of the company’s large models and its AI-native products. Specifically, (i) around 70.0% will be invested in the R&D of large models over the next five years; and approximately 20.0% will be allocated toward the development, enhancement, and global scaling of AI-native products within the same timeframe. Approximately 10.0% will be allocated to working capital and general corporate purposes.           Further reading:            MiniMax Prospectus           The prime season for subscribing to new shares has arrived! Use Futu to subscribe to new shares with 0 interest, 0 handling fees, and 0 cash subscription. Participants in the current promotion have the chance to waive one year’s fees for subscribing to new shares.            Come and experience it now >>            Note: This activity is exclusively available to users in the Hong Kong region.           Editor/Afina            The translation is provided by third-party software.              The above content is for informational or educational purposes only and does not constitute any investment advice related to Futu. Although we strive to ensure the truthfulness, accuracy, and originality of all such content, we cannot guarantee it.               Risk Disclaimer                The above content is for informational or educational purposes only and does not constitute any investment advice related to Futu. Although we strive to ensure the truthfulness, accuracy, and originality of all such content, we cannot guarantee it.                Got It                 Risk Disclaimer                 The above content is for informational or educational purposes only and does not constitute any investment advice related to Futu. Although we strive to ensure the truthfulness, accuracy, and originality of all such content, we cannot guarantee it.                 Got It               Write a comment            0            0            0            Like            Love            Laughing Cry            Respect            Emm            Sad            Angry           Tap to Select a Mood           分享到weixin            分享到qq            分享到facebook            分享到twitter            分享到微博            粘贴板            Use the share button in your browser            to share the page with your friends           Tap here to share           No comments yet. Write one.            Market Insights                  Hot Stock                       Hot Stock                       Top HK stocks viewed in the last 24 hours, capturing market sentiment and key capital flow insights.                       Top HK stocks viewed in the last 24 hours, capturing market sentiment and key capital flow insights.                       No.                        Symbol                        % Chg                          Sample Name                            Sample Code                          +18.82%                          Sample Name                            Sample Code                          +16.67%                          Sample Name                            Sample Code                          +14.46%                         4                          APT SATELLITE                           01045                          +13.60%                         5                          ELEPHANT HLDGS                           08635                          +11.86%                      View More                    Invest with Futu!                     Invest with Futu!                     Hot Topics                      Hot Topics                    Monthly Market Outlook: Peak Earnings Season! How to Navigate November?                   In October, the U.S. stock market once again achieved a remarkable increase, with the three major indices hitting new record highs! Looking                    Show More                        年頭旺到年尾                            Nov 3 06:28                           October 31 review ..                           年頭旺到年尾                            Nov 6 09:38                           Market Review on November 5th *                     - No more -            Statement          This page is machine-translated. Futubull tries to improve but does not guarantee the accuracy and reliability of the translation, and will not be liable for any loss or damage caused by any inaccuracy or omission of the translation.          OK          About Us            Why Futu             Investor Relations             Join Us            Services            Pricing             Help Center             Tools            Policy            Disclaimer             Terms of Service             Privacy Statement            Customer Service            +852 2523 3588             Trading days: 24 hours             Non-trading days: 9:30-21:30            Other Inquiries            Business inquiries: +852 2523 3588             Business Partnerships：BD@futuhk.com             Media Contact：media@futuhk.com            Head Office (Admiralty)            34/F, United Centre, 95 Queensway, Admiralty, HK             Opening hours: 9:00 am-6:00 pm; 12:00 nn-1:00 pm ( From Monday to Friday， except Public Holidays)            FUTU Store           Flagship Store            Tsim Sha Tsui            Tsuen Wan            Mong Kok            Causeway Bay            Tseung Kwan O            Sha Tin             address:               Shop A,B,C on Gound floor and shop A on 1st Floor, Soundwill Plaza , NO. 38 Russell Street, Causeway Bay, Hong Kong               Opening Hours:               Monday to Saturday: 10:00am - 9:00pm               Sunday and public holidays 10:00am - 9:00pm               Address:               G/F, 96 Nathan Road, Tsim Sha Tsui, Kowloon               (Tsim Sha Tsui MTR station exit B1, Opposite to ‘The ONE’)               Opening Hour:              Monday to Saturday: 10:00 am - 9:00 pm              Sunday and public holidays: 10:00 am - 6:00 pm              Address:               G/F, No. 280 Sha Tsui Road, Tsuen Wan, New Territories               (Opposite to \'Tai Hung Fai Centre\')               Opening Hours:               Monday to Saturday: 10:00 am - 7:00 pm               Sunday and public holidays: 10:00 am - 6:00 pm               address:               G/F, 67-69 Argyle Street, Mongkok, Kowloon               (Opposite to Mong Kok MTR station exit D2)               Opening Hours:               Monday to Saturday: 10:00 am - 9:00 pm               Sunday and public holidays: 10:00 am - 6:00 pm               address:               G/F, Lai Yuen Apartments , 29-33 Lee Garden Road, Causeway Bay, Hong Kong               （Causeway Bay MTR station exit F1)               Opening Hours:               Enhancement works will be carried out from 5 December to 16 January.               address:               Shop UG16-17, UG/F, MCP Central, Tseung Kwan O, New Territories               Opening Hours:               Monday to Saturday: 10:00am - 9:00pm               Sunday and public holidays 10:00am - 6:00pm               address:               G09A, G/F, Kings Wing Plaza 1, No. 3 On Kwan Street, Sha Tin, New Territories               Opening Hours:               Monday to Saturday: 10:00am - 7:00pm               Sunday and public holidays 10:00am - 6:00pm             © 2025 FUTU.           Feedback & Suggestions           Report Information Security Vulnerability           Investor Relations           Agreement           Privacy           Futu Securities           FUTU I&E           Links           粤公网安备 44030502008587号           粤ICP备17008904号-3          © 2025 FUTU     '

In [25]:
async def is_article_from_today(client, clean_text, url):
    
    today = datetime.now()
    today_str = today.strftime("%B %d, %Y")  # e.g., "December 29, 2025"
    today_str_alt = today.strftime("%d %B %Y")  # e.g., "29 December 2025"
    today_str_short = today.strftime("%m/%d/%Y")  # e.g., "12/29/2025"
    
    prompt = f"""
You are analyzing a news article to determine if it was published today.

Today's date is: {today_str} (also known as {today_str_alt} or {today_str_short})

Here is the article content (extracted from HTML):
{clean_text}

Article URL: {url}

Look for publication date information in the article. This could be:
- A "Published" or "Updated" date
- A timestamp
- A date in the article metadata
- Any date information visible on the page

Determine if this article was published TODAY ({today_str}).

Return ONLY "YES" if the article is from today, or "NO" if it's from a different date.
If you cannot determine the date, return "NO".
"""
    
    try:
        response = await client.chat.completions.create(
            model="openai/gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=10,
        )
        
        result = response.choices[0].message.content.strip().upper()
        return result == "YES"
    except Exception as e:
        print(f"    WARNING: Error checking article date: {e}")
        return False  # Default to False if check fails

In [39]:
await is_article_from_today(client, clean_text.replace("\n", ""), "https://news.futunn.com/en/post/66790061/the-us-materials-sector-emerges-as-the-hidden-winner-of?chain_id=R4cqdOkIUz1fSH.1kl93t6&futusource=news_headline_list&global_content=%7B%22promote_id%22%3A13766%2C%22sub_promote_id%22%3A28%2C%22f%22%3A%22news.futunn.com%2Fen%2Fmain%22%7D&report_id=301133&report_type=market&src=3%2C3")

True